### ISSUE TITLE
[Android] OpenMedia(false) starts playback.

### ISSUE THREAD

**Issue by WASDMagician** [RenderHeads/UnityPlugin-AVProVideo#1283] opened 2022-09-05 03:32 UTC
**Describe the issue**
Calling OpenMedia on a MediaPlayer with AutoOpen and AutoStart set to false causes the media to start playing even when passing false as the autoPlay option.
Happens under both the Media Player and Exo video api's.
Prefer software decoder and Unity audio seem to prevent the issue but these are obviously not ideal solutions and have lead to desyncs for me in the past.
Doesn't happen in editor or in a windows build.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video - Core Edition - v2.6.1
 - Operating system version: Android 10
 - Device model: Oppo A15
 - Video specs (resolution, frame-rate, codec, file size): 360x480 - 25fps, mp4, 1.18MB

**To Reproduce**
1. In scene, prefab or code create a GameObject with a MediaPlayer component and assign a media reference.
2. Set Auto Open and Auto Play to false.
3. Reference the MediaPlayer in a script.
4. Call [MediaPlayer].OpenMedia(false)

**Comment by Ste-RH** [comment] 2022-09-05 10:18
This is a regression bug due to #1278 and will be fixed in the next version (v2.6.2).  We will likely release this in the coming week.

@WASDMagician if you require a fix before this, please [email](mailto:unitysupport@renderheads.com?subject=Github%20issue%201283) over your Unity Asset Store PDF invoice and we will send over a v2.6.1f2 release for you to test/use.

**Comment by Ste-RH** [comment] 2022-09-06 15:17
Fix verified.

**Closed** 2022-09-15 13:02 UTC
Labels: Android, Fixed
