### ISSUE TITLE
When playing video with AVPro, using the webview plugin in iOS to play audio or video will be suspended by AVPro.

### ISSUE THREAD

**Issue by 3wz** [RenderHeads/UnityPlugin-AVProVideo#167] opened 2019-09-06 07:12 UTC
Problem description:

iOS下使用UniWebView内置网页插件内播放视频或者音频的时候会把使用AVPro播放视频给卡主

Device (which devices are you having the issue with - model, OS version number):

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: plugin v1.9.17 scripts v1.10.0
Target Platform: Android
Unity: v2018.4.7f1 WindowsEditor
OS: Desktop - H81M-CT (TSINGHUA TONGFANG Computer) - Windows 10  (10.0.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz - 4 threads - 16320KB
GPU: Emulated GPU running OpenGL ES 3.0 - Emulated - OpenGL ES 3.0 [emulated] - 2017KB - 4096

**Comment by AndrewRH** [comment] 2019-09-06 14:20
Google Translate says 
"When playing video or audio in UniWebView's built-in webpage plugin under iOS, it will use AVPro to play video to the card owner."

Hmm...

**Comment by 3wz** [comment] 2019-09-06 14:29
it will make video paused

**Comment by 3wz** [comment] 2019-09-06 14:34
UniWebView is a mobileplatform webview plugin, I use it in unity to show some webpage and same time I use AVPro play video, but when webpage has audio or video , that makes the AVPro paused

**Comment by MorrisRH** [comment] 2019-09-09 17:27
I understand that the UniWebView video playback is fullscreen, this would cause Unity's view controller to lose focus and be suspended, stopping AVPro Video from playing. If this is the case then there is nothing we can do from our side as the issue is with UniWebView.

We might be able to better diagnose the issue with a sample project. If you can provide one, please send it to unitysupport@renderheads.com

**Comment by 3wz** [comment] 2019-09-10 14:17
you could choose an inline way to play your videos by UniWebView, and I test it .  but it also makes AVPro paused.

**Comment by MorrisRH** [comment] 2019-09-23 16:38
I'm afraid I cannot reproduce this.
I created a simple scene with a video player and opened a uniwebview after playback had started, the media continued to play underneath the WebView. When opening media in the WebView, both played together. On closing the WebView, the media player instance was still running.

**Closed by MorrisRH** 2019-09-23 16:38 UTC
Labels: Bug, CNR, iOS
