### ISSUE TITLE
Playback on macOS standalone and Unity Editor doens't work

### ISSUE THREAD

**Issue by paatz04** [RenderHeads/UnityPlugin-AVProVideo#116] opened 2019-07-10 08:06 UTC
Playback on macOS standalone and Unity Editor doesn't work, on iOS it renders fine, but on mac build or in the unity editor the video flashes red, or stays black - and multiple 10+ water mark logos appear - the time still updates, and it finishes correctly when it should - but rendering using Display UGUI doesn't work

 - Unity version: 2019.1.8f
 - AVPro Video version: 1.10
 - Operating system version: macOS 10.14.5
 - Device model: Macbook Pro 15" 2019
 - Video specs (resolution, frame-rate, codec, file size): 
1920p mp4 30fps h264

**Comment by MorrisRH** [comment] 2019-07-10 09:44
Please switch the renderer type to OpenGL Core for macOS.
Unfortunately there are compatibility issues with Metal and certain hardware configurations which we are currently working to resolve.

**Comment by paatz04** [comment] 2019-07-10 10:47
Thank you, that works. But I'm having issues with TMPro using Opengl core on mac standalone builds in combination of overlay canvasas - are you aware of any cross compatibility issues ? It doesn't appear to happen in the editor though...

**Comment by MorrisRH** [comment] 2019-07-10 16:53
I'm not sure I'm seeing the same issue as you, but I did need to change the sort order fields of the canvases so the text would render over the video.

**Comment by paatz04** [comment] 2019-07-10 22:41
The sort order of all text components is correct - and didn't need to be changed after migrating from VideoPlayer to AV. (why would they change)

The TextMeshPro UGUI fonts even change when the video is currently not rendered - it just has to be loaded. 

If mp4 not loaded: -> Font renders fine
If mp4 loaded and not rendering/playing -> Font renders incorrectly
If mp4 loaded and rendering -> Font renders correctly

<img width="653" alt="Screen Shot 2019-07-10 at 11 31 32 PM" src="https://user-images.githubusercontent.com/8363908/61009861-44871180-a3c8-11e9-953a-6581782e8e1e.png">

**Comment by paatz04** [comment] 2019-07-11 00:25
It only happens with white font.

<img width="853" alt="Screen Shot 2019-07-11 at 12 16 26 PM" src="https://user-images.githubusercontent.com/8363908/61013477-e0b81500-a3d6-11e9-831c-a5d5a5be4fea.png">
<img width="1417" alt="Screen Shot 2019-07-11 at 12 16 11 PM" src="https://user-images.githubusercontent.com/8363908/61013478-e0b81500-a3d6-11e9-8a3a-9cb55dcb541f.png">

**Comment by paatz04** [comment] 2019-07-11 01:09
A combination of changing the TextmeshPro material to Mobile/default shared and asigning a new material to the DisplayUGUI worked. I will do more testing now

**Comment by MorrisRH** [comment] 2019-07-11 09:02
Thanks for the extra information. I'm having trouble replicating your setup though, would it be possible for you to send a sample project to unitysupport@renderheads.com ?

The iOS issue is because Use YpCbCr420 is checked in the iOS specific media player settings. Our shaders are setup to use this format but the default ui shader is not. Uncheck it and things should work correctly for you (although at a cost of approx. twice the memory usage).

**Comment by paatz04** [comment] 2019-07-11 09:21
Yes - I will do.

Just changing the shader for my TMPro font to Mobile worked and renders fine now on Mac. Can I use one of your shaders instead and keep using YpCbCr420?
thanks

**Comment by MorrisRH** [comment] 2019-07-11 10:03
Yes, attach the shader “AVProVideo/Unlit/Opaque (texture+color+fog+stereo support) to your custom material on the “Display UGUI” component.

**Comment by paatz04** [comment] 2019-07-12 06:27
Thanks this works. 
I'm sometimes seeing weird artefacts on the video ( maybe around the watermark ?) on iOS - where specific areas are coloured differently or just general rendering problems - is it fair to assume that these issues won't happen after buying a license and getting rid of the watermark ?

Cheers!

**Comment by MorrisRH** [comment] 2019-07-12 08:14
Yes, that's an issue with watermarking on iOS. The full product does not have this problem.

**Comment by paatz04** [comment] 2019-07-16 00:01
Hi Morris - thanks a lot for your responses - we have it 100% working and setup now - the only worry is that at some point we will need to use METAL instead of OpenGL Core - Do you happen to have a very rough ETA of when you might be able to fix the rendering issues ?

**Comment by AndrewRH** [comment] 2019-07-17 10:36
The rendering issue is not present in the full package, it is caused by the watermark rendering and only appears on certain models of Mac's, and only when using the Metal graphics API.

**Comment by paatz04** [comment] 2019-07-17 15:09
Sorry just to confirm - this refers to the issue that the whole cutscene is not properly playing on mac+metal, orignally/previsouly asked? 

Not to the weird artefacts happening around the watermark (mentioned 2 comments above) ?

Aka, I can go to prod with mac and metal - with the full package. ? 
Cheers!

**Comment by MorrisRH** [comment] 2019-07-17 16:04
I can confirm that on both macOS and iOS, Metal works correctly with the full version of the plugin.

**Comment by paatz04** [comment] 2019-07-21 09:48
Thank you. I have bought the plugin and everything seems to work as intended.
I can safely disregard this warning from your manual now then: 
"* Recommend using OpenGL Core instead of Metal on macOS as we have had reports of rendering issues with some GPUs"

**Closed** 2019-07-22 09:44 UTC
Labels: bug, macOS
