### ISSUE TITLE
[Android] Exoplayer API: Unable to stream video with HTTP header data

### ISSUE THREAD

**Issue by AndrewSpalato-FGMNT** [RenderHeads/UnityPlugin-AVProVideo#1162] opened 2022-04-26 06:44 UTC
Media player throws generic error when attempting to load a streaming mp4 file from a server that requires HTTP header data using Exoplayer API.

 - Unity version: 2020.3.30f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.4.1 (Trial)
 - Operating system version: Android
 - Device model: Samsung Galaxy S9+
 - Video specs (resolution, frame-rate, codec, file size): Using a custom video at 4096x2048 px resolution.

1. Create a media player component set to ExoPlayer API for Android
2. Add URL to media player that is hosted on a secure server
3. Add HTTP Headers to enable secure playback. 
4. Build apk and launch on device, attempt to load media player. 

Expected outcome: Video should load and first frame should be visible.
Actual outcome: Generic error thrown specifically for ExoPlayer API for Android.

I have attempted to reimport the plugin just in case I missed something.

When attempting to load, the app logs the attempted opening of the media from URL

This issue does **not** occur if using the supplied URL in the user manual: https://rh-testmedia.s3-eu-west-
1.amazonaws.com/Samples/BigBuckBunny-360p30-H264.mp4

The issue also does **not** occur if using the Android MediaPlayer API instead of ExoPlayer API.

Logs:
`04-26 16:38:16.124  7136  8745 E Unity   : [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
04-26 16:38:16.124  7136  8745 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
04-26 16:38:16.124  7136  8745 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
04-26 16:38:16.124  7136  8745 E Unity   :`

**Comment by Chris-RH** [comment] 2022-04-26 08:35
Hi @AndrewSpalato-FGMNT. The resolution of the Samsung Galaxy s9+ is 2,960x1,440, so you video resolution is just too high.

**Comment by kahnivore** [comment] 2022-04-26 09:44
Could you please share a full log file?

**Comment by AndrewSpalato-FGMNT** [comment] 2022-04-27 00:33
I turns out I am able to stream 4096x2048 or 4K UHD video using ExoPlayer if not streaming from a secure server that requires HTTP header data. 

Does ExoPlayer support video/audio streaming in combination with HTTP Header data?

**Comment by RenderHeadsSte** [comment] 2022-04-27 10:32
Ahh, right, oki, not a video resolution issue.

The MediPlayer API path does not support HTTP headers in any way...so that hints at incorrect server setup if you are seeing it playback using that API path.

Are you able to send us the video url and header details so we can investigate here?  If you do not wish to make them public you can send them to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Github%20Issue%20#1162)

**Comment by AndrewSpalato-FGMNT** [comment] 2022-04-28 00:22
@RenderHeadsSte Thank you, have sent an email to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Github%20Issue%20%231162)

**Comment by Remon8399** [comment] 2022-04-28 09:18
Hi @RenderHeadsSte 
I do have similar issue with android exoplayer api, I do follow the instruction from document by modify androidmanifest with android:usesCleartextTraffic="true", when start to play the scene for first time it does load the video and can play it, but when you reload the same url it come with error and the video preview just blank, and making others mediaplayer component in hierachy not working properly.

There are no logic error from myside, you can simple open blank project and import the avpro plugin, and put http video link, do create a button on scene (this button will just simple do OpenMedia(same url)) when you click it, you will notice the mediaplayer component just break, together with all mediaplayer that had in hierachy. (internet access required, android:usesCleartextTraffic="true").

Do be aware this error won't show in unity editor even you switch to android in build setting, this error only appear on build apk on android phone.

No issue with desktop version and ios version. Android version with https also working fine, but with http and setup android:usesCleartextTraffic="true" will trigger the issue.

**Comment by RenderHeadsSte** [comment] 2022-04-28 09:53
@AndrewSpalato-FGMNT I see what the issue is here.  ExoPlayer treats user-agents separately from headers.  It looks like WinRT bundles it all in together.  Will need to have a chat internally on how we go about support for this and get back to you.  The good news is I have made it work here with a small code change to the plugin.

@Remon8399 Can you please create a separate issue for your problem rather than piggy-back this one. Thanks!

**Comment by RenderHeadsSte** [comment] 2022-04-28 16:03
@AndrewSpalato-FGMNT We have concluded that an Android specific plugin fix is the right approach to address this issue.  The fix will be in the next AVPro Video release - which is likely to be next week.

**Comment by RenderHeadsSte** [comment] 2022-05-05 18:29
@AndrewSpalato-FGMNT we have published a new build with the fix in.  Please do let us know if this addresses the issue.

**Comment by AndrewSpalato-FGMNT** [comment] 2022-05-06 01:50
@RenderHeadsSte Thank you very much! Streaming with HTTP Header data with User-Agent using ExoPlayer works on our end too.

**Closed** 2022-05-06 07:04 UTC
Labels: Bug 🐛, Android, Fixed
