### ISSUE TITLE
AvProVideo v3, in android, 2 mp4s can't be played at the same time.

### ISSUE THREAD

**Issue by HyundongHwang** [RenderHeads/UnityPlugin-AVProVideo#2026] opened 2024-10-10 07:09 UTC
**Describe the issue**
Hello.
In AvProVideo v3, in android, 2 mp4s can't be played at the same time.
This issue doesn't occur on ios, macOS.

**Your Setup**
- unity : 2022.3.37f1
- AvProVideo : 3.0.11
- os : android 14
- device model : samsung galaxy s22 ultra, SM-S908N
- video : mp4(h264+aac), 30fps

**To Reproduce**
1. btnLoad
- Load v0.mp4, v1.mp4 to 2 MediaPlayers _mp0, _mp1 at the same time.
2. btnPlay01
- Play _mp0, _mp1 at the same time.
3. You can see that only _mp1 is played.
4. After that, if you stop and do btnPlay01 again, you can see that only _mp0 is played.

**ScreenShot**

[ScreenShot](https://github.com/user-attachments/assets/776482d1-4d40-437e-a75b-25c4c6ad9a09)

**Comment by Chris-RH** [comment] 2024-10-10 08:28
Hi, 

Please don't post links to project files or apk here.  Please can you delete them from your github.
Can you instead send them to unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2024-10-10 09:23
Hi, 

We've reproduced the bug and think that we know the cause.

**Comment by Ste-RH** [comment] 2024-10-10 09:24
I believe this is an issue caused by the fix for issue #1967 in v3.0.9

We will have to revert that fix in order to address this one, then find another way to address that issue.  It might actually be an issue with media3/ExoPlayer - I have opened an [issue](https://github.com/androidx/media/issues/1798) with them to question it

**Comment by HyundongHwang** [comment] 2024-10-10 09:41
Yes, that's right.

It works fine in v3.0.8.


![v](https://github.com/user-attachments/assets/bc73c6b3-b81a-4e0a-b50a-7465b7381912)

**Comment by Ste-RH** [comment] 2024-10-10 13:50
This should be fixed in the next release.

#1967 should also remain fixed (albeit with a different fix applied)

**Comment by Ste-RH** [comment] 2024-10-18 16:05
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.

**Closed** 2024-10-25 08:32 UTC
Labels: Bug 🐛, Android, Fixed, Version 3.x
