### ISSUE TITLE
Changing output devices (with different sample rates) can cause audio playback rate to change.

### ISSUE THREAD

**Issue by Crambror** [RenderHeads/UnityPlugin-AVProVideo#1317] opened 2022-10-04 14:56 UTC
**Describe the issue**
When playing audio files using MediaPlayer if we change output device the rate of playback can change. This appears to be to do with the 2 output devices we're using having different sample rates. It's like Unity's output sample rate is only taken into account when the MediaPlayer is created and is not checked and if necessary changed when Unity notifies of an output device change. We are using the audio via Unity method of playback along with the AudioOutput component.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.5.6
 - Operating system version: Mac
 - Device model: Mac M1 Max
 - Video specs (resolution, frame-rate, codec, file size): any mp3/wav

**To Reproduce**
1. On a Mac create a new project
2. Create a simple MediaPlayer using the audio output via Unity method, add an AudioOutput component to handle audio
3. Add a simple audio file such as mp3/wav, speech is easiest to identify problem
4. Play the project in the editor
5. While audio is playing change audio output device between 2 devices supporting different max sample rates, do this during audio playback. In my case I'm switching between Sony WH-1000XM4 headphones (44.1kHZ) and Apple AirPods (48kHZ) both connected via bluetooth.
6. You should notice that after switching audio playback slows down or speeds up.
7. This can be replicated within the Unity Editor, standalone build is not needed.
8. Stopping and running the level again will fix the issue until device is switched again.

Notes:
If you want to check the sample rate of your audio devices you can tap into the AudioSettings.OnAudioConfigurationChanged event and log the AudioSettings.outputSampleRate. Then when you switch audio device you should see the sample rate of each device. They need to differ for this bug to be heard.

**Comment by MorrisRH** [comment] 2022-10-05 08:00
You are correct, we only set the output sample rate at player creation. I expect this happens for all platforms.
We'll investigate and see what can be done.

**Comment by MorrisRH** [comment] 2022-10-11 14:19
I'm unable to reproduce this. Every time I switch between two devices with different sample rates I get:

**Comment by Crambror** [comment] 2022-10-13 08:11
Hmm ok, I do get that message but our audio continues, although it may be that the currently playing audio wav stops, but we definitely get further playback. Our app plays a series of speech wavs, and the future wavs show the problem, those wavs reuse the existing MediaPlayer.

**Comment by Crambror** [comment] 2022-10-25 11:10
Ok I've done some more work on my audio test project and have some slightly improved repo steps. You are correct that sometimes the device change causes the audio to stop, but on the next play the audio resumes, also sometimes the audio continues despite the change.

I have a test project now that plays a short video with speech, waits for it to finish, then starts it again. This makes it easier to reproduce the problem. What I have noticed is when switching between my mac audio at 48000 and my headphones at 44100 is that the AudioOutput component does not change sample rate and remains at whatever was set when the media player was created.

By starting the app on my mac at 48000 and then switching to my headphones at 44100 the audio continues to play at a lower pitch, returns to normal when I switch back to my mac. Sometimes the change causes the audio to stop, but it picks up again when the video starts again.

Let me know if you want me to send you my test project which I'm happy to do.

**Comment by MorrisRH** [comment] 2022-11-14 11:05
If you can share a project showing the issue that would be great. Please send it (or a link to it) to unitysupport@renderheads.com using this issue as the emails subject.

**Comment by MorrisRH** [comment] 2022-12-05 16:24
Thanks for sending through the project. I've been able to reproduce this well enough to implement a fix which will make it into the next release.

**Comment by MorrisRH** [comment] 2022-12-08 15:04
Hey @Crambror, version 2.6.7 has just been released with a fix for this.

**Closed by MorrisRH** 2022-12-08 15:04 UTC
Labels: macOS, Fixed

**Comment by quwanli** [comment] 2025-02-12 08:30
Video stream playback using OpenMediaFromBuffer on Windows platform crashes: EXCEPTION_STACK_BUFFER_OVERRUN / FAST_FAIL_FATAL_APP_EXIT / 0x7ffb5043502e: Fatal Error: EXCEPTION_STACK_BUFFER_OVERRUN / FAST_FAIL_FATAL_APP_EXIT / 0x7ffb5043502e
Why?
