### ISSUE TITLE
GetDuration and GetDurationFrames return 0 on macOS

### ISSUE THREAD

**Issue by jukka-at-fake** [RenderHeads/UnityPlugin-AVProVideo#586] opened 2021-01-22 12:04 UTC
**Describe the bug**
MediaPlayer.Info.GetDuration() and MediaPlayer.Info.GetDurationFrames() return 0 on macOS.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.0.1
 - Operating system version:  Catalina (v10.15.7)
 - Device model: MacBookPro 16-inch (AMD Radeon Pro 5500M & Intel UHD Graphics 630)
 - Video specs (resolution, frame-rate, codec, file size): 720x1280, H.264, 20.7 MB

  **To Reproduce**
  1.  Use `MediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, (link below), false);`
  2.  Start video playback and yield until first frame is ready.
  3.  Try to read `MediaPlayer.Info.GetDurationFrames()` or `MediaPlayer.Info.GetDuration()`

Results 
- Windows & Oculus Quest: correct duration reported
- macOS: 0 for both 

**Videos**
[link](https://glue-public-static-resources.s3.eu-west-1.amazonaws.com/team%3A0nfwkhf599ae4n8s/72b6e893-38e4-4ef8-9d3a-b72c6d811cf1/VID_20201221_161325.mp4)

**Comment by MorrisRH** [comment] 2021-01-22 12:28
Cannot reproduce this, both GetDuration and GetDurationFrames are returning correct values when the ReadyToPlay or Started events are triggered.

There is an issue with the FirstFrameReady event not being triggered in version 2.0.1 (fixed in version 2.0.2), however ReadyToPlay or Started will have fired already.

**Comment by psy-ankka** [comment] 2021-01-22 18:54
Thank you for the quick response! The FirstFrameReady issue appears the be the root cause in our case. Any timeline for the v2.0.2?

**Comment by RenderHeadsSte** [comment] 2021-01-22 19:33
> Thank you for the quick response! The FirstFrameReady issue appears the be the root cause in our case. Any timeline for the v2.0.2?

The release is in progress now. So it will hopefully be live within hours.

**Comment by AndrewRH** [comment] 2021-01-22 23:31
@psy-ankka 2.0.2 is available now - do let us know if this solves this issue.

**Closed** 2021-02-04 09:50 UTC
Labels: CNR 🤷, Fixed, Version 2.x, macOS
