### ISSUE TITLE
Crash when a MediaPlayer instance is active and using UIImagePickerView

### ISSUE THREAD

**Issue by cyliax** [RenderHeads/UnityPlugin-AVProVideo#922] opened 2021-09-06 14:37 UTC
Issue:
We use AVPro to show some videos in our App. And we use Stans Assets iOS Native Pro / Android Native Pro to capture videos with a native iOS camera overlay. I tried to replace "Stans Assets" with "Native Camera for Android & iOS" and both doing a great job, as long es there is no AVPro in the project:

The native camera is opening and I can see my camera image. But when I press record, the app crashes in 9 of 10 attempts. Sometimes it works but I couldn't find out why. Everything runs fine on Android with both plugins and capturing an image instead of a video is no problem as well (no audio ?)

I think there might be an issue when accessing audio resources, I had BAD ACCESS' logs when pressing the record button. I tried all the possible AVPro settings: Unity audio, closing video before opening import screen and so on but nothing works. 

Setup:
 - 2019.4.29 - 2020.3.16f1
 - 2.1.8
 - iOS 13 - 14 (current)
 - Device model: iPhone 11 Max Pro, iPhone 12 Mini, iPad 2018
 - Your big buck bunny example video: BigBuckBunny-360p30-H264.mp4

Reproduce:
1. Open a new project and prepare it to work within iOS
2. Add an UI button to call native camera import methods in "Stans Assets iOS Native Pro" or "Native Camera for Android & iOS"
3. Run the app and try to capure a video... works
4. Add an AVPro MediaPlayer to your root, show an example mp4 video on a DisplayUGUI object
5. Export again and try to record a video... crashes more than it runs

I can provide you a sample project, if it helps you.

Thanks

**Comment by kahnivore** [comment] 2021-09-06 19:20
Hi, yes, a sample project will be helpful. Could you please send it to unitysupport@renderheads.com?

**Comment by cyliax** [comment] 2021-09-07 11:03
Well, I found out, that the issue appears with version 2.1.8, downgraded to 2.1.6 and some others - there is no problem accessing the camera view. start recording and playing videos with avpro. I'll send you a minimized test project.

**Comment by AndrewRH** [comment] 2021-09-10 09:45
I believe a fix for this is being investigated internally

**Comment by MorrisRH** [comment] 2021-09-13 18:46
Thanks for the sample project, we wouldn't have been able to reproduce the issue so quickly otherwise. Results are as follows (all using Unity 2020.3.17f1):
* iPhone 5s, iOS 12.5.4, AVPro Video 2.1.8 - Unable to reproduce
* iPhone X, iOS 14.7.1, AVPro Video 2.1.8 - Unable to reproduce
* iPad Pro (10.5 inch), iOS 14.7.1, AVPro Video 2.1.8 - Crashes every time, the crash is caused by an over deallocation of what looks like the captured videos metadata (guessing based on the memory contents) and is happening in the internals of Apple's camera capture class. Why having a media player instance in the scene causes this is currently beyond me.
* iPad Pro (10.5 inch), iOS 14.7.1, AVPro Video 2.1.6 - No crash

I'll see if I can identify what changed between 2.1.6 and 2.1.8 to cause this.

**Comment by MorrisRH** [comment] 2021-09-14 09:17
This has now been fixed (again, thanks for the sample project) and will be in the next release 2.2.0

**Comment by AndrewRH** [comment] 2021-09-15 11:15
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.

**Closed** 2021-09-17 08:29 UTC
Labels: Bug 🐛, iOS, Fixed, Version 2.x

**Comment by guodan** [comment] 2023-09-07 07:26
> This has now been fixed (again, thanks for the sample project) and will be in the next release 2.2.0

I update to 2.8.5，there is no problem.
