### ISSUE TITLE
Retain last valid video frame whilst buffering up a new video

### ISSUE THREAD

**Issue by VOX-Neil** [RenderHeads/UnityPlugin-AVProVideo#976] opened 2021-10-19 19:54 UTC
**Is your feature request related to a problem? Please describe.**
Apologies if this is already do-able although I can't find a solution.

I am playing a video on a playlist player from an external url and then buffering another to play straight after. Sometimes it's not clear which video will be buffered next and so I'd like to retain the last frame of the previous video whilst the new video is being buffered.  Currently I get a null texture as there isn't a valid texture while the new video is loading and therefore a blank screen which isn't ideal.

**Describe the solution you'd like**
One way I've managed to do this is simply to cache the previous valid texture and use that if HasValidTexture() is null.  I'm also doing the same with _flipY to ensure the correct vertical rotation.
However, I'm not sure if this is the best solution or if it will work in all situations yet.  

Ideally, an option on the playlist player or media player to retain the last frame would be great.

**Comment by kahnivore** [comment] 2021-10-20 10:14
Which platform(s) support are you looking for?

**Comment by Chris-RH** [comment] 2023-07-05 13:26
duplicate of #621

**Closed by Chris-RH** 2023-07-05 13:26 UTC
Labels: duplicate, enhancement 🚀, Version 2.x
