### ISSUE TITLE
can not load when build with android obb on  Android emulator 。 Such as mumu emulator 

### ISSUE THREAD

**Issue by lvchy** [RenderHeads/UnityPlugin-AVProVideo#423] opened 2020-07-20 07:46 UTC
When build with android obb ，on mumu emulator ，it shows 
![image](https://user-images.githubusercontent.com/24428364/87912607-42a66280-caa0-11ea-9704-a4a2d18cca52.png)

**Comment by lvchy** [comment] 2020-07-20 07:47
On mobile it load and show suc

**Comment by lvchy** [comment] 2020-07-20 09:11
Now I also find some old,low memory mobile can not play the video

**Comment by lvchy** [comment] 2020-07-20 09:16
![image](https://user-images.githubusercontent.com/24428364/87921081-ad5d9b00-caac-11ea-90e6-4160efdc0114.png)

some phones

**Comment by lvchy** [comment] 2020-07-20 09:42
And all this android device ,i can play the video with out unity obb patch !

**Comment by lvchy** [comment] 2020-07-20 11:01
these android devices android sdk version is 6.0

**Comment by lvchy** [comment] 2020-07-20 11:10
unity version is 2018.4.21f1 , any help welcome .... thanks very much !!

**Comment by AndrewRH** [comment] 2020-07-22 16:38
How big is your video file?   I believe opening the OBB / JAR containing a very large file uses up a lot of memory.  

Have you considered downloading the video file from the internet instead, and storing it in the PersistentMediaPath folder?

Thanks,

**Comment by lvchy** [comment] 2020-07-23 02:19
![image](https://user-images.githubusercontent.com/24428364/88246590-816d3000-cccd-11ea-999a-9563f0be0422.png)
there is my game video ,every mp4 file size is about 2m-5m .
And this error only happen on android 6.0 and emulator diveces, and only with obb patch . other phone not happen .

If I build without obb , all these android 6.0 phones and emulator devices can play video success.

Is there some difference between android 6.0 on obb loader ??


Thanks a lot ~~

**Comment by lvchy** [comment] 2020-07-23 02:31
All my file now is in streaming folder .

**Comment by lvchy** [comment] 2020-07-23 02:34
BTW,I don not think the file size is cause this error . Because I have lots of unity assetbundle file in streaming folder , the size is much bigger than the mp4 file ,but can be loaded success

**Comment by lvchy** [comment] 2020-07-23 02:43
Is there some differences on load obb file in your android jar loader ?
![image](https://user-images.githubusercontent.com/24428364/88247721-597fcb80-ccd1-11ea-9384-10aae62ca91d.png)

Some difference in android version can cause load file fail .

**Comment by RenderHeadsSte** [comment] 2020-07-24 16:27
I have done some testing on an Android 6.0.1 device, and the same build on an Android 7.0.0 device.  There is indeed a difference.  The device with 6.x does play back the video, but I observed the following things:

- It takes a while for the video to start.
- Playback appears to freeze at seemingly random points in playback, then continue eventually.
- Reducing the size of the OBB has a huge effect on the delays, with OBBs of a larger sizes refusing to playback at all (could be I just did not wait long enough ~5 minutes).
- I tested this in AVPro Video v1.x and v2.0.0beta2 and the results were the same.

I can only assume this is a bug in Android v6.0.0/6.0.1/etc.  We cannot offer a fix for this as it is in the Android APIs which we have no influence over.

**Comment by RenderHeadsSte** [comment] 2020-07-24 16:37
I reproduced this bug on an Android 6.0.1 device, and the same APK was fine on an Android 7.0.0 device.  All testing suggested that the issue due to something in the Android API layer, which would mean we could not offer a fix.  However, I tested a build switching to using the MediaPlayer API Path and the issue does not present itself.  I was really not expecting this.

So...can you try switching the API Path to MediaPlayer and report back please?

**Comment by lvchy** [comment] 2020-07-27 06:04
@RenderHeadsSte  ,thanks a lot ~ 
So , which MediaPlayer API Path should i use ? 
RelativeToPersistentDataFolder ??

**Comment by lvchy** [comment] 2020-07-27 12:16
@RenderHeadsSte  RelativeToPersistentDataFolder with obb patch can work ,but ,but ,it's very vert slow ,a black screen on my game shows about 5 secods until video is ready to play.With out obb patch can work well

**Comment by RenderHeadsSte** [comment] 2020-07-29 14:15
No, you are referring to the 'Source Path'.  This is the setting you are looking for:

![image](https://user-images.githubusercontent.com/46531149/88811326-504d9d80-d1ae-11ea-822c-d074c7ab9f4e.png)

**Comment by lvchy** [comment] 2020-08-03 12:09
OK ,I will try it,but what diffenence between these two api ?

**Comment by RenderHeadsSte** [comment] 2020-08-04 15:13
MediaPlayer is the core Android SDK, ExoPlayer is built on and around it and has a lot more features.

Are you able to report tat using the MediaPlayer API fixed the problem you are seeing?

**Comment by lvchy** [comment] 2020-08-13 08:56
I will report after using the MediaPlayer API these days,thanks a lot~

**Comment by RenderHeadsSte** [comment] 2020-09-02 10:30
> I will report after using the MediaPlayer API these days,thanks a lot~

Anything to report?

**Comment by lvchy** [comment] 2020-10-21 07:17
Unfortunately , it not worked . 
I have no idea now .
I can only use the old setting .

**Comment by lvchy** [comment] 2020-10-21 07:46
I use the same setting ,and the same api to play video .some shows correctly ,some shows a black screen , there is the  log window log . 
![Uploading image.png…]()

**Comment by RenderHeadsSte** [comment] 2021-01-25 22:50
Closing due to inactivity

**Closed by RenderHeadsSte** 2021-01-25 22:50 UTC
Labels: Android, Bug 🐛
