### ISSUE TITLE
Unity 2019+ directshow & media foundation rendering difference?

### ISSUE THREAD

**Issue by tufeixp** [RenderHeads/UnityPlugin-AVProVideo#286] opened 2020-03-09 07:16 UTC
I suffered with many issues related to DirectShow and media foundation on windows 10:
1, The media foundation always plays videos much brighter than DirectShow, which is unacceptable in most cases, however, for some very dark video: eg.
![colorClipping](https://user-images.githubusercontent.com/11953709/76190208-7088ba00-6217-11ea-8e6d-176ddd6ce9ec.JPG)
using DirectShow can lead to contrast clipping contour in the dark.
2, Using DirectShow plays HD streaming frame by frame, no sound at all, turning Resampler on makes no difference, however media foundation plays much smoother. eg. http://ivi.bupt.edu.cn/hls/cctv6hd.m3u8 .The codec is LAV Filter from Klite full codec pack.

1Frame Sample Video added:
[DarkClipping.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4316034/DarkClipping.zip)

**Comment by AndrewRH** [comment] 2020-03-09 12:40
Hi,

Thanks for reporting this issue.  I think this may be related to this issue:
#122

It seems as though it's caused by using the Linear colour space and DirectShow.  So for now you could change to Gamma colour space.  It seems to be due to some change in behaviour from Unity 2019..  We are still investigating this.

Please let me know:
1) Unity version
2) GPU

Thanks,

**Comment by tufeixp** [comment] 2020-03-09 15:13
1. Unity Version: 2019.3.3f1
2. GPU: Nvidia GTX 1050
I have to use DirectDraw other than Media Foundation because of the stereo Meta data issue, besides, I can not afford to switch to gamma color space, because I have 3d models designed in linear color space to render, and this can not be switched at runtime. Thus No workaround for me.

**Comment by AndrewRH** [comment] 2020-03-09 16:54
Thanks for the extra examples....we're taking a look...

**Comment by tufeixp** [comment] 2020-03-09 17:29
I also tried to switch the video api to Media Foundation if the input is m3u8, however, the playback remains jaggy. :<
`                if(_mediaPlayer.m_VideoPath.EndsWith("m3u8"))   //force use media foundation, but still too bright under linear color space
                {
                    _mediaPlayer.PlatformOptionsWindows.videoApi = Windows.VideoApi.MediaFoundation;
                }
                else
                {
                    _mediaPlayer.PlatformOptionsWindows.videoApi = Windows.VideoApi.DirectShow;
                }`

**Comment by AndrewRH** [comment] 2020-03-09 17:56
Hmm how are you displaying the video to screen?
eg, Are you using the DisplayIMGUI component?

**Comment by tufeixp** [comment] 2020-03-10 10:29
No, I use ApplyToMesh method, and have also bypassed the gamma adjust code implemented in AVProVideo.cginc. By adding the gamma auto-correction code, MediaFoundation output looks much better now, while Direct Draw output looks still a little bit pinkish and need some saturation adjustments.
For the DisplayIMGUI demo with Media Foundation backend, I have to change this line:
                if (QualitySettings.activeColorSpace == ColorSpace.Linear && !_mediaPlayer.Info.PlayerSupportsLinearColorSpace())
and change gamma correction to 1.2 other than 2.2 to make it look right on screen. I guess unity has some extra gamma conversion for the UI.

For now I just need to switch between the two VideoApi at runtime, in order to get around the m3u8 playing issue.

**Comment by AndrewRH** [comment] 2020-03-11 12:54
Oooh hmm...wait, so you were using your own shader/material?
If so - then that's why I wasn't able to replicate it on our side... Our plugin requires use of our shaders as we have to compensate for platform / video API differences in the shaders sometimes...

Perhaps you could send me a short video clip (mp4) that demonstrates the pink/saturation colour issue on DirectShow when it is played back?  Then we can investigate this further.

Otherwise are you happy to close this issue now?   I will actually leave it open until we have fixed the IMGUI issue at least...

**Comment by tufeixp** [comment] 2020-03-11 18:17
I have added the DarkClipping.zip to the first post, please check it on your demo project. I tried with post gamma and contrast adjustments, none can fix that.
Hope you can check the pinkish flv streaming too, 'cause I have no idea why it's different comparing to MPC player, while both are using the same LAV filter.

**Comment by AndrewRH** [comment] 2020-03-11 19:47
Thanks for the dark video - I have replicated the posterize effect.....we're looking into it

As for the FLV pink - do you have a sample video? :)

**Comment by tufeixp** [comment] 2020-03-12 04:06
Uploaded:
[pinkishDirectDraw.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4322210/pinkishDirectDraw.zip)

**Comment by tufeixp** [comment] 2020-03-12 04:29
This screenshot was from the 01_Demo_BackgroundShader.scene, setting the draw api to directDraw.
![compare2](https://user-images.githubusercontent.com/11953709/76487093-3b20de00-645c-11ea-978a-89f38c627ab0.PNG)
I found that it has nothing to do with the input formats, but all contents drawn by directDraw to the mesh using linear color space looks the same pinkish/redish tone.

**Comment by AndrewRH** [comment] 2020-03-12 17:27
Thanks very much for this.

We have looked into the issue with DirectShow contrast/clipping that you first mentioned and have resolved this.  We will include the fix for this in the next version of the plugin.

I will test the pink issue and get back to you.  Thanks,

**Comment by AndrewRH** [comment] 2020-03-13 16:56
Ok the pink issue has been solved.  It was a bug in our 10-bit shader conversion code.  I'm not sure why it decided to pick the 10-bit path for that video....  The fix will be included in the next release of the plugin.
For now you can run LAV Video Configuration and disable the P010 output format:
![image](https://user-images.githubusercontent.com/5418126/76642649-87971700-654b-11ea-9c6e-23b2413ab21b.png)

Is there anything else or can I close this ticket now?

**Comment by tufeixp** [comment] 2020-03-13 21:58
After tick the P010 off, the video becomes Y flipped.
Please take a look at the m3u8 with DirectShow issue too.

**Comment by AndrewRH** [comment] 2020-03-15 01:19
> After tick the P010 off, the video becomes Y flipped.
> Please take a look at the m3u8 with DirectShow issue too.

Wow Y flipped??? I don't get that... Okay I will investigate further.
I will check the M3U8 issue.  I did do some initial tests and didn't have any problem. 

Which version of LAV Filters are you using? 0.74.1 is the version I have installed
https://github.com/Nevcairiel/LAVFilters/releases

**Comment by tufeixp** [comment] 2020-03-15 01:54
0.74.1.32-git

**Comment by AndrewRH** [comment] 2020-03-19 23:30
@tufeixp 
FYI we will soon be releasing the new version of the plugin, which should fix the incorrect colour issues you were having.

**Comment by AndrewRH** [comment] 2020-03-20 12:46
@tufeixp just so you know, i've split off the M3U8 DirectShow issue into another issue #299 so that this ticket can focus on the rendering issues and can be closed soon once 1.10.2 is out.  Thanks,

**Closed** 2020-03-20 14:57 UTC
Labels: Bug, Windows
