### ISSUE TITLE
Reliable Frame Seek/Step

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#702] opened 2021-03-29 17:41 UTC
Depending on the codec and DirectShow vs MediaFoundation, sometimes the specific frame seek does not work accurately.  HAP seems to work flawlessly with DirectShow.  Anything with MediaFoundation seems to behave poorly.

Unity: 2019.4.22f1
OS: Windows
AVPro Video: 2.0.10

There is a bunch of code in FrameExtract that seems to wait and poll for the correct frame.  Is there a recommended way for seeking accurately in general?

Also, if we're only moving forward, would like to know the most accurate way to step forward from frame to frame.  There is: 

```
		/// <summary>
		/// The time in seconds seeked will be to the exact time
		/// This can take a long time is the keyframes are far apart
		/// Some platforms don't support this and instead seek to the closest keyframe
		/// </summary>
		void	Seek(double time);
```

If this can take a long time, how do we know when it has reached the desired frame?

```
		/// <summary>
		/// Seek forwards or backwards relative to the current frame
		/// NOTE: For best results the video should be encoded as keyframes only
		/// and have no audio track, or an audio track with the same length as the video track
		/// </summary>
		void	SeekToFrameRelative(int frameOffset, float overrideFrameRate = 0f);
```

Is this the best way to step through a video reliably?

**Comment by kahnivore** [comment] 2021-04-01 16:16
Hi @v2k 

When you say that frame seek doesn't work properly, can you provide more detail of what happens? What is the offset? 

The best way to deal with this is to have a video with keyframes only - all i-frames. 

SeekToFrame would be most accurate. To test that seeking is finished you could subscribe to the seeking event, or you could call IsSeeking to check if it's still seeking or not.

**Comment by v2k** [comment] 2021-04-01 17:54
The most common issue was say Seek(10) would end up at frame 149 or 150 for example.  It wasn't guaranteed to end up at the same (and correct frame) each time.

So the two issues:

1. reliably seeking to a given frame
2. walking a video frame by frame

1: the seek request has a timeout associated with the request, so it's not 100% to end on the requested frame.

2: was looking for a reliable way to step frame by frame through a video.  currently, I'm using SeekToFrameRelative(1) to step frames.  checking GetTextureFrameCount() to see if it's increased.  this seems to be working fairly well, still testing.

originally using Seek(time) by adding fps * dt to time - this didn't seem to always arrive at the correct frame.  it could be off by a frame or two.

I have not tried waiting for the Seek events, that's good to know.  Probably better than polling GetTextureFrameCount().

**Comment by cihadturhan** [comment] 2021-04-05 16:09
Hello, 

On iOS and MacOS, I have this issue and unfortunately it makes my project unusable at the moment.
Although it says seeking is ended, it shows the wrong keyframe. 
Please use the same implementation in V1. It was doing perfect.

Here is a comparison V1 and v2
https://user-images.githubusercontent.com/3739536/113595128-420b2780-9641-11eb-8a05-d707e8c34a81.mp4

Explanation: 
I use `mediaPlayer.Control.Seek()` and check if `mediaPlayer.Control.IsSeeking()` becomes false.
If seeking is ended, I record the camera texture to mp4 file.

This is the test file if you want to test by yourself.
https://user-images.githubusercontent.com/3739536/113596010-67e4fc00-9642-11eb-8fa4-7ad94d0a0e3d.mov

**Comment by MorrisRH** [comment] 2021-04-08 17:00
@cihadturhan I'm unable to reproduce this, I was able to step through the video you provided perfectly using SeekToFrameRelative(1)

**Comment by cihadturhan** [comment] 2021-04-11 22:29
@MorrisRH This is probably a bit difficult to reproduce but I'll try to provide a demo project.
Please don't close the issue until then.

**Comment by RenderHeadsSte** [comment] 2021-04-29 16:03
Any luck on a demo project @cihadturhan?  If so, please send it over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) marking the subject as 'Issue #702'.

**Comment by cihadturhan** [comment] 2021-05-06 09:57
@RenderHeadsSte unfortunately I'm still busy with current projects so I couldn't have time for a repro.
Feel free to close this. 
I can open a new issue or request to re-open this issue when I have time.

**Closed** 2021-05-09 14:18 UTC
Labels: Version 2.x, Windows, iOS, macOS
