### ISSUE TITLE
doesn‘t work in windows 7 

### ISSUE THREAD

**Issue by Severn17** [RenderHeads/UnityPlugin-AVProVideo#725] opened 2021-04-15 06:01 UTC
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: Unity 2018.4.22f1
 - AVPro Video version:  ltest downloaded just now from your website
 - Operating system version: windows 7 professional 6.1 Internal version 7601
 - Device model: windows 7 x86
 - Video specs (resolution, frame-rate, codec, file size): 1024*768

**To Reproduce**
1. Import AvPro
2. unity build x86 Application package

**Logs**
![image](https://user-images.githubusercontent.com/26053673/114821406-17646000-9df3-11eb-8d55-b65c369b79df.png)

![image](https://user-images.githubusercontent.com/26053673/114821363-09aeda80-9df3-11eb-9fa1-1806db39501a.png)

If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Severn17** [comment] 2021-04-15 06:09
In the same package, I was prompted to stop working when I opened the application with Windows 7 x86, but opened successfully with Windows 10 x86_64

**Comment by kahnivore** [comment] 2021-04-16 09:43
Hi @Severn17 

Do our demo scenes work on your Windows 7 machine?

**Comment by Severn17** [comment] 2021-04-16 10:12
yes，I'm using the demo scenes on Windows 7 machine

**Comment by kahnivore** [comment] 2021-04-16 10:34
Could you provide some more details about what the problem is? 
Do the videos play in the editor? 
What happens when you open the build? 

Thanks

**Comment by Severn17** [comment] 2021-04-16 10:37
The second picture is the message when I open the application, and then the application doesn't respond

**Comment by kahnivore** [comment] 2021-04-16 12:30
Would it be possible to get a log file of the crash? 

Thanks.

**Comment by Severn17** [comment] 2021-04-20 07:28
Where are the files you need to log the crash

**Comment by kahnivore** [comment] 2021-04-29 14:46
Please see [this link](https://docs.unity3d.com/Manual/LogFiles.html) in the Unity docs for a description of how to get the log files.

Thanks!

**Comment by kahnivore** [comment] 2021-05-20 14:15
Hi @Severn17 

Sorry this took so long, needed to get a hold of a machine to install Windows 7 on. 

We've tested builds of all the demo scenes on Windows 7 Professional with the latest version of AVPro Video on the latest Unity 2018 LTS and they all work fine. On the machine we were using the video is quite choppy with the graphics quality high, but play smoothly on low. 

Can you confirm you are still having this problem? 

Thanks

**Comment by Severn17** [comment] 2021-06-07 09:56
I'm very sorry that the test machine on my side has been taken back. Now this problem cannot be repeated.Thank you very much for your efforts

**Comment by AndrewRH** [comment] 2021-07-23 16:44
I believe this issue may be related to #873 which should be fixed in the next release (2.1.7)

@Severn17 if your Windows 7 machine has an old GPU then it could be the same issue...

Thanks,

**Comment by AndrewRH** [comment] 2021-07-27 15:02
@Severn17  we have just released version 2.1.8 which includes a fix for Windows 7 support.

We had a number of users reporting Windows 7 issues and have fixed some problems with it.

Please let us know if the resolves the issue for you.

Thanks,

**Comment by AndrewRH** [comment] 2021-07-28 09:04
@Severn17  version 2.1.8 is available now

**Comment by AndrewRH** [comment] 2021-08-03 16:14
I am closing this issue as we have not heard back and believe that the issue has been resolved with the 2.1.8 version.

Thanks,

**Closed by AndrewRH** 2021-08-03 16:14 UTC
Labels: Bug 🐛, Fixed, Version 2.x, Windows
