### ISSUE TITLE
TextureProducer returns a black texture in ExoPlayer

### ISSUE THREAD

**Issue by AntonioStissi** [RenderHeads/UnityPlugin-AVProVideo#47] opened 2019-04-15 09:17 UTC
**Bug description**
I need to switch my 360 videos without having black frames in the middle, to do so I am saving a texture from the TextureProducer and showing it on a mesh during the time the new video is loading. It works quite well in the Unity Edito, on iOS (VR Cardboard mode) and it works on Android using Media Player but **it does not work using ExoPlayer on Oculus Go (Android 7.1.2)**. **Using ExoPlayer the shown texture is black** (but not null).

**My setup:**
 - Unity version: 2017.4.24f1
 - AVPro Video version: 1.9.12
 - Operating system version: Android 7.1.2 (Oculus Go)
 - Device model: Oculus Go
 - Video specs (resolution, frame-rate, codec, file size): 
resolution: 3840x1922
frame-rate: 29.970030
codec: H264 - MPEG-4 AVC
file size: it happens with several files having size ranging from 5 to 25MB.

**To Reproduce**
1.  Load a 360 video and show it on a sphere (VR mode)

2. Run the following code to switch to another video
`// Get a reference to the current frame as Texture2D.
Texture2D currentFrame = (Texture2D)mediaPlayer.TextureProducer.GetTexture();
// Blit the pixels on texture to the RenderTexture
Graphics.Blit(currentFrame, TransitionRenderTexture);
// Set the Texture on the Transition Screen Mesh Renderer Material
transitionScreenMeshRenderer.material.SetTexture("_MainTex", TransitionRenderTexture);`

3. The render texture is black

**Comment by RenderHeadsSte** [comment] 2019-06-14 14:55
Whilst we were not able to reproduce this issue, we have seen a variant of the 'black frame' issue when using the ExoPlayer API path.

We have just released Version 1.9.17, which contains a fix for said issue in the ExoPlayer API path.  Maybe you could grab this version and check to see if the problem you are seeing has been addressed?

**Comment by AndrewRH** [comment] 2019-06-19 12:08
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  If you're still having this issue with the new version please do let us know.

Thanks,

**Comment by AndrewRH** [comment] 2019-06-26 13:30
Closing issue - presumed fixed

**Closed by AndrewRH** 2019-06-26 13:30 UTC
Labels: Android, bug

**Comment by AntonioStissi** [comment] 2019-06-27 08:01
Hi Andrew,
thanks for your reply, I still was not able to test the new plugin with
ExoPlayer. I will plan some test in the next few weeks.

Thanks!
Antonio

[image: Warp Industries]Antongiuseppe StissiTech Lead VR App+31 6 305 208 88
[image: Facebook] <https://www.facebook.com/warpindustries/> [image: Medium]
<https://medium.com/warp-industries> [image: LinkedIn]
<https://www.linkedin.com/company/10780715/> [image: Twitter]
<https://twitter.com/WarpVR> [image: Youtube]
<https://www.youtube.com/channel/UCpXmC1NyDYnmDmWpdaVGs8w> [image: Website]
<https://warp.industries/>

This message is confidential. If you have received this message in error,
please let us know and delete this email.

Warp is not liable if this message has been modified and/or sent without
permission. Warp Industries | KvK: 68335458
Molengraaffsingel 12, 2629 JD Delft, the Netherlands
<https://maps.google.com/?q=Molengraaffsingel+12,+Delft,+the+Netherlands&entry=gmail&source=g>
