### ISSUE TITLE
Using ExoPlayer + Unity audio on Android, audio random pops

### ISSUE THREAD

**Issue by richardzhangHEAR360** [RenderHeads/UnityPlugin-AVProVideo#960] opened 2021-10-11 23:06 UTC
**Describe the issue**
Using ExoPlayer + Unity audio on Android, audio random click/pops about every 10 secs to every minutes.
ExoPlayer + System Direct audio works perfectly, but we need Unity audio since we need to process the audio. 
Tested both in Unity 2021.1.14f1 and 2019.4.19f1, both had the same issue.
Streaming a video with multi-channel audio is much easier to replicate. (Although by default, we only output the first 2 channels using AudioOutput script)
Streaming a video with 2.0 audio track can also replicate, but much less frequently.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version: 2.2.1 
 - Operating system version: Android 11 
 - Device model: Samsung S20 FE
 - Video specs (resolution, frame-rate, codec, file size):  H264 MP4 + AAC (2Mbps video + 348Kbps 5.1 audio)

**To Reproduce**
1. Import AVPro 2.2.1 plugin to a new project
2. Stream a MP4 video file either from web or locally with a 5.1 audio track in MediaPlayer
3. Build and run on any Android device

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://wowzafiles.s3.us-west-2.amazonaws.com/DarkKnightAACLow.mp4

This is the recording recorded from my Android device upon streaming this content using AVPro 2.2.1:
https://wowzafiles.s3.us-west-2.amazonaws.com/pop.wav
At about 6.5s and 12.7s, you will hear the first 2 pops.
There are at least 10 pops while streaming this content.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by richardzhangHEAR360** [comment] 2021-10-13 07:21
Yes, using Demo_MediaPlayer scene.
Also tested on Pixel 3, playing for the first 4 mins, I heard at least 2 pops.
This issue replicates more easily while playing a video with higher bitrate audio track and having more audio channels.
Paying locally or remotely have exactly the same chance of getting this issue.

Feel free to try this one, a much higher audio bitrate on 5.1 audio track:
https://wowzafiles.s3.us-west-2.amazonaws.com/DarkKnightAAC.mp4

**Comment by richardzhangHEAR360** [comment] 2021-10-14 06:01
Was the only pop due to buffering in 10 minutes sounds exactly the same as my pop.wav recording? (At about 6.5s and 12.7s)

I just sent an APK build with DarkKnightAAC.mp4 in the StreamingAssets folder.
Tried on Pixel 2 and Pixel 3 phones, the audio pops barely happen.
However, on Samsung S20 FE (using an USB TYPE C to 3.5mm adapter) and Pico VR 4K headset (directly plugged in 3.5mm port), the audio pops happen pretty often, every 10s to 1 min.
Also, I tested using Samsung Galaxy Buds+, seems hard to replicate the issue.
To summary, to replicate more easily, better to use Samsung devices, directly plugging headsets to 3.5mm port or through a USB TYPE C to 3.5mm adapter.
These pops on Samsung device may also relates to local audio buffer draining.

**Comment by cross6180** [comment] 2021-10-15 03:21
If is in VR, maybe you could try to disable the Doppler effect in unity audio settings.
I’ve encountered similar issue, disable that solved my problem.

**Comment by kahnivore** [comment] 2021-11-03 12:52
@richardzhangHEAR360 we'll test this on the Pico as soon as we can.

**Comment by RenderHeadsSte** [comment] 2021-11-04 15:40
@richardzhangHEAR360 I have tried this on a Pico G2 4k and have reproduced it with your project and the video with the 5.1 higher bitrate audio you posted above in Unity 2021.1.13.  I have also reproduced it with the AVPro trial in the same version of Unity.

Here is where it gets interesting.

I could not reproduce it in Unity 2018.4.15 using either your project or the AVPro trial version.

Needs more investigation.  But in the mean time, I wonder if you could confirm the problem does not happen in Unity 2018?

**Comment by RenderHeadsSte** [comment] 2021-11-04 18:32
By way of trying to see what is happening to the audio samples I did the following:

- Made a video with 5.1 audio stream with sine wav in L and R only
- Played this back on the Pico via a build made in Unity 2021.1.13
- Record the samples I get back from AVPRo native plugin at the point of 'GrabAudio' in the AudioOutputManager class
- As I was recording the wav file, I listened for glitches...there were approximately 10

There are no glitches in the recorded audio wav file.

Hmm

**Comment by richardzhangHEAR360** [comment] 2021-11-04 18:48
@RenderHeadsSte 
Thank you very much for the testing.

How about recording the wav file right after 'RequestAudio'?
If so, then probably due to a temp buffer underrun.

**Comment by RenderHeadsSte** [comment] 2021-11-04 19:20
Decent shout.  But exactly the same result grabbing data after RequestAudio - albeit a stereo wav is output rather than a 6 channel one.

**Comment by richardzhangHEAR360** [comment] 2021-11-04 21:07
Hmm, if you cannot record any glitches in 'OnAudioFilterRead', then probably 'RequestAudio' sometimes stuck the Unity audio thread.

**Comment by RenderHeadsSte** [comment] 2021-11-05 12:03
Tracked back to native GrabAudio call taking sometimes 2 to 9 ms on occasion.  Looking into why that might be.

**Comment by richardzhangHEAR360** [comment] 2021-11-10 07:21
Glad that you found the cause. Thanks.
Is it promising to be fixed in the upcoming release?

**Comment by kahnivore** [comment] 2021-11-10 15:05
We're still investigating currently. Thank you for your patience on this!

**Comment by richardzhangHEAR360** [comment] 2021-11-15 22:55
Thanks. Please keep me posted.
We still have customer waiting.
Any update would be appricated.

**Comment by RenderHeadsSte** [comment] 2021-11-26 06:31
We have a possible fix implemented, it will be in the next release.  I am afraid we do not have a date pencilled in for that yet but it should be within the next week.

**Closed** 2021-12-06 19:05 UTC
Labels: Android, Fixed

**Comment by AndrewRH** [comment] 2021-12-06 19:47
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,
