### ISSUE TITLE
Videos Frame numbers are not synched on Android as in Editor

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#1999] opened 2024-09-11 17:24 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I want to pause my video at a specific frame number for example at 504. But the displayed frame on pausing the video at 504 in Android is not exactly the same as it is in editor

**Your Setup (please complete the following information):**
 - Unity version: 2021
 - AVPro Video version (3.0.7 (trial)): 
 - Android 14: 
 - Device model: Redmi Note 12
 - Video specs (1920 x 1080, 24 fps, 213MB):

**Comment by Chris-RH** [comment] 2024-09-12 08:11
Please make sure that you are testing with the latest version of AVPro Video, 3.0.10.

What code are you using to pause on the specific frame?
Are you streaming or using a local video?
Are you able to supply a sample video or URL that you are using for testing?

**Comment by noman5412** [comment] 2024-09-12 10:37
Now using the latest version of AVPro 3.0.10
Command to seek to specific frame is "_mediaPlayer.Control.SeekToFrame(11479)"
Streaming video from aws s3 bucket
Moreover I have emailed you at unitysupport@renderheads.com with more details.

**Comment by Ste-RH** [comment] 2024-09-12 14:21
@noman5412 We have a fix for this.  It looks like Android, under the hood at SDK level, rounds frames up...whilst every other platform internally rounds as one would traditionally expect.  Likely a very long standing bug in AVPro Video.

The good news is, this is a very easy fix...and one you do not have to wait for our next release to address.

Open Helper.cs and change the function 'ConvertFrameTimeToSeconds' to:

```csharp
public static double ConvertFrameToTimeSeconds(int frame, float frameRate)
{
	frame = Mathf.Max(0, frame);
	frameRate = Mathf.Max(0f, frameRate);
	double frameDurationSeconds = 1.0 / frameRate;
#if !UNITY_EDITOR && UNITY_ANDROID
	return ((double)frame * frameDurationSeconds);
#else
	return ((double)frame * frameDurationSeconds) + (frameDurationSeconds * 0.5);       // Add half a frame we that the time lands in the middle of the frame range and not at the edges
#endif
}
```

We will make this change for the next release as well.

Thanks for reporting the issue!

**Comment by Ste-RH** [comment] 2024-09-12 15:59
@noman5412 AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.

**Closed** 2024-09-19 08:01 UTC
Labels: Bug 🐛, Android, Fixed

**Comment by noman5412** [comment] 2024-10-16 11:48
Hello again,
I have just noticed that _mediaPlayer.Control.SeekToFrame(int frameNumber) is working perfectly on Android but _mediaPlayer.Control.GetCurrentTimeFrames() is not returning the right frame number in Android.
I have tested this using the latest version of AVPro v3.0.11 and tried on two different android devices.

like if you seek to frame number for example 14000 on android and then debug the frame number using _mediaPlayer.Control.GetCurrentTimeFrames() then the result will be 13999 in android logcat which is a single frame difference.

Please provide a solution for it.

**Comment by Ste-RH** [comment] 2024-10-16 13:34
@noman5412 

I have reproduced this in v3.0.11, but it appears to be addressed in v3.1.0 (which we are working hard to get released).

**Comment by Ste-RH** [comment] 2024-10-16 14:02
(post deleted due to me providing inaccurate information)

**Comment by Chris-RH** [comment] 2024-10-18 16:43
AVPro Video version 3.1 has been released
