### ISSUE TITLE
2.6.4 iOS fatal bug: memory leak

### ISSUE THREAD

**Issue by garric** [RenderHeads/UnityPlugin-AVProVideo#1402] opened 2022-12-15 03:54 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Our game have recently upgraded avpro from v1 to v2.6.4，and game is released out yesterday. But, out tester find that 2.6.4 have memory leak on iOS, and It will crash due to out of memory If played multipletimes。This bug is very very very serious for us。 

**Your Setup (please complete the following information):**
 - Unity **custom** 2019.4.22a1/Unity **official** 2019.4.40f1c1:
 - Avpro 2.6.4 
 - iOS
 - video details is not important

**To Reproduce**
1. download the preview package https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/download/2.6.4/UnityPlugin-AVProVideo-v2.6.4-Trial.unitypackage
2. create a Unity project with two scenes
 2.1 EmptyScene（the first scene）, which can switch Demo_MediaPlayer(included in the preview package)
 2.2 Demo_MediaPlayer, which can switch to EmptyScene
3. build project and run on iOS.
4. Enter the EmptyScene, then switch to Demo_MediaPlayer scene(play vedio)，then back to EmptyScene, and so repeatedly.
5. Memory leak is happened, which proved by xcode stats(see screeshots)

**Screenshots**
![WeChatWorkScreenshot_10176752-154b-49a2-84c3-e70807af594e](https://user-images.githubusercontent.com/1220348/207768109-e152aa02-2b61-41a4-ae59-a8960633a38c.png)
![WeChatWorkScreenshot_9381efd5-4897-4209-a0e3-842ed8ca4e1a](https://user-images.githubusercontent.com/1220348/207768116-12b9acfc-94ea-4b5b-ab67-87670317e73f.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment] 2022-12-15 09:33
Please update to latest version (2.6.7) and see if the issue still occurs.
It would also be very useful to know the kind of media being played. Is it being played locally or streamed, if streamed mp4 or HLS?

**Comment by garric** [comment] 2022-12-15 10:10
> Please update to latest version (2.6.7) and see if the issue still occurs. It would also be very useful to know the kind of media being played. Is it being played locally or streamed, if streamed mp4 or HLS?
1. The tested video is RenderHeads.mp4 included in v2.6.4 preview pakcage. 
2. We have released our game. Upgrade to 2.6.7 means we have to make a full update to users, which is not the suitable option for now. Is there any workaround(like call some c# method)?

**Comment by garric** [comment] 2022-12-15 10:18
> 

The bug has been the highest priority task for our project. If needed, I can send  the test package to you.

**Comment by MorrisRH** [comment] 2022-12-15 11:22
I can confirm that version 2.6.4 has a memory leak, and that it is fixed in version 2.6.7.
I'm afraid that upgrading to the latest version is your only option as the fix was in the native code side.

**Comment by garric** [comment] 2022-12-15 11:35
> .



> I can confirm that version 2.6.4 has a memory leak, and that it is fixed in version 2.6.7. I'm afraid that upgrading to the latest version is your only option as the fix was in the native code side.

That's a bad news for us.
1.We find 5 texture 0xxx and 1 TextureProducer texture in xcode. When mediaplayer is destoried, are all "5 texture 0xxx and 1 TextureProducer texture" leaked?  It's possible to only use one mediplayer, use this mediaplayer to play all videos in game；Is there still exists memory leak in this situation?
3.What's difference from 2.6.4 and 2.6.7? It's risk for our oneline game to upgrade plugin, especially after this experience from v1 to v2.6.4. Is there possible for you to supply a fix patch only for this memory leak bug?

**Comment by garric** [comment] 2022-12-15 11:51
> 

The memory leak is for all iOS devices? It's possible to explain the reason of memory leak?

**Comment by MorrisRH** [comment] 2022-12-15 12:13
1. I don't think using a single player instance will fix the issue.
2. This is the list of iOS specific changes since version 2.6.4 not including the memory leak:
* #1259 Fixed issue with incorrect output being assigned when voice over is activated
  * video would play but not show any output if voice over mode is activated
* #1367 Added support for videos where multiple audio tracks are set as enabled
  * edge case for media that has been authored with multiple audio tracks all set as enabled, will only affect players with the ```Audio Output Mode``` set to ```Unity```.
* #1314 Added support for modifying the audio output mode after player creation but before calling OpenMedia
  * minor tweak to allow changing the output audio mode before opening the media file
* #1326 Built with Xcode 13.2.1 to ensure compatibility with Unity cloud build

Aside from the memory leak, all the other fixes have been minor.

**Comment by MorrisRH** [comment] 2022-12-15 12:15
> The memory leak is for all iOS devices? It's possible to explain the reason of memory leak?

The issue was a regression in our texture management code which was fixed as soon as it was spotted. It is not device specific and affected both macOS and iOS.

**Comment by garric** [comment] 2022-12-15 13:04
> 

I compared v2.6.4 and v.2.67：
most c# modifications are related to iOS/macOS, so what's the changes on android?

**Comment by garric** [comment] 2022-12-15 13:05
> 1. I don't think using a single player instance will fix the issue.
> 2. This is the list of iOS specific changes since version 2.6.4 not including the memory leak:
> 
> * [iOS with VoiceOver activated does not display videos #1259](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1259) Fixed issue with incorrect output being assigned when voice over is activated
>   
>   * video would play but not show any output if voice over mode is activated
> * [Video with multiple audio tracks causes choppy audio when played through Unity on macOS/iOS #1367](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1367) Added support for videos where multiple audio tracks are set as enabled
>   
>   * edge case for media that has been authored with multiple audio tracks all set as enabled, will only affect players with the `Audio Output Mode` set to `Unity`.
> * [Unable to record audio of the video rendered on 3D mesh using third party plugins like NatCorder #1314](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1314) Added support for modifying the audio output mode after player creation but before calling OpenMedia
>   
>   * minor tweak to allow changing the output audio mode before opening the media file
> * [Issue building IOS with cloud build after latest Update #1326](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1326) Built with Xcode 13.2.1 to ensure compatibility with Unity cloud build
> 
> Aside from the memory leak, all the other fixes have been minor.

I compared v2.6.4 and v.2.67：
most c# modifications are related to iOS/macOS, so what's the changes on android?

**Comment by MorrisRH** [comment] 2022-12-15 13:19
List of Android changes since 2.6.4:
* Upgraded ExoPlayer from 2.18.0 to 2.18.1
* #1313 Audio piped through Unity should now sync on loop
* Added 'multiview' support to the UI transparent OES shader (AVProVideo/Internal/UI/Transparent Packed (stereo) - AndroidOES)
* #1352 Return from plugin modified to address issue seen only in Unity 2018
* #1342 Shaders fixed for right eye offset issues when using multiview in VR with OES and monoscopic videos

**Comment by garric** [comment] 2022-12-15 13:41
> List of Android changes since 2.6.4:
> 
> * Upgraded ExoPlayer from 2.18.0 to 2.18.1
> * [Android - Audio out of sync when using Unity audio output with a looping video #1313](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1313) Audio piped through Unity should now sync on loop
> * Added 'multiview' support to the UI transparent OES shader (AVProVideo/Internal/UI/Transparent Packed (stereo) - AndroidOES)
> * [Crash on Android when video starts: JNI DETECTED ERROR IN APPLICATION #1352](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1352) Return from plugin modified to address issue seen only in Unity 2018
> * [Monoscopic 360° Videos on Quest using OES & Multiview = Right Eye skewed #1342](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1342) Shaders fixed for right eye offset issues when using multiview in VR with OES and monoscopic videos

Thanks

**Comment by MorrisRH** [comment] 2022-12-19 09:33
Closing this issue as it's already fixed in the latest release.

**Closed by MorrisRH** 2022-12-19 09:33 UTC
Labels: iOS
