### ISSUE TITLE
Unity 2020.2.1 Android Crash

### ISSUE THREAD

**Issue by pmb1701** [RenderHeads/UnityPlugin-AVProVideo#580] opened 2021-01-20 09:32 UTC
**Describe the bug**
AVPro Video crashes on Quest 1 and 2 when loading a video. This was observed first in our application and then found to happen also with the AVPro Video sample scenes.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: v2.0.1 Core Edition
 - Operating system version: Android
 - Device model: Quest 1 & 2

**To Reproduce**
1. Import AVPro Video - Core Edition.unitypackage in Unity 2020.2.1f1
2. Add the Demo_DisplayComponents sample scene in Build Settings and make an Android build
3. Install and run apk in Quest 1 or 2

**Logs**
https://clients.glue.work/s/NkS23aXzx6CTH2n

**Comment by RenderHeadsSte** [comment] 2021-01-20 11:09
Extracted from log:

FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
Process: com.DefaultCompany.AVProTest, PID: 10566
java.lang.Error: 
FATAL EXCEPTION [Loader:ProgressiveMediaPeriod]
Unity version     : 2020.2.1f1
Device model      : Oculus Quest
Device fingerprint: oculus/vr_monterey/monterey:7.1.1/NGI77B/1201830.9360.0:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.extractor.TrackOutput.sampleData(com.google.android.exoplr2avp.util.ParsableByteArray, int)"
&nbsp;&nbsp;at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:536)
&nbsp;&nbsp;at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:200)
&nbsp;&nbsp;at com.google.android.exoplr2avp.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
&nbsp;&nbsp;at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
&nbsp;&nbsp;at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:415)
&nbsp;&nbsp;at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
&nbsp;&nbsp;at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
&nbsp;&nbsp;at java.lang.Thread.run(Thread.java:761)

**Comment by RenderHeadsSte** [comment] 2021-01-20 11:30
Also in the log:

[AVProVideo] Initialising AVPro Video v2.0.1 (native plugin v2.0.0f1-core) on Adreno (TM) 540/Vulkan 1.0.0 [512.513.0] (MT False) on Android

@pmb1701 I think you have your Graphics API set to Vulkan (it might be set to Auto), not OpenGLES3 or OpenGLES2.  Can you check this please?  We do not currently support Vulkan.

**Comment by pmb1701** [comment] 2021-01-20 11:44
Our application is set to OpenGLES3, but I did indeed forget to change it from Vulcan for the test project this log is from. However, changing it has no effect on the outcome, the demo scene still crashes with the same fatal exception.

**Comment by RenderHeadsSte** [comment] 2021-01-20 12:05
Oki, I will look deeper :)

Can I get a log from the OpenGLES3 run please   Just in case there is something different.

**Comment by pmb1701** [comment] 2021-01-20 12:11
Of course, here it is:
https://clients.glue.work/s/Fbbn8RKNxmGzeHC

**Comment by RenderHeadsSte** [comment] 2021-01-20 13:00
Log reports:

FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
Process: com.DefaultCompany.AVProTest2, PID: 15665
java.lang.Error: FATAL EXCEPTION [Loader:ProgressiveMediaPeriod]
Unity version     : 2020.2.1f1
Device model      : Oculus Quest
Device fingerprint: oculus/vr_monterey/monterey:7.1.1/NGI77B/1201830.9360.0:user/release-keys
Build Type        : Release
Scripting Backend : Mono
ABI               : armeabi-v7a
Strip Engine Code : false

Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.extractor.TrackOutput.sampleData(com.google.android.exoplr2avp.util.ParsableByteArray, int)"
&nbsp;&nbsp;at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:536)
&nbsp;&nbsp;at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:200)
&nbsp;&nbsp;at com.google.android.exoplr2avp.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
&nbsp;&nbsp;at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
&nbsp;&nbsp;at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:415)
&nbsp;&nbsp;at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
&nbsp;&nbsp;at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
&nbsp;&nbsp;at java.lang.Thread.run(Thread.java:761)

I have ran the Demo_MediaPlayer scene here with the Cones 2K HEVC video on a Quest1 in Unity 2018.4.15f1 and everything is as it should be.   Will try Unity 2020.2.x now

**Comment by RenderHeadsSte** [comment] 2021-01-20 13:58
Have reproduced here in Unity 2020.2.1f1.  Didn't have to use a Quest to reproduce.

**Comment by RenderHeadsSte** [comment] 2021-01-20 17:51
It appears the issue is the same as [this](https://stackoverflow.com/questions/57990458/exoplayer-not-playing-add-and-got-crash).

We do have...

android.enableDexingArtifactTransform=false

...set in the Android plugin build environment, but it appears this needs to be set when building with Unity 2020.2.x.  This is done by exporting the project out of Unity, opening in android Studio, adding that property to the 'gradle.properties' file, building and deploying.  This is far from ideal.  I will continue to see if I can find a work-around without having to export the project.

**Comment by RenderHeadsSte** [comment] 2021-01-20 18:01
And here is the solution to avoid exporting the project each time you want to build/run...

Go to the 'Player Settings', 'Publishing Settings', 'Build' and tick 'Custom Gradle Properties Template'  Edit the file shown in the path (\Assets\Plugins\Android\gradleTemplate.properties) and add the line:

android.enableDexingArtifactTransform=false

Save the file and build/run your project out of Unity.

![image](https://user-images.githubusercontent.com/46531149/105215657-70e92580-5b49-11eb-9725-12cf096823c5.png)
![image](https://user-images.githubusercontent.com/46531149/105215557-5020d000-5b49-11eb-975e-6bdce50f08bc.png)

**Comment by RenderHeadsSte** [comment] 2021-01-20 18:01
If you could try this fix and let me know how it works out for you @pmb1701 I would very much appreciate it

**Comment by pmb1701** [comment] 2021-01-20 19:08
I added that custom gradle property in our application project, and I can confirm that does indeed solve the crashing issue - unfortunately, only to reveal another issue, which is that Info.GetVideoWidth() and Info.GetVideoHeight() return zero for the dimensions of all videos in the Android build, which makes useless my own aspect ratio preservation solution that I had to implement in order to use the Apply To Mesh component. In the Editor, as well as Mac and Windows builds those methods return correct dimensions. I will create a new issue for that.

**Comment by RenderHeadsSte** [comment] 2021-01-20 20:48
That sounds very strange indeed!  Looking forward to getting some details :)

Will close this issue now.

**Closed by RenderHeadsSte** 2021-01-20 20:48 UTC
Labels: Android

**Comment by pmb1701** [comment] 2021-01-20 21:21
As a matter of fact I was able to fix it by getting the dimensions and calculating the aspect ratio upon a different MediaPlayer event. In Editor as well as Windows and Mac builds the dimensions seem to be correctly reported when the Started event fires, but in the Android build I had to react in FirstFrameReady instead, which seems like a more logical place anyway so I'll refrain from creating another issue. :) Thank you for the fix for the crash issue!

**Comment by RenderHeadsSte** [comment] 2021-01-20 22:10
Ahh, oki...this is interesting!

You are seeing this because the Started event fires when the plugin says 'IsPlaying' is true.  The width/height returned back from the c# AndroidMediaPlayer are actually local class members that are set when there is a texture to return.  The log time between these is 13ms...so the next frame in essence.  I might look at bringing this into line with other platforms for consistency.

Thanks for reporting it!

**Comment by bonsenz** [comment] 2021-07-01 06:26
I had this problem too. Setting _android.enableDexingArtifactTransform=false_ did not solve the issue for me (working with Unity 2021.1.10f1). I found [this](https://github.com/google/ExoPlayer/issues/8128). I added _-keepnames class com.google.common.** { *; } to my produard-user file and more more crashing.
