### ISSUE TITLE
Using OpenMediaFromBuffer with external splitter causing endless looping in AVPro

### ISSUE THREAD

**Issue by xuserv** [RenderHeads/UnityPlugin-AVProVideo#865] opened 2021-07-15 13:51 UTC
**Describe the issue**
The AVPro causing the whole standalone player or editor stop responding with OpenMediaFromBuffer and external splitter installed environment, However using OpenMedia works fine.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.14f
 - AVPro Video version: 2.1.6-trial
 - Operating system version: Windows 7 / Windows 10
 - Device model: x64-based Generic PC
 - Video specs (resolution, frame-rate, codec, file size): 1280x720 / 60fps / 40MB

**To Reproduce**
1. Install any kind of AIO codec bundles with splitters.
2. Open Media via OpenMediaFromBuffer.
3. AVPro unable to process due to splitter not returning any values and keep waiting for valid results.

**Logs**
No Error Logs Generated, the whole Unity Editor or Standalone is stop responding.

**Notes**
Want to use OpenMediaFromBuffer as possible, currently adapting with encrypted assetbundle.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment] 2021-07-16 08:30
We will have to look into this.  If possible could you send us a cut down scene/script that demonstrates the issue?

Is your video MP4?  Which codec packs have you tried?

Thanks,

**Comment by AndrewRH** [comment] 2021-07-16 08:30
@kahnivore perhaps you could try to reproduce this once they send us their scene/script

Thanks,

**Comment by AndrewRH** [comment] 2021-07-16 08:30
@kahnivore perhaps you could try to reproduce this once they send us their scene/script

Thanks,

**Comment by kahnivore** [comment] 2021-07-16 09:22
@xuserv if you can send us a project so we can reproduce this please do so to unitysupport@renderheads.com with #865 in the subject line. Thanks!

**Comment by xuserv** [comment] 2021-07-16 10:22
> We will have to look into this. If possible could you send us a cut down scene/script that demonstrates the issue?
> 
> Is your video MP4? Which codec packs have you tried?
> 
> Thanks,

Used Video was MP4/AVC with 1920x1080 @ 60fps, I was using StarCodec with default setup and additional MP4/OGG splitters installed.

> @xuserv if you can send us a project so we can reproduce this please do so to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) with #865 in the subject line. Thanks!

No problem! Will do asap.

**Comment by xerorex** [comment] 2021-07-19 09:02
I am also experiencing this problem. Please solve it quickly.

**Comment by xuserv** [comment] 2021-07-19 09:46
The project has been sent to developers and I also did additional test.

This only happens when media loads from buffer, reading from files or URL works fine as mentioned before.
Without splitters it directly goes to 'Microsoft DTV-DVD Video Decoder', However with splitters it goes 'LAV Splitter' then 'Microsoft DTV-DVD Video Decoder'.
My only guess is 'LAV Splitter' doesn't support Read from Buffer feature and making endless loop in here.

Is there any workaround on this?
Asking users to uninstall codecs seems not a good idea to me.

**Comment by kahnivore** [comment] 2021-07-19 14:58
Hey @xuserv 

Checked out your project. I have LAV Splitter installed, and I'm struggling to reproduce your problem. I've tested your scene which is using OpenMediaFromBuffer and the file plays fine. Is there a step I'm missing here?

**Comment by xerorex** [comment] 2021-07-19 15:19
@kahnivore 
In my case, an error occurred when installing the basic version of the codec and the 64-bit version of the codec 'full'. Consider this case.

http://www.starcodec.com/en/x64.php

**Comment by xuserv** [comment] 2021-07-19 15:22
> Hey @xuserv
> 
> Checked out your project. I have LAV Splitter installed, and I'm struggling to reproduce your problem. I've tested your scene which is using OpenMediaFromBuffer and the file plays fine. Is there a step I'm missing here?

That's odd, Have you installed splitters from 'Splitters' folder which included in project or installed from other sources?

**Comment by kahnivore** [comment] 2021-07-19 15:28
I installed LAV Filters from [here ](https://github.com/Nevcairiel/LAVFilters/releases). Would this not be equivalent?

**Comment by xerorex** [comment] 2021-07-21 15:55
@kahnivore Is there any progress on the issue?

**Comment by kahnivore** [comment] 2021-07-21 19:08
Not yet, sorry. We need to investigate this a bit further.

**Comment by xuserv** [comment] 2021-07-27 12:04
Is there any updates on this? I'm currently thinking about improve my local server solution or not.

**Comment by xerorex** [comment] 2021-07-28 15:49
@kahnivore @AndrewRH I don't want you to forget this issue. I'm still waiting for a solution.

**Comment by xuserv** [comment] 2021-08-08 05:21
Little update on this.

> Tried opening a local server then read from it, it does works but there is significant performance drops and no guarantee our port is not used in users pc.
This only happens on MediaFoundation Playback when Ranges response is not supported on Web Server, will proceed after timeout. using DirectShow Playback solved this somehow.

We ended up using Unity VideoPlayer, but this needs to be solved for someone want to play encrypted video.
Using or Making a local server to prevent this problem isn't ideal solution.

**Comment by AndrewRH** [comment] 2022-04-20 16:01
I've reproduced the issue.  I had to install StarCodec64 to get the issues to appear.

1) Big Buck sample video doesn't load and freezes Unity.
2) RenderHeads and Cones sample videos do load, but don't handle seeking and don't loop.

The script I'm using for testing:
      
      using System.Collections;
      using System.Collections.Generic;
      using UnityEngine;
      using RenderHeads.Media.AVProVideo;
      
      public class TestBufferedPlay : MonoBehaviour 
      {
	      [SerializeField] MediaPlayer _mp = null;
      
	      // Use this for initialization
	      void Start () 
	      {
		      Debug.Log("reading " + _mp.MediaPath.GetResolvedFullPath());
		      byte[] buffer = System.IO.File.ReadAllBytes(_mp.MediaPath.GetResolvedFullPath());
		      _mp.OpenMediaFromBuffer(buffer);
	      }
      }

**Comment by AndrewRH** [comment] 2022-04-20 16:47
Okay progress...

So the Big Buck video freezes because of FLV Splitter which enters some code and never returns.  If I install StarCodec64 without FLV Splitter then this video plays correctly.

The others videos however still have the issue where they can't seek/loop.  This seems to be because it's using the LAV Splitter and not our internal GDCL-MPEG4 Demuxer as Big Buck sample video does.  To work around this we're addeding the ability to force the usage of GDCL-MPEG4 which corrects this issue.  

So in the list of preferred filters you can add GDCL-MPEG4 if you're going to be loading MP4 files from buffers and this should have much better behaviour with these different codec packs / splitters installed.  Also this fixes the issue with FLV Splitter, so no need to deselect it during install.

This fix will be in the next update to AVPro Video: v2.4.2

Thanks for your patience.

**Closed** 2022-05-05 16:16 UTC
Labels: Windows, Fixed, Version 2.x
