### ISSUE TITLE
AVProVideo sometimes fails to open a video

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProVideo#729] opened 2021-04-16 11:07 UTC
**Describe the bug**
I tried opening a video recorded by the iphone but it failed silently. (ie. `MediaPlayerEvent.EventType.Error` is never called.)

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.3
 - AVPro Video version: 2.0.11
 - Operating system version: 14
 - Device model: iOS 
 - Video specs (resolution, frame-rate, codec, file size): Video captures recorded with 30 FPS HD & 4K on iPhone XR (HEVC)

**To Reproduce**
1. Load a video
2. Wait until it's ready to play
4. Do it a few times

**Logs**
*xcode output*
```
2021-04-16 13:48:55.038049+0300 [790:112543] [Player] asset duration is   2.62 seconds
2021-04-16 13:48:55.038080+0300[790:112543] [Player] creating 2 player items
2021-04-16 13:48:55.039277+0300[790:112543] [Player] asset is compatible with AirPlay
2021-04-16 13:48:55.046040+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.113242+0300[790:112543] [Player] player item status is ready to play
2021-04-16 13:48:55.113394+0300[790:112543] [Player] player item status is ready to play
2021-04-16 13:48:55.160743+0300[790:112543] [Player] player rate changed to  0.000
2021-04-16 13:48:55.160795+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.160962+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.219595+0300[790:112543] [Player] asset duration is   2.88 seconds
2021-04-16 13:48:55.219627+0300[790:112543] [Player] creating 2 player items
2021-04-16 13:48:55.219993+0300[790:112543] [Player] asset is compatible with AirPlay
2021-04-16 13:48:55.224302+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.256949+0300[790:112543] [Player] player item status is ready to play
2021-04-16 13:48:55.257072+0300[790:112543] [Player] player item status is ready to play
2021-04-16 13:48:55.291990+0300[790:112543] [Player] player rate changed to  0.000
2021-04-16 13:48:55.292043+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.292196+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.333002+0300[790:112543] [Player] asset duration is   3.56 seconds
2021-04-16 13:48:55.333067+0300[790:112543] [Player] creating 2 player items
2021-04-16 13:48:55.333506+0300[790:112543] [Player] asset is compatible with AirPlay
2021-04-16 13:48:55.336599+0300[790:112543] [Player] player time control status changed to paused
2021-04-16 13:48:55.407344+0300[790:112543] [Player] player item status is failed, error: İşlem tamamlanamadı
```

**Possible Fix:**
https://stackoverflow.com/questions/23850366/avplayer-fails-with-avplayeritemstatusfailed-osstatus-error-12983

**Comment by kahnivore** [comment] 2021-04-16 14:27
Hey @cihadturhan 

Which version of 2.0.11 are you using? Core, Ultra or Trial?

Do you perhaps have a sample video we could test? 

Thanks.

**Comment by cihadturhan** [comment] 2021-04-16 14:32
Hi,
It's core iOS.

**Comment by fingerx** [comment] 2021-04-19 00:54
If it runs for a long time, avpro may also fail to open the video. please see https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/730

**Comment by fingerx** [comment] 2021-04-19 00:54
@kahnivore

**Comment by MorrisRH** [comment] 2021-04-19 12:38
I've fixed the issue with the MediaPlayerEvent.EventType.Error not being triggered and this will be available in a future release.
However I've been unable to reproduce the rest of the issue. It may be something specific to do with the media files you're trying to play. Are you able to share them? If so please send them to unitysupport@renderheads.com

**Comment by fingerx** [comment] 2021-04-19 13:45
@MorrisRH  Do you need video files? I have sent you a question email, but the video is not included. My system uses 5.1 usb sound card.

**Comment by MorrisRH** [comment] 2021-04-19 14:04
@fingerx not sure this issue applies to the issue you’re seeing, this is iOS specific

**Comment by fingerx** [comment] 2021-04-19 14:13
@MorrisRH thanks, i send video to unitysupport@renderheads.com #730

**Comment by cihadturhan** [comment] 2021-04-19 15:05
@MorrisRH 
> However I've been unable to reproduce the rest of the issue. It may be something specific to do with the media files you're trying to play. 

Video normally works fine. 
This issue happens if I quickly open, seek and close two 4k videos on iOS. I've implemented my own playlist player similar to yours. It might be because of a memory issue because it doesn't happen always and it happens a few quick load/unload videos. It's nice to have an error event.

So thank you for the fix.

**Comment by cihadturhan** [comment] 2021-04-19 15:08
@MorrisRH I've opened another issue #724 which could be the similar reason: Playing two 4K videos on iOS.

**Comment by MorrisRH** [comment] 2021-04-20 15:41
I think this is the same issue as #704 which has been fixed in version 2.1.0.
Please let us know if this is not the case.

**Comment by shubhank008** [comment] 2021-04-26 16:10
> I've fixed the issue with the MediaPlayerEvent.EventType.Error not being triggered and this will be available in a future release.
> However I've been unable to reproduce the rest of the issue. It may be something specific to do with the media files you're trying to play. Are you able to share them? If so please send them to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

@MorrisRH is the EventType Error not triggering for Failed to open media available in 2.1.0 or will be in another update ?  
Facing same, I want to know or catch this error so I can switch to different mode or show my user to install LAV but even try catch not working with it.  

For now using the returned bool value but Event triggering fix would be great.

**Comment by MorrisRH** [comment] 2021-04-26 16:30
@shubhank008 this issue was with iOS, from the sounds of it you’re targeting windows? If so could you open a fresh issue so our windows devs can handle it specifically? Thanks!

**Comment by shubhank008** [comment] 2021-04-26 18:02
> @shubhank008 this issue was with iOS, from the sounds of it you’re targeting windows? If so could you open a fresh issue so our windows devs can handle it specifically? Thanks!

Thanks will open it

**Comment by MorrisRH** [comment] 2021-04-29 16:53
Closing this issue as #704 has been confirmed as fixed

**Closed by MorrisRH** 2021-04-29 16:53 UTC
Labels: CNR 🤷, Version 2.x, iOS
