### ISSUE TITLE
live stream hls not working in webgl

### ISSUE THREAD

**Issue by adrw2** [RenderHeads/UnityPlugin-AVProVideo#397] opened 2020-06-24 15:04 UTC
**Describe the bug**

Live Streaming videos do not load in webgl.

I tried using hls urls and extrernal assets to get livestream video links. both works fine in unity.

Based on your doc, im following these steps:

- adding hsl as external librery inside webgl platform in Media Player (tested overriding path too)
- build to webgl (tried with WebGL 2.0 and 1.0)
- download hls.min.js file from https://github.com/video-dev/hls.js/releases (tried different versions)
- paste it in TemplateData folder
- add <script src="TemplateData/hls.min.js"></script> in index before UnityLoader.js
- uploaded to itch.io and tested in Chrome, Mozilla, Safari

now im seeking if there is something wrong with CORS, but dont really understand how to setup.

any idea?  thanks

**Your Setup (please complete the following information):**
 - Unity version: 2019.3
 - AVPro Video version: last updated
 - Operating system version: win 10

**Comment by AndrewRH** [comment] 2020-06-24 15:51
Questions:

1) Any error in the console log?
2) Does your live media work in the HLS.JS test?
https://hls-js.netlify.app/demo/

Thanks,

**Comment by adrw2** [comment] 2020-06-25 12:23
Thanks Andrew

1. no

2. when i paste hls url (https:\\manifest.googlevideo....m3u8) got this error: This might be a CORS issue

But it works fine if I install chrome extension: Allow CORS

Is there any other way to setup in order to work for everybody and other browsers?

thank you

**Comment by AndrewRH** [comment] 2020-06-25 13:13
I'm afraid I don't think there is any way to override it.  If the host of the content wants to limit which domains can access it, then that is what they will do...You would need to host your webpage on the same domain, or get the provider to add the CORS permissions for your domain.  So yeah, you would need something like the Allows CORS extension to tell the browser to ignore CORS.

**Comment by adrw2** [comment] 2020-06-25 14:51
I see. So in my case, the host of the content is youtube. 

if the livestream would be uploaded from other platform that allows it, then should it work. is that right? 

do you know where could i test it from?

On the other hand, what about DASH?  would make any difference?

Thanks for your attention. I really appreciate your help.

**Comment by AndrewRH** [comment] 2020-06-26 09:58
DASH won't many any difference.  CORS is something at the browser-level.
I believe that it is against YouTube's EULA to create your own stream using YouTube, so they use CORS (and other tricks) as a way to prevent this.   I'm afraid I don't know any way around this other that what I've mentioned already.  

Since this is not a bug or feature request I'll close this ticket now - but thanks for getting in touch with us.  If you have another issue please open a new ticket.

**Closed by AndrewRH** 2020-06-26 09:58 UTC
Labels: WebGL
