### ISSUE TITLE
Does not import with 2021.1.13 when old version prefab in scene

### ISSUE THREAD

**Issue by cevanno** [RenderHeads/UnityPlugin-AVProVideo#849] opened 2021-07-05 15:35 UTC
**Describe the issue**
Import of trial version 2.1.5 into Unity 2021.1.13 fails. Continually reports 
ArgumentException: Getting control 1's position in a group with only 1 controls when doing repaint
Aborting

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.13
 - AVPro Video version: 2.1.5 trial
 - Operating system version: Windows 10 H2
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Open new 3D project
2. Setup for Quest development by installing Oculus Integration 1.9.1 and XR Plugin Management 4.0.5
3. Import AVPro package => View the Console to see the repeating errors

**Logs**
[AVProInstall_Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6765263/AVProInstall_Editor.log)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment] 2021-07-06 10:05
I'm afraid I can't reproduce this problem.  I followed your steps exactly but didn't get any errors/warnings and the plugin was completely usable.   Could you try again?

**Comment by AndrewRH** [comment] 2021-07-06 10:54
I wonder if it has something to do with your specific window layout in Unity, or what you click on directly after importing?

From the logs it looks like it's failing at drawing the media path UI which should only be rendered if you click on the MediaPlayer component or a MediaReference asset - is that something you do?

I still haven't managed to reproduce this error...

**Comment by cevanno** [comment] 2021-07-06 19:04
Thank you for looking at this.  I believe my project was not as clean as I'd described.  I had a prefab with avp components in it from an older avp release (simple player on a sphere) and disabling that seemed to allow the import to complete. The new avp components are not backward compatible to the version I had.
I don't mean to hijack this thread but I've used avp in the past and its my top choice for my new project but I can't seem to get started. 
I need to play a 360 video in Quest2. Your docs say quest2 is supported but as soon as I replace the MainCamera with the OVRCameraRig in the Hierarchy,  all the avp materials seem to stop working.  To reproduce something similar, open your Demo_DisplayComponents and replace the MainCamera with OVRCameraRig and you see the skybox texture disappear and the cube turns black (like my sphere for 360 playback). Just to verify this is not a general complaint, I added a new 3d object (sphere) with the standard shader and made it blue and this appears in the quest and appears alongside the black avp cube where the materials don't work in quest.  Surprisingly, they work fine in Editor play.  Can you point me to documentation or a demo that works?

**Comment by AndrewRH** [comment] 2021-07-07 21:07
Thanks I see you have created a new issue for this.

I will close this thread unless you're still having issues with importing the plugin.  And yes, if you have components from the old version then there may be issues but we can't found for all eventualities.

Thanks,

**Closed** 2021-07-08 07:06 UTC
Labels: Version 2.x, not a bug

**Comment by cevanno** [comment] 2021-07-10 13:54
Agree closing this. Yes, started new issue for the new issue to keep thread on topic so others can find the answer in their searches.
