### ISSUE TITLE
[Android] SeekFast causes crash

### ISSUE THREAD

**Issue by Aunter1992** [RenderHeads/UnityPlugin-AVProVideo#1903] opened 2024-06-19 09:52 UTC
1、SeekFast causes crash， log
FATAL EXCEPTION: main
                                                                                                    Process: com.DefaultCompany.AVProTest, PID: 13025
                                                                                                    java.lang.IllegalArgumentException
                                                                                                    	at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:40)
                                                                                                    	at androidx.media3.exoplayer.SeekParameters.<init>(SeekParameters.java:71)
                                                                                                    	at com.renderheads.AVPro.Video.Player_ExoPlayer._seekWithTolerances(Unknown Source:66)
                                                                                                    	at com.renderheads.AVPro.Video.Player_Base.UpdateCommandQueue(Unknown Source:85)
                                                                                                    	at com.renderheads.AVPro.Video.Player_Base.Update(Unknown Source:100)
                                                                                                    	at com.renderheads.AVPro.Video.Manager$1.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8223)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

**Comment by Chris-RH** [comment] 2024-06-19 10:32
Which version of AVPro Video is this please?

**Comment by Aunter1992** [comment] 2024-06-19 10:34
3.0.3

**Comment by Chris-RH** [comment] 2024-06-19 10:40
Is it Vulkan or OpenGLES?
Can you reproduce it in one of our demo scenes?

**Comment by Aunter1992** [comment] 2024-06-19 11:29
DemoScene :AVProVideo\Demos\Scenes\Demo_MediaPlayer.unity
change seek to seekfast
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/1c071ee1-8b1e-4e7b-8ce4-55395cfd740b)

click TimeForwardButton

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/fa26a9e4-9505-46f5-8bf9-33c2a1ea17e3)

**Comment by Ste-RH** [comment] 2024-06-19 15:12
Can you send over a full logcat please?

**Comment by rrenderr** [comment] 2024-06-19 18:31
@Ste-RH 
Attach the full log in this thread, as you asked me.
[FullLog.log](https://github.com/user-attachments/files/15904743/FullLog.log)

**Comment by Ste-RH** [comment] 2024-06-25 14:34
Are you able to provide the URL you are using @Aunter1992 ?

**Comment by Aunter1992** [comment] 2024-06-26 02:25
> Are you able to provide the URL you are using @Aunter1992 ?
 I  used avprovideo demo
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/db0293f0-aa18-41d6-8210-13fc0d3fcac3)

**Comment by Ste-RH** [comment] 2024-06-26 09:55
Reproduced!  There will be a fix for this in the next release (v3.0.5).

**Comment by Chris-RH** [comment] 2024-06-28 11:32
AVPro Video version 3.0.5 has been released.  Please let us know if it has not fixed your issue.

**Comment by rrenderr** [comment] 2024-07-04 15:27
It works for me

**Comment by Aunter1992** [comment] 2024-07-05 05:54
When I switch videos and use seekfast to reload the progress, if I do it multiple times, the application crashes.

07-05 11:34:04.026  9599  9599 I System.out: AVProVideo video state: buffering
07-05 11:34:04.028  9599  9599 I System.out: AVProVideo video state: ready | m_VideoState: 4 | m_bIsBuffering: true
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: JNI CallStaticVoidMethodV called with pending exception java.lang.NullPointerException: Attempt to read from field 'int com.renderheads.AVPro.Video.Player_Base$VideoCommand._command' on a null object reference in method 'boolean com.renderheads.AVPro.Video.Player_Base.lambda$RemoveDuplicateCommand$0(int, com.renderheads.AVPro.Video.Player_Base$VideoCommand)'
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean com.renderheads.AVPro.Video.Player_Base.lambda$RemoveDuplicateCommand$0(int, com.renderheads.AVPro.Video.Player_Base$VideoCommand) (SourceFile:-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean com.renderheads.AVPro.Video.Player_Base$$ExternalSyntheticLambda0.test(java.lang.Object) (D8$$SyntheticClass:-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean java.util.Collection.removeIf(java.util.function.Predicate) (Collection.java:576)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void com.renderheads.AVPro.Video.Player_Base.RemoveDuplicateCommand(int) (SourceFile:-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void com.renderheads.AVPro.Video.Player_Base.SeekWithTolerances(double, long, long) (SourceFile:-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void com.renderheads.AVPro.Video.Manager.Player_Seek(int, double, double, double) (SourceFile:-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer.access$600(com.unity3d.player.UnityPlayer) ((null):-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean com.unity3d.player.UnityPlayer$g$1.handleMessage(android.os.Message) ((null):-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void android.os.Looper.loop() (Looper.java:294)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]   at void com.unity3d.player.UnityPlayer$g.run() ((null):-1)
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591] 
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]     in call to CallStaticVoidMethodV
07-05 11:34:04.029  9599  9653 F ro.nebula:space: java_vm_ext.cc:591]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
07-05 11:34:04.051  1201  1201 I QTI PowerHAL: Power setMode: 6 to: 1
07-05 11:34:04.053  1201  1201 E QTI PowerHAL: Failed to acquire lock for hint_id: 10A5.

**Comment by Aunter1992** [comment] 2024-07-08 06:30
[full-log.txt](https://github.com/user-attachments/files/16123581/full-log.txt)

**Comment by Chris-RH** [comment] 2024-07-08 08:21
It looks like it might be a threading issue.
Which Unity version and which main entry point are you using?

**Comment by Aunter1992** [comment] 2024-07-08 08:26
> It looks like it might be a threading issue. Which Unity version and which main entry point are you using?

2021.3.16.f1c1
What does "main entry point" mean?

**Comment by Chris-RH** [comment] 2024-07-08 08:27
Are you using teh latest version of AVPro video? 3.0.6?

**Comment by Aunter1992** [comment] 2024-07-08 08:31
> Are you using the latest version of AVPro video? 3.0.6?

no,  used 3.0.5.
I'll try 3.0.6

**Comment by Aunter1992** [comment] 2024-07-09 10:36
still has the issue , AVProVideo 3.0.6 ultra
[full-log306.log](https://github.com/user-attachments/files/16142085/full-log306.log)

**Comment by Ste-RH** [comment] 2024-07-09 14:35
This is now a different issue.  This is because the player is being destroyed off the main thread.  ExoPlayer now demands that all it's calls are made on the thread that created the object (the main thread in AVPro Videos case).

This will require us to defer the destroy/deinitialise calls to the main thread.  We will look into making this change.

For the record, this is the callstack:

`at void androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread() (ExoPlayerImpl.java:2797)
at void androidx.media3.exoplayer.ExoPlayerImpl.stop() (ExoPlayerImpl.java:995)
at void com.renderheads.AVPro.Video.Player_ExoPlayer._stop() (SourceFile:-1)
at void com.renderheads.AVPro.Video.Player_ExoPlayer.CloseVideoOnPlayer() (SourceFile:-1)
at void com.renderheads.AVPro.Video.Player_Base._CloseVideo() (SourceFile:-1)
at void com.renderheads.AVPro.Video.Player_Base.Deinitialise() (SourceFile:-1)
at void com.renderheads.AVPro.Video.Manager.DestroyPlayer(int) (SourceFile:-1)
at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
at boolean com.unity3d.player.UnityPlayer.access$600(com.unity3d.player.UnityPlayer) ((null):-1)
at boolean com.unity3d.player.UnityPlayer$g$1.handleMessage(android.os.Message) ((null):-1)
at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
at void android.os.Looper.loop() (Looper.java:294)
at void com.unity3d.player.UnityPlayer$g.run() ((null):-1)`

**Comment by Ste-RH** [comment] 2024-07-09 15:23
@Aunter1992 We are struggling to reproduce the crash here.  Can you provide some more information as to your projects setup?  How are you destroying the MediaPlayer?  Are you doing it on a thread?  Or maybe you have the 'Application Entry Point' set to GameActivity?

**Comment by Aunter1992** [comment] 2024-07-10 03:17
> @Aunter1992 We are struggling to reproduce the crash here. Can you provide some more information as to your projects setup?
> 
> * How are you destroying the MediaPlayer?
> * Are you doing it on a thread?
> * Do you have the 'Application Entry Point' set to GameActivity?

1、MediaPlayer destoryed auto.   called by unity method OnDestory()   in MediaPlayer ， I just  delete gameobject view.
2、when  MediaPlayer destoryed auto,  if  I  used  JNI call。   It will throw Exception 
 AndroidJavaException: java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'UnityMain'
Expected thread: 'main'
[full-log-auto-destory.txt](https://github.com/user-attachments/files/16154754/full-log-auto-destory.txt)

**Comment by Ste-RH** [comment] 2024-07-10 10:01
We still cannot get it to crash like you say.  Would you be able to send over a base-bones project to unitysupport@renderheads.com that shows the crash @Aunter1992 ?

**Comment by Aunter1992** [comment] 2024-07-10 10:29
> We still cannot get it to crash like you say. Would you be able to send over a base-bones project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) that shows the crash @Aunter1992 ?

It looks like the issue was with my usage. If I don't call forcedispose before each openmedia, the crash no longer occurs. I have corrected this, thank you.

**Comment by Ste-RH** [comment] 2024-07-10 12:49
Thanks for letting us know!

**Closed by Ste-RH** 2024-07-10 12:49 UTC
Labels: Bug 🐛, Android, Fixed

**Comment by Aunter1992** [comment] 2024-07-11 02:54
I have identified the cause of the problem. It is due to an unhandled exception from AndroidJNI.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/6af9a053-ee94-4190-8829-4b1bac9af23e)
The call to Native.AVPPlayerRelease(_player) threw a JNI exception that was not handled.

If I continue to use JNI calls in C#, it will not cause the program to crash, something like this.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/e8830e16-7d75-4cad-a7a4-a9769aa02d56)
However, if the next JNI call is made in C++, it will cause the program to crash.
Here is how I am handling it to avoid this issue.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/5a4b4c84-5bad-448f-8296-a1afb108ecbe)

This involves the issue of handling AndroidJNI exceptions, which you can look up on your own.

**Comment by Ste-RH** [comment] 2024-07-11 05:44
Back to ‘can you provide a bare bones project that shows the crash/exception’ ?

I can see why it’s happening, but I cannot implement and test a fix if I cannot reproduce it.

**Comment by Aunter1992** [comment] 2024-07-11 05:49
> Back to ‘can you provide a bare bones project that shows the crash/exception’ ?
> 
> I can see why it’s happening, but I cannot implement and test a fix if I cannot reproduce it.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/ba74230c-2fbc-42cb-bb06-851feb430d61)
call SystemInfo.batteryInfo  after AVPlayRelease  , It will  throw  JNI Exception   when  Mediaplayer destoryed. you  can do  a simple test .

**Comment by Ste-RH** [comment] 2024-07-11 12:55
Tried that. No difference.  Cannot reproduce.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46531149/9fd38ee4-1f00-401a-820e-95bfb1d984b7)

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46531149/0701e685-a16b-4c3e-96b1-ecfadcd67a32)

**Comment by Aunter1992** [comment] 2024-07-11 12:58
> Tried that. No difference. Cannot reproduce.
> 
> ![image](https://private-user-images.githubusercontent.com/46531149/347824198-9fd38ee4-1f00-401a-820e-95bfb1d984b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDI4NzQsIm5iZiI6MTcyMDcwMjU3NCwicGF0aCI6Ii80NjUzMTE0OS8zNDc4MjQxOTgtOWZkMzhlZTQtMWYwMC00MDFhLTgyMGUtOTViZmIxZDk4NGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyNTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MzA2OTVlYTAyN2QyNTA5NDdiYzQwYTJjMzNiMjg3MjViMDBjYzcwYjkzYTIxZThkODcxMjdkYjJmOWVmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tPVTFUUl5GpcD74sU7JNW_AfFQVwkammt3DIhUtX15A)
> 
> ![image](https://private-user-images.githubusercontent.com/46531149/347824012-0701e685-a16b-4c3e-96b1-ecfadcd67a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDI4NzQsIm5iZiI6MTcyMDcwMjU3NCwicGF0aCI6Ii80NjUzMTE0OS8zNDc4MjQwMTItMDcwMWU2ODUtYTE2Yi00YzNlLTk2YjEtZWNmYWRjZDY3YTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyNTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjUyMGEyNjMxZjU0MzNkMjc2YzlkZTBmN2IxYmJiZjhhMWZlN2Q2M2Q2YzQyZGUwMmUxODY3ZTY1MmUzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YbZ4QE82vSdJTo_E6emnVjeNgWQnsE5bGb7Vqh3UiY)
Strange problem, let's put it aside for now. I'll organize it later.

**Comment by Aunter1992** [comment] 2024-07-11 12:59
#1942  Please address this issue as soon as possible.

**Comment by Ste-RH** [comment] 2024-07-11 13:08
> #1942 Please address this issue as soon as possible.

How is this issue linked to issue 1942?  If it is not, then cross posting with no link is extremely unhelpful and just slows down how quickly we can offer support.  Please delete the post if the issues are not linked @Aunter1992

**Comment by Ste-RH** [comment] 2024-07-11 15:36
Whilst I cannot reproduce it...I am 99% sure I know what is causing it, and have put a change in to counter the issue.  Not being able to test it, this fix is going in completely blind.

We will include it in the next release (v3.0.7) which we hope to get out tomorrow or early next week.

**Comment by Chris-RH** [comment] 2024-07-16 13:42
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.

**Comment by Chris-RH** [comment] 2024-07-16 14:35
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.
