### ISSUE TITLE
When using AVproVideo2.7.3 on windows 10, frequent dragging (repeated dragging) of the video progress will cause stuck problems

### ISSUE THREAD

**Issue by dabengying** [RenderHeads/UnityPlugin-AVProVideo#1506] opened 2023-04-03 06:18 UTC
**Describe the issue**
When using AVproVideo2.7.3 on windows 10, frequent dragging (repeated dragging) of the video progress will cause stuck problems。

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.3.11
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3（from unity asset）
 - Operating system version: windowns 10
 - Device model: windowns 10 pc
 - Video specs (resolution, frame-rate, codec, file size): 30fps, 1920*1080， MPEG-4 AAC ，H.264,  18.5M

**To Reproduce**
1. When using AVproVideo2.7.3 on windows 10, frequent dragging (repeated dragging) of the video progress will cause stuck problems.  use AVproVideo2.7.3 demo also have same problem.

**Logs**
[2023_3_28(1).log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11135288/2023_3_28.1.log)

**Screenshots**
![img_v2_53cd3fba-2f77-4c92-97c0-4beb5538859g](https://user-images.githubusercontent.com/8490300/229425591-b160fb5f-3d67-4ed5-b0de-163d31b9cf15.jpg)

help!!!
![img_v2_e56d918c-512f-48ae-9690-cc03b82a27eg](https://user-images.githubusercontent.com/8490300/229428676-50339d23-bbc7-4892-91f5-231d38e57c05.jpg)

**Comment by Chris-RH** [comment] 2023-04-03 12:20
I've opened a new project in 2021.3.21 and AVPro Video 2.7.3.  Using the mediaplayer demo scene I have tried various lengths of local and streamed videos.  I have dragged the seek bar up and down repeatedly, I have also clicked up and down it.  I haven't had a crash yet.
Is there something else I should be doing?

**Comment by dabengying** [comment] 2023-04-04 03:27
Hello, I suspect that the issue occurred only on Windows 10. I tried the same operation multiple times on Windows 7 and Windows 11, but there was no problem. However, on the Windows 10 version of the system, I encountered the same issue on two test devices. Can you check it  on Windowns 10?

**Comment by dujimache123** [comment] 2023-04-04 04:03
https://user-images.githubusercontent.com/18678960/229684223-8fe7fa78-5c80-426f-ab98-1da8dd331d6b.mp4

**Comment by dabengying** [comment] 2023-04-04 06:16
Hello, I suspect that the issue occurred only on Windows 10. I tried the same operation multiple times on Windows 7 and Windows 11, but there was no problem. However, on the Windows 10 version of the system, I encountered the same issue on two test devices. Can you check it  on Windowns 10?

I provide a list of device tests, including Win10, Win7, and Win11, but only Win10 will have issues.
And testing demo apps, error logs, and operation videos.
Thank you for helping me check this bug again， Especially for Win10

Demo App:
https://curriculum-us.wntss.com/u3d/download/AVProVideoDemo.zip

Bug recurrence operation video 1：
https://curriculum-us.wntss.com/u3d/download/error-1.mp4

Bug recurrence operation video 2：
https://curriculum-us.wntss.com/u3d/download/error-2.mp4


![devicesList](https://user-images.githubusercontent.com/8490300/229703758-444aaccf-db41-4e18-8d59-1af45804720b.png)
[AVProVideoErrorLog.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11145254/AVProVideoErrorLog.zip)

**Comment by dabengying** [comment] 2023-04-04 10:26
We tested on four Win10 version systems and found that not all Win10 version systems will have issues. The problematic versions are: the home version is Win10 2004, and the enterprise version is Win10 21H2。
app demo url: https://curriculum-us.wntss.com/u3d/download/AVProVideoDemo.zip

![11](https://user-images.githubusercontent.com/8490300/229763753-e8cc783b-789c-455f-b46f-0dfb72eb17e7.jpg)

![22](https://user-images.githubusercontent.com/8490300/229763764-5a640b89-5f45-4c6e-a971-bedb2e0b9360.jpg)

**Comment by Chris-RH** [comment] 2023-04-04 14:26
Have you tested both d3d11 and d3d12?

**Comment by dabengying** [comment] 2023-04-05 11:20
Is it to check if the problem device has d3d11 and d3d12 installed?
Look at the running log, it should support d3d11, I can try to manually upgrade the d3d11 library later

Initialize engine version: 2021.3.10f1c1 (fad0948fb939)
[Subsystems] Discovering subsystems at path 
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) Iris(R) Xe Graphics (ID=0x9a49)
    Vendor:   Intel
    VRAM:     3987 MB
    Driver:   30.0.101.1960
<RI> Initializing input.

[AVProVideo] Initialising AVPro Video v2.7.3 (native plugin v2.7.0f1-core) on Intel(R) Iris(R) Xe Graphics/Direct3D 11.0 [level 11.1] (MT False) on WindowsPlayer

**Comment by Chris-RH** [comment] 2023-04-05 12:47
Could you change it to d3d12 and see if you get the same result please :)

**Comment by dabengying** [comment] 2023-04-06 03:23
I have created a new package using d3d12, and the device that previously had problems running the package using d3d12 is currently working fine.
![image](https://user-images.githubusercontent.com/8490300/230264327-8d5b3e05-2b51-4e72-a241-aef31261206a.png)

https://curriculum-us.wntss.com/u3d/download/AVProVideoTest_d3d12.zip

However, there are currently issues with using the default automatic (d3d11)

GfxDevice: creating device client; threaded=1; jobified=1
d3d12: loaded!
Direct3D:
    Version:         Direct3D 12 [level 12.1]
    Renderer:        Intel(R) Iris(R) Xe Graphics (ID=0x9a49)
    Vendor:          Intel
    VRAM:            3987 MB
    App VRAM Budget: 3588 MB
    Driver:          30.0.101.1960
    Unified Memory Architecture
    Cache Coherent UMA

**Comment by Chris-RH** [comment] 2023-04-06 10:44
OK, that's great thank you, that's useful to know

**Comment by dabengying** [comment] 2023-04-11 02:35
Hello, will this issue be resolved in the near future? Thanks

**Comment by Chris-RH** [comment] 2023-04-11 09:17
We are a very small team, but it is on our TO DO list.

**Comment by dabengying** [comment] 2023-04-12 03:26
Got it, thanks

**Comment by dabengying** [comment] 2023-05-31 03:31
AVPro Video v2.8.0 - 26 May 2023
Hello, is this problem fixed in the latest version? 
I see that the release record seems to have not been modified, right?

**Comment by Chris-RH** [comment] 2023-05-31 07:47
Not yet.

**Comment by songgravel** [comment] 2023-06-19 03:47
I have the same issue on Windows11 when using MediaFoundation as Video API. Switching to DirectShow or Win RT can solve my problem.

**Comment by archain** [comment] 2023-07-05 11:17
Hi, MorrisRH, I notice that you've marked this issue to 'Fixed',  will it be released soon?

**Comment by Ste-RH** [comment] 2023-07-05 11:19
@archain This should be fixed in the last release (v2.8.1).  Do let us know so we can close this issue accordingly.

**Comment by dabengying** [comment] 2023-07-05 11:49
Hi Ste-RH，May I ask when the new version(v2.8.1) will be released?

**Comment by archain** [comment] 2023-07-06 01:32
@Ste-RH Ok, we will check it right now and give you a feedback later

**Comment by archain** [comment] 2023-07-06 02:09
@Ste-RH Unfortunely, it still cause stuck problem on Windows7, The main information is as follows:

2023-07-06T09:43:54: [AVProVideo] Initialising AVPro Video v2.8.1 (native plugin v2.8.0f1-trial) on Intel(R) HD Graphics/Direct3D 11.0 [level 11.0] (MT False) on WindowsPlayer
2023-07-06T09:43:54: [AVProVideo] Opening [url] (offset 0) with API MediaFoundation
2023-07-06T09:43:55: [AVProVideo] Using playback path: DirectShow (848x478@30.00)

On this machine, even if I do not use hardward decoding, the playback is always DirectShow

I click the progress bar back and forward about 10 minutes, it stuck again!

**Comment by Chris-RH** [comment] 2023-07-06 09:29
Sorry, there has been some confusion.  The fix is in the next version, which has not been released yet.
Unfortunately we don't have a Windows 7 machine to test on. I don't believe they are supported at all by Microsoft anymore.

**Comment by archain** [comment] 2023-07-06 10:38
@Chris-RH It seems Windows7 will fallback to DirectShow? MediaFoundation is not supported on windows7? And DirectShow will cause this issue.

By saying "Fixed", it means you fixed issue on windows10, right? I just want to know! thanks!

**Comment by archain** [comment] 2023-07-12 08:43
@Chris-RH I've found that when I use 'DirectShow' on windows 10, or "DirectShow" on windows7,
GetSeekableTimes always return min=0,max=0, is this mean that I can not do seek under "DirectShow"
I've tested on windows7(2GB memory), when I play a remote video, when I seek forward and back, it will cause the app to freeze.
and on windows10, it will take a lot of time to recover.

So is it "DirectShow" implementation's bug?

**Comment by Ste-RH** [comment] 2023-07-12 11:14
We are hoping to release v2.8.2 later today.  This has some improvements in that might help address the original issue.  But as we have been unable to reproduce the issue here, we cannot say 100% whether it will be fixed.

**Comment by archain** [comment] 2023-07-12 11:42
@Ste-RH OK!Thanks a lot!

**Comment by Chris-RH** [comment] 2023-07-12 14:36
AVPro Video version 2.8.2 has been released.  Please let us know if this is still an issue.

**Comment by archain** [comment] 2023-07-13 02:14
@Chris-RH I can reproduct the issue by using windows 10, and I use your demo scene "Demo_MediaPlayer"
1、Open scene "Demo_MediaPlayer"
2、Select "MediaPlayer" at Hierarchy panel
3、On the right Inspector, change Media Source to "Path"
4、Copy url "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" to the "Absolute Path Or URL"
5、Choose render api to "DirectShow"
6、Run unity 3d and do seek operation of the video player, it will freeze the unity3d editor

Why I'm using "DirectShow" on windows 10, it is because we use windows 7, and it will fallback to "DirectShow", the same
result will be caused.

**Comment by Chris-RH** [comment] 2023-07-13 08:35
So is it still not fixed using AVPro video version 2.8.2 in Windows 10?

**Comment by archain** [comment] 2023-07-13 08:57
Using "DirectShow" api and play online video source, seek causes freeze, which can be reproduced
I've tried it by using your demo scene

**Comment by Chris-RH** [comment] 2023-07-13 09:34
@dabengying is it working for you?

**Comment by dabengying** [comment] 2023-07-13 09:59
> @dabengying is it working for you?

It doesn't work. Soft decoding may get stuck on Win7, but the problem was resolved on previous Win10

**Comment by dabengying** [comment] 2023-07-13 10:00
@Chris-RH It doesn't work. Soft decoding may get stuck on Win7, but the problem was resolved on previous Win10

**Comment by RichRH** [comment] 2023-07-19 10:14
Hi @archain,

Thanks for providing these steps - I believe I have managed to reproduce this issue and possibly found a cause. It seems to be a combination of DirectShow, LAV filters (even latest) and your remote/URL MP4 source.

I'm looking into a possible fix (with this video the MS File Source (URL) filter seems to be favoured over the LAV Splitter Source, which aren't very compatible) but my assumptions currently are:

- You're using LAV filters? (For MP4 playback under DirectShow)
- This issue doesn't occur if you use a local version of the video?

Cheers,

**Comment by archain** [comment] 2023-07-19 10:58
Great! @RichRH
1、I do not set LAV filters
2、yes，when use local file, there is no problem

**Comment by RichRH** [comment] 2023-07-20 11:12
Hi @archain,

Thanks for your feedback - after some more investigation I've managed to reproduce the issue _without_ LAV filters being used. This must mean it's using the included GDCL demuxer as for DirectShow MP4 playback a 3rd party splitter _has_ to be used.

It does appear to be the same issue though; MS File Source (URL) filter, your remote/URL MP4 source and a 3rd party demuxer - I'm looking into a fix but a few supplementary notes:

- Only an issue with remote videos, local work fine
- Problem seems to be linked to rapid seeking + MS File Source (URL) filter causing deadlock and locking thread
- Once video is fully downloaded by MS File Source (URL) filter, the problem appears to go away
- LAV Splitter Source instead of MS File Source (URL) filter and LAV Splitter seems to work as expected (but probably not practical for end users)
- I'm looking at trying to remove the deadlock with GDCL to provide an out-of-the-box solution rather than requiring extra filters (such as LAV)

Cheers,

**Comment by Chris-RH** [comment] 2023-07-21 10:44
AVPro version 2.8.3 has been released.  Please let us know if this has not fixed your issue.

**Comment by archain** [comment] 2023-07-21 12:07
@Chris-RH 
Yes, It is solved on windows 10
but on windows 7, there's no graphic, only stall image can be seen, it is not freeze any more

**Comment by Chris-RH** [comment] 2023-07-25 10:21
One the issues that we are having with this is that we don't have any machines that have Windows 7 and it is no longer supported by Microsoft.

**Comment by Chris-RH** [comment] 2023-07-28 11:57
We've managed to install Win7 and aren't seeing these issues.  What hardware are you using? It is most likely to be the cause.

Please also note:

![unity_windows7_720](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/e76511b2-5697-4811-8521-5d2e1b271b79)

**Closed** 2023-08-08 08:38 UTC
Labels: Windows, Fixed
