### ISSUE TITLE
Plugin version number 0.1-core build 1198 doesn't match the expected version number 2.4.0.

### ISSUE THREAD

**Issue by ArkosRPG** [RenderHeads/UnityPlugin-AVProVideo#1113] opened 2022-02-23 12:24 UTC
We've bought iOS only version
Building app with Unity Cloud Build

Got error log on any media player enabled

[AVProVideo] Plugin version number 0.1-core build 1198 doesn't match the expected version number 2.4.0.  It looks like the plugin didn't upgrade correctly.  To resolve this please restart Unity and try to upgrade the package again.

RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(Boolean)
App.UI.DownloadedImage:SetKey(String, String)
...

Nothing seems to be broken but this log spams a lot.

Device: any iOS we try

Media: all your demo links and our hevc/mp4

**Comment by kahnivore** [comment] 2022-02-23 13:04
Have you tried re-importing the package? See [these steps](https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#upgrade-steps).

**Comment by MorrisRH** [comment] 2022-02-23 17:08
Duplicate of #973.
This is due to a change in how Xcode archives projects and beyond our ability to fix, please see [here](https://developer.apple.com/forums/thread/690647) for more information.

**Closed by MorrisRH** 2022-02-23 17:08 UTC
Labels: duplicate, won't fix, iOS
