### ISSUE TITLE
[Android] Game is crushed, when i open it. Quest 2 / 3

### ISSUE THREAD

**Issue by AlexDeKarlo** [RenderHeads/UnityPlugin-AVProVideo#1902] opened 2024-06-18 18:17 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When i open game, game is crushed.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.9f
 - Core 1.11.7
 - Operating system version: Windows 10
 - Device model: Quest3
 - Video specs 5120x5120 60fps 160349 kilobit/s

**To Reproduce**
1. Create project
2. Install AVPro
3. Set path: video.mp4 and use Relative To Persistent Data Folder
4. In editor work great
5. in quest 3/2 game crash

**Logs** Quest 3
[com.DefaultCompany.AVProTest-logcat.txt](https://github.com/user-attachments/files/15890767/com.DefaultCompany.AVProTest-logcat.txt)

**Screenshots** Editor
![test](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46936937/c9f0afac-af14-425d-a6a0-82ca6b4042b3)

**Videos** Quest 3
https://youtu.be/3-BcbP3Mn00

**Comment by Chris-RH** [comment] 2024-06-19 08:29
We no longer support AVPro Video version 1 as it was depreciated in favour of AVPro Video version 2 in Q1 2021.  

1. Are you testing on an actual device or an emulator?
2. Can you reproduce it in a new project running only AVPro Video demo scenes?

From looking at the information provided it looks like the bitrate of your video is exceptionally high.  [Recommendations are a maximum of 100Mb/s](https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/).  You should look into encoding it properly to reduce this.

You can also reduce the[ maximum buffer in the Android options](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/component-media-player.html#platform-specific---android) of the mediaplayer component, so it will require less memory.

Make sure your video is encoded with faststart: ffmpeg -i input.mp4 -acodec copy -vcodec copy -movflags faststart output.mp4

Additionally:

"Alloc concurrent copying GC freed 15(560B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 11us,18us total 19.207ms"
From your log, it seems the system is only allowing your app to allocate 256MB of memory, which isn't very much.  You could try enabling[ largeheap](https://github.com/google/ExoPlayer/blob/r2.11.4/demos/main/src/main/AndroidManifest.xml#L35).

"Error LoadTask java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 64704 free bytes and 63KB until OOM, target footprint 268435456, growth limit 268435456"
It looks like your app was using all its allowed memory and ExoPlayer was denied allocating 65552 byte.

**Comment by MorrisRH** [comment] 2024-06-21 10:51
I see you're using the Mono runtime on Android, I would recommend switching to IL2CPP for builds as you can target 64bit architectures (Mono is 32bit only).

Closing this as we no longer provide support for AVPro Video 1.x.

**Closed by MorrisRH** 2024-06-21 10:51 UTC
Labels: Android, Version 1.x
