### ISSUE TITLE
Oculus Quest Black Screen Issue

### ISSUE THREAD

**Issue by d-d-d-d-d** [RenderHeads/UnityPlugin-AVProVideo#776] opened 2021-05-12 15:49 UTC
I'm having a similar problem to what is described here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/686

And unfortunately Streaming Assets is not workable for me--both apps I'm experiencing it on use large videos I need to upload as expansion files. I've done a number of apps this way and the issue is new as of two weeks ago. 

Traditionally, I use an absolute URL - /sdcard/Android/obb/com.[org].[app]/videofile.mp4 - to load videos. This no longer seems to work.

I've guessed that it's a permissions issue, but including READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in my manifest does not solve it. The files are there, but something is preventing AVPro from loading them. 

I'm currently trying to use a legacy version of Oculus Integration to see if that works--there's been some changes in 28.0, including that the Quest and Quest II are using Android 10--but even if this works I'd love to understand how to get around this in the future in case the legacy Oculus stuff isn't an option. Is there something I need to be doing differently to load large videos? 

Thanks!

**Comment by RenderHeadsSte** [comment] 2021-05-12 16:01
It isn't the size of the video that is an issue, but as you say...permissions.

Android changed file access permissions in Android 10, and more so in Android 11.  Take a look at #596 and #544.  Also check out [this](https://forum.unity.com/threads/android-10-and-scoped-storage-missed-features-in-unity-2019.749333/) forum thread, and [this](https://developer.android.com/training/data-storage#scoped-storage) and [this](https://developer.android.com/about/versions/11/privacy/storage) developer documentation.

Hope this information helps.  Regarding accessing videos on device storage, there is nothing we can really do at AVPro Video asset level.

**Comment by d-d-d-d-d** [comment] 2021-05-12 19:16
Thanks for your response! Unfortunately, following the steps at #596 has not fixed the issue. I've got the MediaPlayer set to Absolute Path/URL, and I'm passing in file:///sdcard/Android/obb/com.[org].[appname]/[moviename] but still no luck. Is there anything else you can think of that I can try? Or is there anything wrong in my Player settings or manifest? 

My player settings:
![Screenshot 2021-05-13 02 09 05](https://user-images.githubusercontent.com/19946735/118031542-dda25d00-b390-11eb-906a-f1875ba684e7.jpg)

and my manifest:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto">
  
  <application android:requestLegacyExternalStorage="true" android:label="@string/app_name" android:icon="@mipmap/app_icon" android:allowBackup="false">
    <activity android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" android:configChanges="locale|fontScale|keyboard|keyboardHidden|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode" android:launchMode="singleTask" android:name="com.unity3d.player.UnityPlayerActivity" android:excludeFromRecents="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.INFO" />
        <category android:name="com.oculus.intent.category.VR" />
      </intent-filter>
      <meta-data android:name="com.oculus.vr.focusaware" android:value="true" />
    </activity>
    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false" />
    <meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only" />
    <meta-data android:name="com.oculus.supportedDevices" android:value="quest|quest2" />
  </application>
  <uses-feature android:name="android.hardware.vr.headtracking" android:version="1" android:required="true" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
</manifest>
```

**Comment by RenderHeadsSte** [comment] 2021-05-12 19:39
If you can send over a full logcat output from a ‘run’ I will be able to see better what is going on.

**Comment by d-d-d-d-d** [comment] 2021-05-12 20:09
Here's this, thanks again. 
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6468795/log.txt)

Re: paths different between Quest / Quest II, I haven't seen that in their [documentation](https://developer.oculus.com/documentation/unity/ps-assets/), which I suppose is not surprising. Do you happen to have the difference handy?

**Comment by RenderHeadsSte** [comment] 2021-05-12 20:23
Thanks for the log...will look over it.

Check out [this](https://forums.oculusvr.com/t5/Oculus-Quest-Development/Quest-2-Local-Storage-Path-changed-Quest1-App-broken/m-p/840167) forum thread for path differences.

**Comment by RenderHeadsSte** [comment] 2021-05-12 20:27
Your log shows that the plugin has not been loaded (line 2018).  This can happen for a few reasons.  Take a look at #728 maybe.  If that doesn't help, if you could post up all of your player settings, I might be able to spot the issue.

**Comment by RenderHeadsSte** [comment] 2021-05-12 22:08
We have a script that sets up the plug-in files metadata as part of the build process, so that isn’t a concern. Not having the files is definitely gonna cause issues.

Have you tried switching to mono to narrow the issue down?

**Comment by d-d-d-d-d** [comment] 2021-05-12 22:52
Ah, yes, it works again when building with Mono. Hopefully Oculus will have clearer guidelines for this before the warning about 64-bit apps being a requirement gains enforcement. 
I'm going to keep investigating the issue, and if you think of anything more I'd love to hear it, but it's been heartening to have your guidance through this process. Again, thank you for all your help.

**Comment by RenderHeadsSte** [comment] 2021-05-12 23:19
Ther is no reason il2cpp should not work. Let’s dig a bit deeper?

can you send a screen grab of your XR (oculus) settings?

**Comment by d-d-d-d-d** [comment] 2021-05-13 07:13
Here's these. For this project I've rolled back Oculus Integration to 25.0, and updated Oculus Tools to 1.57. I'm also not using XR Toolkit / Management, though I'm having the same problem in another project that is. 
XR Settings
![xrsettings](https://user-images.githubusercontent.com/19946735/118091320-dc0a8080-b3f4-11eb-9178-3beac6d9bddf.jpg)
I'm also using the OES path for this one, though in the other project I've tried the non-OES path and it didn't seem to make a difference.

**Comment by RenderHeadsSte** [comment] 2021-05-13 09:56
Could you send over another log using IL2CPP now you have the arm64 plugin files in the correct place?

**Comment by RenderHeadsSte** [comment] 2021-05-13 10:33
Just tested here:

- Our Demo_360Stereo scene
- On a Quest 2
- In Unity 2019.4.20f1 and installing the XR plugin manager (and Oculus)
- Rendering Mode set to 'Multi Pass'
- Added a 'UpdateMultiPassStereo' component, and also a 'Tracked Pose Driver' to the main camera
- Set script backend to IL2CPP
- Set the MediaPlayer to absolute path and loaded /sdcard/Download/
- Ticked custom manifest option and added android:requestLegacyExternalStorage="true" to the file, and removed the commented line so it does not get overwritten on the next build
- Set 'Write Permission' to 'External (SDCard)'

The video plays and everything renders exactly as one would expect.  Maybe you are missing one of the steps here?

**Comment by d-d-d-d-d** [comment] 2021-05-13 11:04
Here's the log for the new IL2CCP build--same deal, no video play. 
[log3.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6472006/log3.txt)
Again, this project isn't using Unity's new(er) XR Plugin framework / Toolkit. 

As for my other project, which does use Unity's new XR suite:
1. I haven't added an UpdateMultiPassStereo component--is this something needed even for monoscopic video?
2. I haven't yet done a build with requestLegacyExternalStorage; am doing it now and will let you know the results.
3. I'm testing on a Quest 1, but based on how recent the problems have been, and that Unity updated Quest 1 to run the same version of Android as Quest 2, I've gotta suspect this is the source of recent pains.

**Comment by d-d-d-d-d** [comment] 2021-05-13 12:05
Hmm, I'm getting a failed Gradle build when I add android:requestLegacyExternalStorage to my manifest in my other project. I'm using the JDK/Android SDK/NDK/Gradle installed with Unity. Tried the manifest posted above, as well as just adding it to the Oculus-generated one, to no avail. Same Minimum/Target Android levels as the first project, same computer....

Here's the most informative output from the console
[gradlebuildfailure.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6472320/gradlebuildfailure.txt)

**Comment by RenderHeadsSte** [comment] 2021-05-13 16:15
> Hmm, I'm getting a failed Gradle build when I add android:requestLegacyExternalStorage to my manifest in my other project. I'm using the JDK/Android SDK/NDK/Gradle installed with Unity. Tried the manifest posted above, as well as just adding it to the Oculus-generated one, to no avail. Same Minimum/Target Android levels as the first project, same computer....
> 
> Here's the most informative output from the console
> [gradlebuildfailure.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6472320/gradlebuildfailure.txt)

What version of the Android SDK are you using?

**Comment by RenderHeadsSte** [comment] 2021-05-13 16:19
> 1. I haven't added an UpdateMultiPassStereo component--is this something needed even for monoscopic video?

No, not required if you are not playing back a stereo video (or more accurately, the material properties are not setting up the shader to render as stereo).

**Comment by RenderHeadsSte** [comment] 2021-05-13 16:21
Do you have a Quest 2 to hand?  I can grab hold a Quest 1 maybe tomorrow to test on.

I will test using the legacy VR now...

**Comment by d-d-d-d-d** [comment] 2021-05-13 17:35
Using what's bundled with Unity 2019.4. Looks like
SDK: android 28
Build tools: 28..0.3

I'm also getting the message "Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0

What's confusing to me is I don't remember setting this up any differently than the first project--it too is using the bundled Android libraries--and the only difference in the manifest and Player Settings and gradle file (when I've clicked to use a custom gradle) is that this project doesn't want me to requestLegacyExternalStorage.

I've got other SDKs installed via Android Studio, but have not tested them yet.

I can snag a Quest II tomorrow if necessary.

**Comment by d-d-d-d-d** [comment] 2021-05-13 17:42
Ah okay, used the Android Studio SDKs and it compiled. Will let you know re: videos what happens.

**Comment by RenderHeadsSte** [comment] 2021-05-13 17:49
Interestingly, I am getting 'black screen' (but have audio playing from the video so I know it is playing back at least) when I use the legacy XR in Unity 2018.4.20f1 on the Quest 2 ...when using Mono!

**Comment by d-d-d-d-d** [comment] 2021-05-13 19:36
So same issue with IL2CCP in app 2. Here's the logcat for that:
[app2log1.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6474691/app2log1.txt)
Going to build with Mono now but not sure I'll be able to test in the next 10 hours. Will let you know when I do.

**Comment by RenderHeadsSte** [comment] 2021-05-13 19:44
Can you check if the il2cpp apk has the file libAVProLocal.so in it? Thst is what the logs are complaining about - I guess it’s missing from the ARM64 folder.

**Comment by d-d-d-d-d** [comment] 2021-05-13 20:15
> Can you check if the il2cpp apk has the file libAVProLocal.so

Ah, so it had none of the AVPro libs. 
![Screenshot 2021-05-14 03 04 08](https://user-images.githubusercontent.com/19946735/118181766-5b826900-b462-11eb-9ce8-4bd041ba11bc.jpg)
Looked again at Unity, and when I was enabling them I'd just select all and tick "Android".
![Screenshot 2021-05-14 03 10 33](https://user-images.githubusercontent.com/19946735/118181714-486f9900-b462-11eb-8063-9e923203c0e3.jpg)
By only selecting one, I got to choose the architecture, and since I was switching to 64-bit... 
![Screenshot 2021-05-14 03 10 16](https://user-images.githubusercontent.com/19946735/118181926-8b317100-b462-11eb-8778-e6d0d8216535.jpg)
Well, I rebuilt and now my new IL2CCP includes the AVPro libraries. Will test.
![Screenshot 2021-05-14 03 14 05](https://user-images.githubusercontent.com/19946735/118181855-781ea100-b462-11eb-94d3-bf0e026a715f.jpg)

**Comment by RenderHeadsSte** [comment] 2021-05-13 20:52
Interesting. But more interesting is that we have a script that, as part of the build process, sets up the meta data for the library files according to what unity is building. Maybe there is an issue in/around that 🤔

**Comment by RenderHeadsSte** [comment] 2021-05-14 09:58
So on the point of our build processing setting up meta files according to the architecture being used...One of our team has questioned whether you have moved the plugins folder (or even the whole AVProVideo folder) ?  This would cause the metafile setting up of plugin files to not work.

**Comment by d-d-d-d-d** [comment] 2021-05-14 13:11
No, everything is where it was imported to--/Assets/AVProVideo/ and /Assets/Plugins/Android/libs/*

Good news is that the mono build is playing videos in the second app. Playback is choppy but I imagine that's a different issue. Will try with an IL2CCP build next.

**Comment by RenderHeadsSte** [comment] 2021-05-14 13:23
> ![Screenshot 2021-05-14 03 10 16](https://user-images.githubusercontent.com/19946735/118181926-8b317100-b462-11eb-8778-e6d0d8216535.jpg)

This screen shot shows things have moved?

**Comment by d-d-d-d-d** [comment] 2021-05-14 13:32
Huh, I definitely didn't manually move anything--I only touched the Android tickbox and the Platform Settings pictured. The path seems to be where the package wants them?
![Screenshot 2021-05-14 20 29 41](https://user-images.githubusercontent.com/19946735/118277798-5d483d00-b4f3-11eb-8f2b-31f4ea23baa3.jpg)

**Comment by RenderHeadsSte** [comment] 2021-05-14 13:38
Ahhhhhhh, this is AVPro v1.x !!!

Yeah, the metafile fixing-up was new in v2.x.

Note to everyone else reading this...this is why we ask for this kind of information in the initial template you fill out for an issue.
(Note to self...always ask what version the dev is using)

So that makes sense then.  Your files are in the right place, but you have to manually setup the arm64 plugin files (due to the backward compatibility v1.x offers in terms of Unity versions.

Throw a log this way if IL2CPP still does not work with the fixed up arm64 files.

**Comment by d-d-d-d-d** [comment] 2021-05-16 08:27
That makes sense--sorry for not specifying!

I'm having a similar issue to what you described using IL2CCP. I get garbled audio and no video. With mono I get both, but it's extremely choppy.

Here's the logcat for the IL2CCP 
[app2il2ccp.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6488885/app2il2ccp.txt)


The videos I'm using are well within supported specs for Oculus Quest (codec, resolution, bitrate). I tried both OES and non-OES path when using Mono but neither made a difference.

**Comment by RenderHeadsSte** [comment] 2021-05-17 13:02
Your log shows you had OES mode enabled.

Can you send over a test project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) so I can be absolutely sure I have the same setup.  I will grab a Quest1 today if you can...

**Comment by d-d-d-d-d** [comment] 2021-05-17 13:13
Will do, might be a little bit for the compress/upload, but I'll send it as soon as it's done

**Comment by RenderHeadsSte** [comment] 2021-05-17 13:18
Awesome, thanks.  Sending it over WeTransfer is always a decent option.

**Comment by RenderHeadsSte** [comment] 2021-05-20 08:35
Yes, received and I hope to look at this today

**Comment by RenderHeadsSte** [comment] 2021-05-20 13:16
I have reproduced your issue here on a Quest2 with the project you sent.  Thoughts so far...

Your video plays back perfectly when I use one of the v1.x Demo scenes.  Full frame rate and perfect audio.

In your project, if you disable the Oculus XR setting 'Low Overhead Mode' then the video renders.  The audio is still choppy, but this is in line with the extremely bad frame rate being achieved during video playback - which can be seen now there are video frames rendering.  As to why the frame rate is so terrible, I cannot say.  But I am pretty confident that it is not due to the playback of the video with AVPro.  I would suggest profiling to see if there is anything obvious.

**Comment by d-d-d-d-d** [comment] 2021-05-20 18:41
That's a huge help. Thanks again. Will post what I find after I get a chance to look at it tomorrow.

While doing this, did you find any difference between IL2CCP and Mono?

**Comment by d-d-d-d-d** [comment] 2021-05-21 13:54
So, the choppiness was a feedback loop of directly updating the video seek slider every frame, which was then OnValueChanged calling a method to update frame position... Yeah, whoops :)

I have gotten it working with the non-OES path, but the OES path is giving me audio but no video. I do have the full/paid version, so that's not the issue. Here's logs from
IL2CCP
[newil2ccp.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6522967/newil2ccp.txt)
and Mono
[eosmono.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6522968/eosmono.txt)
builds of that. Thanks again for your help!

**Comment by d-d-d-d-d** [comment] 2021-05-21 18:56
To confirm, with non-OES path it works as expected with both Mono and IL2CCP.

**Comment by RenderHeadsSte** [comment] 2021-05-24 11:22
Assume you changed your shader to an OES one?

**Comment by d-d-d-d-d** [comment] 2021-05-24 11:53
Everything's the same except for "Low Overhead Mode"--maybe that was the issue? I'll try again in the next couple days; focusing on other projects while Oculus reviews.

**Comment by RenderHeadsSte** [comment] 2021-05-24 12:10
Yeah, what you described is what I get when I enable 'Low Overhead Mode', so I am confident it's just that.  Do let us know, and if all good and you are happy to, please close the issue :)

**Closed** 2021-05-29 16:51 UTC
Labels: Android, not a bug
