### ISSUE TITLE
WebGL iOS video playback 

### ISSUE THREAD

**Issue by ASquareDevs** [RenderHeads/UnityPlugin-AVProVideo#770] opened 2021-05-07 18:17 UTC
So I understand that there's an issue with playing video in WebGL on iOS devices, but just recently there has been a solution found that uses Unity's video player. Is there a way we can get a similar solution to work for AvProVideo?

The solution package can be downloaded here....
https://forum.unity.com/attachments/iosvideo-unitypackage.825305/

The user that found it posted it here as well..
https://forum.unity.com/threads/unity-webgl-video-player-doesnt-play-on-ios-mobile.930420/

It uses a user generated action through an HTML created button that has a callback to the video creation function in Unity when clicked. Just wanted to give you guys a heads up that there is a temporary solution out there to see if you could replicate it using your plugin.
 
 - Unity version: 2021.1.1f1

**Comment by ASquareDevs** [comment] 2021-06-01 17:34
Was there any luck replicating it or were you guys not able to get to this ticket yet?

**Comment by kahnivore** [comment] 2021-06-02 10:56
Hi @ASquareDevs 

We'll get back to you as soon as we've been able to look into this properly. 

Thanks

**Comment by ASquareDevs** [comment] 2021-08-06 20:47
Hey! Our team was wondering if there was any forward progress on this ticket?

**Comment by DerrickBarra** [comment] 2021-09-14 18:11
@kahnivore : Any progress on this? We really want to use AVPro on WebGL since you guys support HLS streaming but we need this bug to be fixed. Please check out the link posted to the repo, it shows the current process for making videos play on iOS WebGL via a javascript button tap.

**Comment by DerrickBarra** [comment] 2021-09-28 11:28
@kahnivore @MorrisRH Hi, any updates on this ticket?

**Comment by kahnivore** [comment] 2021-10-01 13:06
We tried the example you linked but so far without success. Unfortunately we haven't had enough time to look into it further .

Have you had any luck implementing it yourselves?

**Comment by ASquareDevs** [comment] 2021-10-04 16:29
https://drive.google.com/drive/folders/1jctLc8pRU2gO_4nXRT-F_276tlxmAuei?usp=sharing
The above link contains tutorial videos that will help you set up a WebGL build as well as how to upload it to your own personal server. Along with these tutorial videos, there is an example video of it working on our iOS device (iPhone SE 15.0) and a text file for additional instructions.

GitHub Project: 
https://github.com/ASquareDevs/UnityVideoWebglDemo

Here's a working link from the GitHub project
https://brandxr-discovery.s3.amazonaws.com/WebGL/WebGl+Video+Example+for+AvPro/index.html

**Comment by AndrewRH** [comment] 2021-10-04 18:12
Thanks @ASquareDevs  for the nice examples etc - I'm sure it will be very helpful.

I just want to clarify what you want .   It seems like you have a working solution - so what do you want us to do?

I guess you want us to integrate this solution so it's easier to deploy without all of these steps.  We will would have to see if that's possible.  I haven't watched your tutorial videos yet, but if it involves adding an HTML button to click then I'm not sure how we can make a generic way to add a button.....

Thanks,

**Comment by DerrickBarra** [comment] 2021-10-04 19:05
@AndrewRH the issue is that this type of solution, clicking a button in javascript to make a video play on WebGL iOS does not work with AVPro Video, but it does with Unity video player.

**Comment by Chris-RH** [comment] 2024-10-07 08:38
Closing as no longer supporting WebGL.

**Closed by Chris-RH** 2024-10-07 08:38 UTC
Labels: enhancement 🚀, WebGL
