### ISSUE TITLE
HLS (.m3u8) video not rendering on iOS platform

### ISSUE THREAD

**Issue by Levin242** [RenderHeads/UnityPlugin-AVProVideo#1397] opened 2022-12-13 10:24 UTC
**Describe the issue**
HLS (m3u8) video is not rendering in iOS 16. Only video is not getting rendered, audio is playing. The video is rendering in the Unity Editor and in Android.

 - Unity version: 2020.3.12f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVProVideo-v2.6.7-Trial
 - Operating system version: iOS
 - Device model: iPhone 11
 - Video specs (resolution, frame-rate, codec, file size): https://jioembibe.cdn.jio.com/hlsmedia/embibe/29/95191_1003221659_auto.m3u8?__hdnea__=st=1670926066~exp=1671054066~acl=/hlsmedia/embibe/29/95191_1003221659_auto.m3u8~hmac=a11e5154f278963f297a51719bbef202c00e95883e6fce7f44f4d84500b58df0

**To Reproduce**
1. Open Trial Demo project in Unity
2. Open the Demo_MediaPlayer scene
3. Select the MediaPlayer gameObject from scene hierarchy
4. In the Media Playe component inspector change Source/Settings/Media Source to Path.
5. In the Media Playe component inspector change Source/Settings/Absolute Path or URL paste the video url.
6. Add the Demo_MediaPlayer scene to Build setings.
7. Build XCode (Version 14.1 (14B47b) Project.
8. Audio plays but the video does not render.

**Logs**
No error logs.

**Screenshots**
<img width="1728" alt="Screenshot 2022-12-13 at 3 47 10 PM" src="https://user-images.githubusercontent.com/113191505/207291903-d367baf6-be15-47e8-a07d-de17ee53a741.png">
<img width="1728" alt="Screenshot 2022-12-13 at 3 47 36 PM" src="https://user-images.githubusercontent.com/113191505/207291937-2b80f079-847a-4c41-8972-a7ca0c093089.png">

![IMG_227094C62D3B-1](https://user-images.githubusercontent.com/113191505/207299543-8bca74ef-4cdc-45a0-a097-994cd730d46a.jpeg)

**Videos**
(https://jioembibe.cdn.jio.com/hlsmedia/embibe/29/95191_1003221659_auto.m3u8?__hdnea__=st=1670926066~exp=1671054066~acl=/hlsmedia/embibe/29/95191_1003221659_auto.m3u8~hmac=a11e5154f278963f297a51719bbef202c00e95883e6fce7f44f4d84500b58df0)

Tried Test stream: https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8
Initially, it didn't work. Only audio was playing and Video was not rendering.

After adding the below setup, test stream  worked fine,
mediaPlayer.PlatformOptionsIOS.preferredMaximumResolution = OptionsApple.Resolution._1080p;
mediaPlayer.PlatformOptionsIOS.preferredPeakBitRate = 4.0f;
mediaPlayer.PlatformOptionsIOS.preferredPeakBitRateUnits = OptionsApple.BitRateUnits.Mbps;

But, tried the same setting for my video. It didn't work.

**Comment by MorrisRH** [comment] 2022-12-13 11:09
Reproduced. Unfortunately the issue is with how Unity have implemented WebCamTexture on iOS. I'm looking for a work around which should hopefully make it into the next build.

**Comment by MorrisRH** [comment] 2022-12-13 11:24
I'm afraid that this is an issue with iOS 16.0, HLS media with AES-128 encryption will not produce any textures so we're unable to output any video frames for it. This has been fixed in more recent iOS updates. I was able to play back your video in our media player demo with no issue on iOS 16.1.2 running on an iPhone 13 Pro.

**Closed by MorrisRH** 2022-12-13 11:24 UTC

**Comment by Levin242** [comment] 2022-12-13 11:26
@MorrisRH Thanks for the reply. Will check in the latest iOS version.
