### ISSUE TITLE
We are getting issue after importing Avpro in are game

### ISSUE THREAD

**Issue by player70798** [RenderHeads/UnityPlugin-AVProVideo#1284] opened 2022-09-05 13:39 UTC
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
![Screenshot 2022-09-02 162403](https://user-images.githubusercontent.com/112877558/188462562-66347dac-bc8d-40b1-92df-599576b3270a.png)

3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2022-09-05 13:58
Can you please fill out all the details asked for in the template so we can try to reproduce this:
**Describe the issue**
A clear and concise description of what the issue is.
**Your Setup (please complete the following information):**
Unity version:
AVPro Video version (number and edition (trial/core/ultra/enterprise)):
Operating system version:
Device model:
Video specs (resolution, frame-rate, codec, file size):
**To Reproduce**
1.
2.
3.
**Logs**
If applicable, add error logs to help explain your problem.
**Screenshots**
If applicable, add screenshots to help explain your problem.
**Videos**
If applicable, add a copy of your video or the URL
**Scripts**
If applicable, add a copy of any custom scripts used.
**Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE**
Instead email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment] 2022-09-05 14:00
Is this a duplicate of: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1182 ?

**Comment by player70798** [comment] 2022-09-05 14:21
No this is not a duplicate of #1182. 
I am sending the full information.

**Closed** 2022-09-06 09:46 UTC
Labels: Android, need more info 🤷
