### ISSUE TITLE
stream video error

### ISSUE THREAD

**Issue by monaalaa** [RenderHeads/UnityPlugin-AVProVideo#276] opened 2020-02-23 11:06 UTC
I got this error when i upgrade from trail version to android version while streaming video 
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

this is the video am streaming 
https://s3-us-west-2.amazonaws.com/upward-vr/demo/good-3840-13-20db.mp4

**Comment by AndrewRH** [comment] 2020-02-23 11:35
Thanks, that sounds very strange..  Could you try reimporting the package again?

I can't think of any reason why this wouldn't work...

Do you know what version of AVPro Video you upgraded from when upgrading from the trial version?

**Comment by monaalaa** [comment] 2020-02-23 11:53
i get the last version in AssetStore

**Comment by RenderHeadsSte** [comment] 2020-02-28 18:17
What Android device are you playing this back on?

**Comment by RenderHeadsSte** [comment] 2020-02-28 18:21
I have tested this on an Oculus Quest here using the provided demo : 08_Demo_360SphereVideo

I can confirm it plays back exactly as it should do.

**Comment by AndrewRH** [comment] 2020-03-02 15:39
@monaalaa check your unity player settings - make sure the Android settings allow network activity...

Since we can't replicate the issue, and without any other feedback we will close this ticket soon

**Comment by RenderHeadsSte** [comment] 2020-03-10 15:42
We shall be closing this bug shortly due to lack of response.

**Closed** 2020-03-13 17:35 UTC
Labels: Android
