### ISSUE TITLE
Crash in Android phone with Exoplayer

### ISSUE THREAD

**Issue by kilelr** [RenderHeads/UnityPlugin-AVProVideo#28] opened 2019-03-10 10:06 UTC
--------- beginning of crash
03-10 17:08:07.771 4322-4322/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fmssb.csi, PID: 4322
    java.util.NoSuchElementException
        at java.util.ArrayDeque.removeFirst(ArrayDeque.java:264)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:682)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Crashed happen when start to play video

 - Unity version: 2018.3.6f1
 - AVPro Video version: 1.9.12
 - Operating system version: android 8.1.0
 - Device model: Galaxy Tab s4 
 - Video specs : 1280 560 , 29 frame , mp4 , 13 mb

**Comment by kilelr** [comment] 2019-03-13 10:54
any update?

**Comment by AndrewRH** [comment] 2019-05-31 11:23
We have some leads now, but are still working on a fix.

Related issue from another user ([#WkLVn] - Native crash in exo player):

We are experiencing the following crash on Android. It's happening on Android 7/8/9 and on various devices Samsung/Motorola.

Crash:
Caused by java.lang.IndexOutOfBoundsException
       at com.google.android.exoplayer2.Timeline$1.getPeriod(Timeline.java:516)
       at com.google.android.exoplayer2.Timeline.getPeriod(Timeline.java:749)
       at com.google.android.exoplayer2.ExoPlayerImpl.playbackInfoPositionUsToWindowPositionMs(ExoPlayerImpl.java:689)
       at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentPosition(ExoPlayerImpl.java:474)
       at com.google.android.exoplayer2.ExoPlayerImpl.getContentPosition(ExoPlayerImpl.java:529)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:575)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:602)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:612)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:425)
       at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:746)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by RenderHeadsSte** [comment] 2019-06-14 14:58
We have just released Version 1.9.17, which contains quite a few fixes in the ExoPlayer API path.  Maybe you could grab this version and check to see if the problem you are seeing has been addressed?

**Comment by AndrewRH** [comment] 2019-06-19 12:08
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  If you're still having this issue with the new version please do let us know.

Thanks,

**Comment by AndrewRH** [comment] 2019-06-26 13:27
Closing this issue - presumed fixed

**Closed by AndrewRH** 2019-06-26 13:27 UTC
Labels: Android, HIGH, bug

**Comment by lovelittle7** [comment] 2019-08-23 14:39
We use 1.9.12 version have the same crash : Caused by java.lang.IndexOutOfBoundsException on Android. May I ask if there is still this issue with the new version or is there some way to avoid it with old version? thanks
