### ISSUE TITLE
Green Video

### ISSUE THREAD

**Issue by aholla** [RenderHeads/UnityPlugin-AVProVideo#837] opened 2021-06-28 13:07 UTC
**Green Video when playing back on IOS and on Mac A1 Chips**
A clear and concise description of what the issue is.

We have had reports of the videos having a green tint on occasions. Its doesn't seems to be all the time.

**Comment by kahnivore** [comment] 2021-06-28 13:22
HI @aholla 

Can you provide more information/context please?

Which version of AVPro Video are you using? 

Is this happening on specific videos?

**Comment by aholla** [comment] 2021-06-28 13:55
Hi, not really. Its been reported by various users of our live app.

Today i saw it when testing in the editor which is what prompted me to write to you. It is no longer happening in the editor...

The videos are streamed via Vimeo and HLS.

The AVPro version is 1.11.7

THanks

**Comment by kahnivore** [comment] 2021-06-29 07:59
We'll need a way to test/reproduce this. Can you send a project file to unitysupport@renderheads.com? And perhaps a screenvid of the behaviour?

**Comment by aholla** [comment] 2021-06-29 08:33
I will try and get a video reply of this happening and will email it when i
see it.

Thanks.

**Comment by adamhbz** [comment] 2021-07-09 12:44
I have sent a video of the issue to the email above. The project is too big to send but I can help if you have any specific questions.

**Comment by MorrisRH** [comment] 2021-07-09 14:12
Thanks for sending on the video of the issue happening.
A few questions:
- What components are you using? (e.g. DisplayUGUI, ApplyToMesh, etc.)
- How is the media player configured, specifically the platform settings?
- Are you using our shaders or have you written your own?
- Are you able to share the URL's of the videos you're playing back (send them to unitysupport@renderheads.com)
- Have you seen this when using one of our demo scenes?
- What version of Unity are you using?

**Comment by kahnivore** [comment] 2021-07-23 17:06
Any word on the above questions @aholla ?

**Comment by aholla** [comment] 2021-07-24 18:30
No, not yet.

I need time to go through it all.

**Comment by kahnivore** [comment] 2021-08-11 09:41
Closing for now as we could not reproduce and haven't heard back. Feel free to reopen if the issue persists.

**Comment by aholla** [comment] 2021-11-02 07:01
I'm still waiting to hear back.

**Comment by MorrisRH** [comment] 2021-11-02 09:08
This one does have me somewhat baffled. I am unable to reproduce it and you're the only person to have ever reported seeing it

 I can think of only two reasons as to why you would see a green video:
1. Some render state is being persisted that is resulting in only the green channel being written to the frame buffer, this is very possible with the OpenGL renderer but I would think quite unlikely with the Metal renderer. If you were using the YCbCr mode for the texture (iOS platform specific property) with a shader that didn't support YCbCr then I would expect to see a red texture being rendered as the Y component is in the red channel only. If you're using the BGRA texture mode then there is nothing from our side that would lead to a green video, with version 1 of AVPro Video we pass the decoded frames straight through to unity with no internal processing.
2. For reasons unknown Vimeo is streaming a green channel only video to your app.

Apologies for not being more helpful, but without a reproducible instance I really have no way to resolve this.

**Comment by MorrisRH** [comment] 2021-11-02 09:10
I've just noticed this line in the code you posted:
```csharp
                case MediaPlayerEvent.EventType.FirstFrameReady:
                    videoDisplayUGui.color = Color.green;
```
If you never get a resolution changed message after that, the green colour would persist.

**Comment by adamhbz** [comment] 2021-11-02 13:35
Oh wow, yeah that will be it! Thanks for your eagle eyes! You can close this as I assume its related to that ****

**Closed** 2021-11-02 15:15 UTC
Labels: iOS, macOS, Version 1.x
