### ISSUE TITLE
Black flickering during play

### ISSUE THREAD

**Issue by Myrothas** [RenderHeads/UnityPlugin-AVProVideo#1700] opened 2023-11-28 00:49 UTC
I play Videos, i get flicker as seen in video.

 - Unity version: Recent VRChat
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): No idea.
 - Operating system version: Win 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 4080

**To Reproduce**
1. Watch a movie
2. Get flickers

Tried different nVidia Versions, different Virtual Desktop Codecs - closed everything running the the background. No change. Only flicker.

**Comment by Myrothas** [comment] 2023-11-28 00:49
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/87095612/3459ae83-84a1-4fc4-97a4-bd9210855bb8

**Comment by Chris-RH** [comment] 2023-11-28 09:11
1. Have you gone to VRChat support about this?
2. Has a previous version of VRChat worked?
3. Are you playing it on Windows or are you using a headset? If a headset, which one?
4. What GPU?
5. What specs video have you tested? resolution, codec, FPS, bitrate?

**Comment by Myrothas** [comment] 2023-11-28 10:55
1. No, but i asked the world creator and he sent me here.
2. I think it was working prior yes.
3. I tried on Flat and VR. Not on Standalone, might try this next.
4. As mentionened, im on a 4080.
5. I can not influence that, as im just a content consumer - not a dev/world creator.

Flickering happens on Flat and VR. Will try Standalone next.

**Comment by Myrothas** [comment] 2023-11-28 12:44
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/87095612/94d1990d-e00a-43cc-80ee-9fbeaeb03d69)

I do not have many options in this player. Nothing about API, res, bitrate and such. It is a built in player, but i guess this aint an issue you can do much about. I can only choose AVPro1080p, as you can see. :x

**Comment by techanon** [comment] 2023-12-28 11:03
This issue has been brought up in the VRChat feedback forum a few times.  
The issue has been anecdotally observed by many users over the past few months with different GPUs (both AMD and NVIDIA observed) across multiple different videoplayer tools that rely on AVPro.  
The issue has been observed in the most raw use of AVPro as possible (no special shader shenanigans, just raw material draw from AVPro).  

My observations from [this VRChat feedback post](https://feedback.vrchat.com/open-beta/p/1370avpro-screens-black-frames) (requires VRC account login to view full post) is:

> The black frame flickering issue seems to be an artifact of AVPro when VRChat is not stably generating frames to meet the expected FPS settings.
Here is my observation of what happens when I change the FPS settings on my 75hz monitor using the world posted in the comment from 2 days ago. https://streamable.com/ycwvu1
> 
> A temporary mitigation I found, for desktop at least, is to cap the framerate to the refresh rate (or just use vsync mode which does that dynamically) to try to stabilize the framerate. In VR, you'll need to decrease your render resolution settings or adjust some other performance settings to alleviate the issue for the time being.

I'm curious to the amount of affect that #1637 has in relation to this erroneous behaviour.

The video used in the streamable recording above was a youtube video at the standard 720p 30fps h264/aac that youtube DL provides (combined audio + video link).

VRChat uses MediaFoundation API and 2.8.5 (as of posting this).
We cannot modify that from the userland side of things.

@Chris-RH Let me know if you need more digging for info and I'll get what I can (for context, I made the video player tool referenced above).

**Comment by Myrothas** [comment] 2023-12-28 11:05
Oh well, i fixed it by adding --disable-hw-video-decoding to startup options.
This fixed it for everyone i mentioned this solution.

**Comment by techanon** [comment] 2023-12-28 11:07
Interesting. Noted.

**Comment by techanon** [comment] 2023-12-28 14:54
I did some further testing and was able to reproduce the issue described in #1637.
The reason it's reported as "black frames" is because most video shaders used in VRChat are strictly opaque, so alpha 0 gets drawn as black instead. In the below video I used a transparent shader to verify the issue and yes it is the invisible frames problem.

**Info**
GPU used: RTX3060 (though doesn't really matter as it happens with various other GPUs as mentioned before)
Proof video: https://streamable.com/fqrcg7
Test world used: https://vrchat.com/home/world/wrld_88f8dda9-2d0c-4506-af7c-954831897dad
Shader used for test: `Unlit/Transparent` with a green quad behind the screen
AVPro version: 2.8.5f1-ultra (VRChat provided)

**Comment by Chris-RH** [comment] 2024-03-25 12:21
This should be fixed in AVPro Video version 3.0.0.  The trial version is available [here ](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases)for testing.  Please let us know if the issue is not fixed in this version.

**Comment by techanon** [comment] 2024-04-01 16:03
I have confirmed it does appear to resolve the flicker issue.
https://streamable.com/l6vz4h recording of 2.8.5 and 3.0.0 within playmode testing of a vrchat scene.
(Had to repro with a new scene as I lost the test scene I used previously.)

**Closed** 2024-04-02 07:43 UTC
