### ISSUE TITLE
Vulkan support 

### ISSUE THREAD

**Issue by wyb314** [RenderHeads/UnityPlugin-AVProVideo#809] opened 2021-06-03 02:20 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kahnivore** [comment] 2021-06-03 11:13
Hi @wyb314 

It's on our roadmap but we unfortunately cannot provide a timeframe for this currently. 

Thanks.

**Comment by ys4kw** [comment] 2021-06-07 03:12
I'm waiting too.
A lot of Android support vulkan and performance is better than other graphic api.

I have replaced to v2 from v1 for this thing.

Which problem makes it difficult to implement?
Can we use the api in near future?

**Comment by kahnivore** [comment] 2021-06-07 15:05
Hi @ys4kw 

We're a small team and therefore need to prioritise the features that have the most requests. We haven't had that many requests for Vulkan and are not sure it's going to make much of a difference to performance. It's still on the roadmap but is unlikely to be implemented in the near future.

**Comment by whitecostume** [comment] 2021-06-28 15:37
If  don't support Vulkan, it will affect our project to use Vulkan

**Comment by 740919820** [comment] 2021-10-11 04:35
我们项目同样使用了Vulkan来增强渲染，但是就不能使用AVProVideo，目前正在寻找替代方案。如果能尽快支持Vulkan就更好了

**Comment by jstarrdewar** [comment] 2021-11-09 17:33
+1 for Vulkan. We are ready to move to Vulkan now for the gameplay portion of our application. Obviously we don't expect to see much benefit in the video playback portion of the experience, but we are anticipating very big improvements in the rest of the application, and unfortunately switching is an all-or-nothing proposition as far as I know.

**Comment by khindemit** [comment] 2021-11-10 17:30
+1 for Vulkan. As mentioned previously, Vulkan affects the overall performance of the app. We can't use this plugin until the support is there.

**Comment by khindemit** [comment] 2021-11-10 17:34
> Hi @ys4kw
> 
> We're a small team and therefore need to prioritise the features that have the most requests. We haven't had that many requests for Vulkan and are not sure it's going to make much of a difference to performance. It's still on the roadmap but is unlikely to be implemented in the near future.

Can I maybe help with implementing the Vulkan support? If you are interested in any help, please drop me an email: k.hindemith@gmail.com

**Comment by gtk2k-2** [comment] 2021-12-30 12:10
Please support Vulkan.
As others have said, I'd like to switch to Vulkan to improve overall game performance, but since AVProVideo doesn't support it, I'm currently building with Vulkan with the video player feature removed.

**Comment by LostSenseT-T** [comment] 2022-01-17 10:48
One more for Vulkan. It is not possible to use VFXGraph with AVpro on Android (Oculus Quest 2) as VFXGraph requires Vulkan.

**Comment by DCowling** [comment] 2022-03-24 15:33
+1 for Vulkan, AVPro support here is what gates our transition to this API for Quest titles currently using OpenGL ES.

**Comment by AvinashChanga** [comment] 2022-04-15 12:02
+1 for Vulkan, echoing the above. AVPro is very useful for Quest, and since Oculus has now officially supported Vulkan for about 2 years, AVPro is now a plugin holding that holds certain projects back, requiring us to look for other solutions. (While the preference would be to keep using AVPro.)

**Comment by MrT3D** [comment] 2022-06-30 19:01
+1 Vulkan

Most projects on Quest will be Vulkan. If there is not Vulkan support, we will have to choose between no AVProVideo or no VFX. AVProVideo will likely lose that battle.

**Comment by khindemit** [comment] 2022-07-01 08:18
In our project we use currently Unity Video Player. For playing videos from Firebase Storage Https Urls it works pretty good. It supports Vulkan API. But if you decide to use it, implement it with a wrapper class, to have some space to implement small tweaks to the video playback if you experience bugs or missing functionality.

**Comment by Feynmen** [comment] 2022-07-29 14:50
+ 1 for Vulkan. We can't switch to the Vulkan API due this plugin, but we need the functionality of the plugin too

**Comment by WikkidEdd** [comment] 2022-08-19 12:10
+1 For vulkan

**Comment by Chris-RH** [comment] 2022-08-19 12:17
Thank you for your interest. It is very helpful to see which future
enhancements are most popular.  Vulkan support is in the roadmap for the
future, but no dates as of yet.

**Comment by wonkee-kim** [comment] 2022-09-13 16:30
+1 for Vulkan. Do you have any chance to priotize this? It's 2022 and Vulkan is necessary for performance.

**Comment by Chris-RH** [comment] 2022-09-13 16:51
Thank you @wonkee-kim. It is on the to-do list :)

**Comment by spotd** [comment] 2022-09-30 07:07
+1 for Vulkan. Hit a brick wall on exhibit install when it turns out blending (backstage / brainsalt) requires Vulkan to work. I now have to strip out the video player in all code! Its an expensive product and should support this level of install

**Comment by Chris-RH** [comment] 2022-09-30 08:27
Thank you for your interest @spotd. It is an enhancement that is popular, so we are looking forward to adding it in the future.

**Comment by dan-geniusx** [comment] 2022-10-21 18:35
+1 major Quest 2 optimizations like Asynchronous Space Warp 2.0 only support Vulkan.

**Comment by ngz82** [comment] 2022-10-25 14:57
+1 for Vulkan support. It would be great to get a bit more clarity on when this might become available.

**Comment by TORISOUP** [comment] 2022-10-27 07:31
+1

**Comment by MrT3D** [comment] 2022-10-28 01:20
+1  Vulkan. We require Vulkan + video for Quest dev (as do most devs targeting the Quest).

**Comment by WikkidEdd** [comment] 2023-01-05 20:09
Happy New Year! 

Is there any update on the roadmap for this?

As someone else already mentioned, the desire for this isn't about gains in AVPro Video's performance it's about the rest of the app. For us compatibility is the more important factor, we have other features we need that only support Vulkan and we're blocked from rolling out those features until we can find a solution for video playback on Vulkan. It's not a good situation to be in.

If you could give us _any_ kind of estimate  (3, 6 or 12 months?) It would help us lot in planning our way forward, we don't want to spend time working out another solution only to find you release Vulkan support in 3 months time for example.

AV Pro plugins have been our go-to for many years. They are by far the most robust and performant plugins on the asset store. Even supporting ARM64 UWP for HoloLens 2 which is super niche, it's surprising that Vulkan for Android/Quest 2 hasn't received the same love.

**Comment by Chris-RH** [comment] 2023-01-06 13:13
We recently added Vulkan support to our other asset AVPro Movie Capture at the end of November last year, so we have a bit of any of what we are getting into.  
We hope to start putting some code together to enable Vulkan support for AVPro Video soon and then a cycle of in-house testing and tweaking will start.   
This is a major update that we are all very keen to get out.  However, at this stage of development, we don't like to throw dates out and potentially have to disappoint people if the product is not sufficiently ready for release.

**Comment by DmitrySwearl** [comment] 2023-01-30 13:13
+1 Vulkan. We will be waiting ur updates soon. Is it possible to let us know when you have an understanding of the approximate release date (month)

**Comment by Chris-RH** [comment] 2023-01-30 13:43
As mentioned previously, I can't give out an exact month I'm afraid.  Its unlikely to happen in the next few months as the team are working on some external projects.

**Comment by HannaGurwitzTT** [comment] 2023-03-05 11:02
+1 Vulkan
A different plugin in our application requires vulkan support, thus making it incompatible with AVPro.

**Comment by jg33** [comment] 2023-03-15 00:01
+1 from me as well! 
It would be essential for a project we're working on. 

Thanks- great work!

**Comment by MrT3D** [comment] 2023-03-22 21:54
Any news?

**Comment by Chris-RH** [comment] 2023-03-23 09:47
It is being worked on.

**Comment by whitecostume** [comment] 2023-04-01 09:35
come on

**Comment by syshex** [comment] 2023-07-13 19:44
Any update on this?

**Comment by Chris-RH** [comment] 2023-07-13 19:55
We are working on it :)

**Comment by syshex** [comment] 2023-07-13 20:44
I get it, I read the thread.  But is it a "this year" or in a couple of years kind of deal?  I understand not wanting to state a date, but no idea of timeframe makes it impossible for others to make decisions.

**Comment by Chris-RH** [comment] 2023-07-14 06:44
We are aiming for Q4 this year

**Comment by Ste-RH** [comment] 2023-07-20 11:35
As we have been quite quiet regarding Vulkan support, I can today announce that Android Vulkan support will 100% be arriving with AVPro Video version 3.0. We very much hope to release this major version before the end of the year.

**Comment by whitecostume** [comment] 2023-08-04 02:22
amazing! thank you

**Comment by MrT3D** [comment] 2023-10-05 00:41
Thanks!

**Comment by syshex** [comment] 2023-11-23 09:59
> As we have been quite quiet regarding Vulkan support, I can today announce that Android Vulkan support will 100% be arriving with AVPro Video version 3.0. We very much hope to release this major version before the end of the year.

@Ste-RH @Chris-RH 

How is this going? Are we still on track for Q4? Can we have a date?

**Comment by Chris-RH** [comment] 2024-01-11 07:50
Hi,

We're a very small team and it will be out when it is ready.

**Comment by BadZhang** [comment] 2024-01-20 08:59
im waiting :)

**Comment by mandelbox** [comment] 2024-01-23 14:29
Also very interested in this.

**Comment by DmitrySwearl** [comment] 2024-01-24 09:17
Waiting as well :)

**Comment by cieraej** [comment] 2024-02-21 16:09
hi! Any updates when Vulkan will be supported with Av Pro? Thanks :)

**Comment by Chris-RH** [comment] 2024-02-21 17:14
Duplicate of https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/59

**Closed by Chris-RH** 2024-02-21 17:14 UTC
Labels: duplicate, enhancement 🚀, Android, Version 2.x
