### ISSUE TITLE
SEGV_ACCERR ios crashes happened lots when we upgraded to 1.10.0

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#182] opened 2019-09-20 08:39 UTC
**Describe the bug**
SEGV_ACCERR ios crashes happened lots when we upgraded AVPro to 1.10.0 .

**The crash stacks ：**

0 libobjc.A.dylib | object_isClass + 4
-- | --
1 Foundation | -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 328
2 Foundation | -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
3 Foundation | __NSSetBoolValueAndNotify + 272
4 AVFoundation | -[AVPlayerItem _updateVideoSuppressionOnFigPlaybackItem:basedOnOutputs:] + 64
5 AVFoundation | ___58-[AVPlayerItem(AVPlayerItemOutputs) _evaluateVideoOutputs]_block_invoke + 124
6 libdispatch.dylib | __dispatch_call_block_and_release + 24
7 libdispatch.dylib | __dispatch_client_callout + 16
8 libdispatch.dylib | __dispatch_lane_serial_drain$VARIANT$armv81 + 548
9 libdispatch.dylib | __dispatch_lane_invoke$VARIANT$armv81 + 468
10 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$armv81 + 744
11 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
12 CoreFoundation | ___CFRunLoopRun + 1964
13 CoreFoundation | CFRunLoopRunSpecific + 436
14 GraphicsServices | GSEventRunModal + 96
15 UIKitCore | UIApplicationMain + 212
16 gameapp | main (main.mm:33)
17 libdyld.dylib | _start + 4

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.
 - AVPro Video version: 1.10.0
 - Operating system version: iOS
 - Device model: iOS 12
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment] 2019-09-20 11:08
a few questions to help us solve the issue:

1. Do you know which version you upgraded from?
2. Could you tell us how you're using the plugin - how many videos are you playing, which resolution+framerate+codecs they're using?   And are your videos local files, streaming MP4, streaming HLS?
3. How often is "lots"?
4. Is your application using a lot of memory/system resources?
5. Are you able to replicate this using just our demo scenes?

Thanks,

**Comment by defchen** [comment] 2019-09-20 12:20
> a few questions to help us solve the issue:
> 
> 1. Do you know which version you upgraded from?
> 2. Could you tell us how you're using the plugin - how many videos are you playing, which resolution+framerate+codecs they're using?   And are your videos local files, streaming MP4, streaming HLS?
> 3. How often is "lots"?
> 4. Is your application using a lot of memory/system resources?
> 5. Are you able to replicate this using just our demo scenes?
> 
> Thanks,

1. We upgraded from ver 1.7.3,  this ios crash had never been happened with ver 1.7.3
2. The number of videos playing at same time is 2-3. And the resolution is little than 1500x720, framerate is 24 with H264. baseline profile. Yes, they are local files we played.
3. "lots" means many different users reported the crash. We had huge users count.
4. The memory of device had been left enough. For example, the device runtime data of one of these users is that device was IPhone8Plus with FlashMem left 1.99 GB ( 68.24% ) and StorageMem left 196.65 GB ( 82.49% ). So , I think it is not about the system resources lack.
5.Sorry, we cannot replicate at this moment.

**Comment by MorrisRH** [comment] 2019-09-20 13:13
Do you know what is happening when the crash occurs? For instance, are you creating a new player or closing an old one, starting playback?

Do you reuse the player instances or create a new one each time?

**Comment by MorrisRH** [comment] 2019-09-23 14:18
I believe I've found the cause. A fix will be present in the next release.
Let us know if it resolves the issue you are seeing.

**Comment by freerangegreg** [comment] 2019-09-27 22:07
Hi, we're getting potentially the same issue on il2cpp osx builds. Any idea on how we could mitigate the issue or avoid triggering it until you release a new build?

Thread 0 Crashed:: tid_307  Dispatch queue: com.apple.avplayeritem.figplaybackitem
0   libsystem_kernel.dylib        	0x00007fff5f21c2c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5f2d7bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5f1866a6 abort + 127
3   UnityPlayer.dylib             	0x0000000107b4c8c4 HandleSignal(int, __siginfo*, void*) + 36
4   libmonobdwgc-2.0.dylib        	0x0000000113611331 mono_chain_signal + 79
5   libmonobdwgc-2.0.dylib        	0x00000001134e2dcf mono_sigsegv_signal_handler + 414
6   libsystem_platform.dylib      	0x00007fff5f2ccb5d _sigtramp + 29
7   ???                           	000000000000000000 0 + 0
8   com.apple.Foundation          	0x00007fff353ede68 KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED + 57
9   com.apple.Foundation          	0x00007fff353edbbf -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 355
10  com.apple.Foundation          	0x00007fff353eda3e -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 68
11  com.apple.Foundation          	0x00007fff3546c20a _NSSetCharValueAndNotify + 253
12  com.apple.avfoundation        	0x00007fff2f214f3d -[AVPlayerItem _updateVideoSuppressionOnFigPlaybackItem:basedOnOutputs:] + 56
13  com.apple.avfoundation        	0x00007fff2f218462 __58-[AVPlayerItem(AVPlayerItemOutputs) _evaluateVideoOutputs]_block_invoke + 117
14  libdispatch.dylib             	0x00007fff5f0935f8 _dispatch_call_block_and_release + 12
15  libdispatch.dylib             	0x00007fff5f09463d _dispatch_client_callout + 8
16  libdispatch.dylib             	0x00007fff5f09a8e0 _dispatch_lane_serial_drain + 602
17  libdispatch.dylib             	0x00007fff5f09b3c6 _dispatch_lane_invoke + 433
18  libdispatch.dylib             	0x00007fff5f09f54b _dispatch_main_queue_callback_4CF + 813
19  com.apple.CoreFoundation      	0x00007fff3318d2d7 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
20  com.apple.CoreFoundation      	0x00007fff3318ca01 __CFRunLoopRun + 2289
21  com.apple.CoreFoundation      	0x00007fff3318bebe CFRunLoopRunSpecific + 455
22  com.apple.HIToolbox           	0x00007fff323eb1ab RunCurrentEventLoopInMode + 292
23  com.apple.HIToolbox           	0x00007fff323eaee5 ReceiveNextEventCommon + 603
24  com.apple.HIToolbox           	0x00007fff323eac76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
25  com.apple.AppKit              	0x00007fff3078379d _DPSNextEvent + 1135
26  com.apple.AppKit              	0x00007fff3078248b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
27  com.apple.AppKit              	0x00007fff3077c5a8 -[NSApplication run] + 699
28  com.apple.AppKit              	0x00007fff3076bae8 NSApplicationMain + 777
29  UnityPlayer.dylib             	0x00000001080d7242 PlayerMain(int, char const**) + 1874
30  libdyld.dylib                 	0x00007fff5f0e13d5 start + 1

**Comment by freerangegreg** [comment] 2019-09-30 18:27
@MorrisRH Do you think this is the same issue? Should I spin it out into a new bug?

**Comment by freerangegreg** [comment] 2019-10-01 16:28
Thanks @MorrisRH

**Comment by MorrisRH** [comment] 2019-10-03 11:44
AVPro Video 1.10.1 is now available and includes our fix for this issue. Would be great if you could let us know if this has resolved the problem for you.

**Comment by freerangegreg** [comment] 2019-10-04 17:27
Yep. No more crashing.

**Closed** 2019-10-09 13:05 UTC
Labels: Bug, Fixed, iOS

**Comment by davidohyer** [comment] 2019-11-06 17:43
Could you please outline what the actual issue and fix was? I'm running into the same exact issue on a completely unrelated project. Thanks.

**Comment by MorrisRH** [comment] 2019-11-06 18:02
The crash was caused by a KVO observer being deallocated without first being removed from the object it was observing. In our case this was the result of a race-condition between the open and dispose calls.
Enabling zombie objects in diagnostics helped to track down the object that had been deallocated.
