### ISSUE TITLE
Monoscopic 360° Videos on Quest using OES & Multiview = Right Eye skewed

### ISSUE THREAD

**Issue by SimonP01** [RenderHeads/UnityPlugin-AVProVideo#1342] opened 2022-10-19 15:48 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Hi, 

I am trying to play a monoscopic 360° video on my Quest using OES rendering.
Everything works fine except, I get a skewed image on the right eye if I use "Multiview" rendering for the Quest.
Not using OES or rendering in Multi Pass mode everything works as advertised.

In your documentation you write OES does not support Stereo in singlepass rendering. Do you mean stereo videos or stereo rendering in general (e.g. VR)?

I am asking because I did the same for the Pico Neo which also uses Singlepass rendering and It worked flawless using OES.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.11 (Built in Renderer)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.5 Android Core
 - Operating system version: Win 10
 - Device model: Quest 1
 - Video specs (resolution, frame-rate, codec, file size): 4096x2048 @ 60fps, h.265, 722mb

**To Reproduce**
1. Create Project
2. Set up OES for Quest (Apply to mesh)
3. No joy

**Videos**

https://user-images.githubusercontent.com/12813068/196740733-55d41945-63c2-43d1-8086-1c47a63d6f12.mp4

**Images**
![AvPro_Settings1](https://user-images.githubusercontent.com/12813068/196741208-d34a2082-ab89-4384-acfd-6b75b271e48e.jpg)

![AvPro_Settings2](https://user-images.githubusercontent.com/12813068/196741239-3bc2d6a4-c087-4570-9b62-a75d27891833.jpg)

**Comment by Chris-RH** [comment] 2022-10-20 14:16
On Oculus devices the only supported options these days are Multi Pass and Multiview.
Are you using this component:
https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html

**Comment by SimonP01** [comment] 2022-10-20 16:22
Strange indeed. It seems I have exactly the same issue as the OP of the thread you mentioned.
I'll investigate and report back.

**Comment by Ste-RH** [comment] 2022-10-20 16:35
If you email over a project that reproduces what you are seeing, I will happily take a look.  Send it to unitysupport@renderheads.com

**Comment by SimonP01** [comment] 2022-10-21 09:07
Hi, I tried again this morning with a vanilla project. Unity 2021.3.11f1. All set up according to Metas developer page.
Then I Used your Demo_360 Scene:

1. Exchanged the 360 stereo movie for your mono variant
2. Changed settings and shaders to OES
3. Set Oculus Rendering to Multiview
4. Added the XRRig and Build
5. No Profit :(

![2022-10-21T07-13-53 257Z](https://user-images.githubusercontent.com/12813068/197158157-ec67a6ad-2e64-4b9e-b2f8-c9eef2a99369.png)

I have sent the complete project (including build) to you. The Scene I used is your own "Demo_360Stereo"

I'll continue Testing on my end as well but It'd be awesome If you could show me the path to glory. 

Cheers

**Comment by Ste-RH** [comment] 2022-10-21 10:37
Downloaded and ran your project (with absolutely no changes) on a Quest 2.  This is the output (captured with Android Studio).

![Screenshot_20221021_113504](https://user-images.githubusercontent.com/46531149/197176780-a0b4e6a8-e2fc-4723-b8df-26ccc94ed6f1.png)

Cannot see anything wrong.  Am I missing something?

**Comment by SimonP01** [comment] 2022-10-21 11:07
Hi, Thanks for your swift reply. 
This is indeed very strange. Maybe it's indeed Quest 1 Vs Quest 2? We unfortunately do not have one (yet).
The image above has been captured with Oculus developer hub.

**Comment by Ste-RH** [comment] 2022-10-21 11:16
I have a quest 1 in hand.  Confirmed.  Seeing it here:

![image](https://user-images.githubusercontent.com/46531149/197183606-cf080ab4-7d50-4c84-a231-472871c6271d.png)

So it is Quest 1 only.  But why?!

**Comment by Ste-RH** [comment] 2022-10-21 11:19
Whatever it is, it appears to be OES only.  I changed to none-OES and do not see the problem.

**Comment by SimonP01** [comment] 2022-10-21 11:23
Yes, I concur. Non OES or switching to MultiPass with OES fixes it.
I also tried:

- turning debug build off/on
- Changing the used OVR Plugin (Oculus -> Tools -> OVR Utilities Plugin)
- Changing API compatibility
- Changing Target API Level Highest/29
- Turning off all settings in the OculusXR Plugin except low overhead mode

**Comment by Ste-RH** [comment] 2022-10-21 11:36
If  you close one eye and rotate your view left/right/left/right/etc...the left eye looks fine, the right is all a bit oddly projected.

**Comment by Ste-RH** [comment] 2022-10-21 13:44
Ahh, nailed it.

The odd offset I was seeing is a none zero position value on the XRRig gameobject.  If I make it zero and use the attached shader, all looks fixed.

[AVProVideo-VR-InsideSphere-AndroidOES.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9839469/AVProVideo-VR-InsideSphere-AndroidOES.zip)

I will apply this fix through all our OES shaders and that will be in the next release.

**Comment by Ste-RH** [comment] 2022-10-21 13:47
Small edit.  There is also a small Y value that gets applied into the CameraOffset gameobject from the 'Camera Y Offset' variable on the XRRig gameobject.  It doesn't appear to have a negative bearing on the render, but thought I would mention it.

**Comment by Ste-RH** [comment] 2022-10-21 13:53
Hmm, one thing that looks odd though, is that the render looks squashed in a top/down sense.  Not sure why.

**Comment by SimonP01** [comment] 2022-10-21 14:28
Hi, thanks for all your efforts.
the XRRig is the standard rig that comes with unity. You get it by: GameObject -> XR -> Convert Main Camera To XR Rig.
The more modern approach is to install the "XR Interation Package" and then GameObject -> XR -> Device Based ->  XR Origin
The Origin Game Object is then moved around if the player moves in VR.

Regarding the shader: It seems the sphere is always at unit scale, which is why it seems of if the camera is not perfectly centered. I guess the GetStereoMatrixVP does not include the modelview matrix. 

Adding it seems to fix things for me. I think.
gl_Position = vpMatrix * unity_ObjectToWorld * gl_Vertex;

**Comment by Ste-RH** [comment] 2022-10-21 14:42
Interesting.  It was the 'tops' of the cylinders in the video that looked too low to me (compared to none-OES).

I have just checked the same scenario out in our default Demo_360Stereo scene on the Quest 1.  The 'right eye' issue is indeed present, but when I apply the shader fix I posted, it is all exactly as I would expect (tops of the cylinders are exactly as with none-OES).

So the XR rig is definitely changing the landscape here.

**Comment by SimonP01** [comment] 2022-10-21 15:00
Interesting.. I thought the only thing the Rig does is translate the camera around in the scene.
I'll do some comparisons starting Monday and report back.

Again, thanks for your efforts today, it's highly appreciated! :)

**Comment by Ste-RH** [comment] 2022-10-21 16:05
Not sure why, but your cylinder height looks completely different to what I am seeing here.  Yours looks correct, or rather, it looks like when not using OES.

This is what I see (looking roughly straight ahead...

![image](https://user-images.githubusercontent.com/46531149/197240130-b996fd17-e683-4bfb-80c3-0f307336a43e.png)

**Comment by Ste-RH** [comment] 2022-10-21 16:51
To add some more confusion.  I copied over the scene that works just fine from our repo (making it mono video and OES enabled) into your demo project...and get the exact same issue as in the screen shot above.  That scene is just fine in the repo project.

I then copied over your scene into the repo project, and that also works just fine!

Only differences appear to be:

- Unity version (2020.3.28f1 vs 2021.3.11fa in your demo project)
- Oculus XR Plugin (1.11.2 - December 15 2021 vs 3.0.2 - June 08 2022 in your demo project : assume the big leap is due to major Unity version difference?)

But all this does not explain why it appears to be just fine for you and not for me in your demo project?!  Assuming you are using the same project for testing as you sent me?

**Comment by SimonP01** [comment] 2022-10-24 08:29
Hi,
Yes this sounds strange indeed. It seems either Oculus or Unity have changed something in the back-end between those versions.
I am indeed testing in the same project I've sent to you.

Regarding the Oculus version number jump: Yes I think so. You can force a different version using the package manifest though. But That could break things.

**Comment by Ste-RH** [comment] 2022-10-24 10:55
I will get these changes in for the next release and we will go from there.

**Comment by SimonP01** [comment] 2022-10-24 11:21
Alrighty. Thanks again for your help.

**Comment by Ste-RH** [comment] 2022-10-24 12:30
Thanks for reporting the issue

**Comment by Chris-RH** [comment] 2022-11-14 13:15
Version 2.6.6 is now out.  Please let us know if this has not resolved your issue.

**Closed** 2022-11-21 09:25 UTC
Labels: Android, Fixed

**Comment by JuanObiJuan** [comment] 2023-01-05 16:39
This is still present in current version. 

My setup is basically (for Oculus Quest 2) the scene included in the demo_360 replacing the camera for the Oculus Quest Camera Rig prefab included in the oculus integration package:
- Stereo Rendering Mode: Multipass settings on Android
- Media player with OES activated
- Material in the sphere: Demo-360 with the shader "AVPro/VR/InsideSphere Unlit Transparent (stereo+color+alpha) - Android OES ONLY"
- AVPro Video: v2.6.7 (plugin v2.6.7f1-ultra)
- Target Platform: Android
- Unity: v2020.3.43f1
- Oculus Camera Rig with Update Multipass Stereo script attached to the center eye Anchor (Camera)
- Render URP
- Playing video "Cones-360Stereo-2K30-H264.mp4"

- I tried just before installing the URP packages and the video looks all right.

- The same scene, but installing URP package (and setting URP assets, quality, etc on the project), the final reuslt change to the camera on the top of the sphere like in the pictures attached. Doesnt matter how big you make the sphere there is no change.

- The same scene but returning to multiview, disabling Android OES and using shader "AVProVideo-VR-InsideSphere-Transparent" everything comes back to how it should and working as expected.
