### ISSUE TITLE
Oculus Go 4k 360 Stereo (3D) aritacts in player

### ISSUE THREAD

**Issue by mark-developr** [RenderHeads/UnityPlugin-AVProVideo#225] opened 2019-11-27 21:08 UTC
**Describe the bug**
Your asset is a life saver so far and has been a much needed improvement on the native unity video player. We needed to move from the native player to AVPro(Android) to solve overheating issues we have with 4k video. Using the alpha 360 stereo shader and not the fast android OES shader because we want to fade the video in and out

However we have some issues with artifacts showing in the video, little green and red flashes, it is subtle but still present and we would like to resolve it.

Can you provide any insight to this? 

Your Setup:
 - Unity version: 2019.2.9f1
 - AVPro Video version: 1.10.1t (scripts v1.10.1)
 - Operating system version: Windows 10, Version 1903
 - Device model: Oculus Go (Android)
 - Video specs (resolution, frame-rate, codec, file size): 4096 x 4096, 30fps, h265, several videos range from 15mb - 143mb

**Comment by mark-developr** [comment] 2019-12-05 02:42
resolved with using Fast OES android playback, we had to sacrafice being able to fade the shader

is it possible to get a fade-able oes 360 stereo shader?

**Comment by AndrewRH** [comment] 2020-02-21 09:50
Glad to hear that you were able to solve your issue :)

As for the fadeable OES shader..  This isn't something we provide, but the source code for our shaders are available in the package, so you should be able to customise them for your needs.

Unfortunately we can't add support for every possible feature and we want to keep the base shaders light.

The OES shader AVProVideo-VR-InsideSphere-AndroidOES already has the _Color property, so you should be able to make it fade to black.  If you want to make it transparent for alpha control, then you can make a copy of it, rename it, and change it to support transparent rendering by changing

Tags{ "Queue" = "Geometry" }

to 

Tags { "Queue" = "Transparent" "IgnoreProjector" = "True" "RenderType" = "Transparent" }

Thanks,

**Comment by AndrewRH** [comment] 2020-02-21 09:51
I will close this ticket now as I believe the issue is resolved.

**Closed by AndrewRH** 2020-02-21 09:51 UTC
Labels: Android, Bug
