### ISSUE TITLE
[Android] The orientation while playing portrait video on android is incorrect

### ISSUE THREAD

**Issue by je2do** [RenderHeads/UnityPlugin-AVProVideo#1945] opened 2024-07-12 03:15 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.6
 - Operating system version: 
 - Device model:  android 14 mobile phone
 - Video specs (resolution, frame-rate, codec, file size):  a common portrait video recorded by mobile phone by portrait taking.

**To Reproduce**
1.  record a video by mobile phone by portrait taking.
2. play the video by AVPro. Either by applyToMesh or DisplayUGUI, either oes or not.
3. See the video orientation and ratio.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

************************************
I have been spending two days debugging on this issue. 
* Obviously, in version of 3.0.6, the texture provided by AVPro Plugin native layer is the same as the source texture provide by ExoPlayer, both for the BGRA and YCbCr420_OES. As the the portrait video, it provides a landscape texture. This is different from AVPro 2.7.3, which does the same for OES texture but not for the none-OES texture.
* After that, it seems like the orientation correction needs to work based on AVPAffineTransform(  AVPAffineTransform -> GetTextureMatrix -> _MainTex_Xfrm -> use the transform matrix in shader to transform uv). But sadly, AVPPlayerVideoTrackInfo.transform is always identical!!!
* While I give the correct transform matrix manually which comes from EXOPlayer, it works perfectly.

I just can't believe that AVPro works incorrectly in such a basic situation.

I have encountered so many bugs on the new version of avpro. It's really driving me crazy!

**Comment by Chris-RH** [comment] 2024-07-12 09:51
This looks to be a duplicate of #1942

**Comment by Ste-RH** [comment] 2024-07-12 13:05
We are hoping to provide a fix for this in a release today, or next week.

> I just can't believe that AVPro works incorrectly in such a basic situation.
> I have encountered so many bugs on the new version of avpro. It's really driving me crazy!

We understand your frustration.  The issues on Android are because we needed to re-implement a huge amount of the plugin to support Vulkan, which was a feature a lot of users were being very vocal to us about implementing, and homogenise with the other mobile platforms.  We are ironing out issues daily, and currently releasing updates weekly to get to a reliable/stable implementation.

**Comment by Chris-RH** [comment] 2024-07-16 13:43
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.

**Comment by Chris-RH** [comment] 2024-07-16 14:35
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.

**Closed** 2024-07-22 09:21 UTC
Labels: duplicate, Android, Fixed, Version 3.x
