### ISSUE TITLE
8K 360 video on Quest 2 crashing

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#547] opened 2020-12-16 10:32 UTC
**Describe the bug**
When using AVPro player to play an 8K video (tried with H264 and H265, 7680x4320, 30fps) from local storage it does play but after a short while it will crash the app. This can also be triggered by mounting/unmounting the headset a few times. Tried with regular and Fast OES path. Video only shows when using Exo Player, with Media Player the image is black.

The same videos play without any issues when using Oculus TV. It's even capable of playing 7680x4320 @ 60fps.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.22f1 on Windows 10 x64
 - AVPro Video version: 1.11.7
 - Operating system version: (Quest 2) based on Android 10
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 7680x4320, 30fps, MP4, H264 and H265.

**To Reproduce**
1. Video player set to Equi rectangular 360 layout mapping, with Exo Player and System Direct Audio Mode.
2. Apply to Mesh is used with a sphere using the OctahedronSphere mesh
3. Sphere uses the AVProVideo/VR/InsideSphere Unlit (stereo+fog) shader, or when using OES: the AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+alpha) - Android OES ONLY shader.
4. Build and run the app and play the video on Quest 2. After a while (mileage varies) the app crashes to Oculus Home without any warning/message.

**Logs**
adb logcat:
[questlog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5701894/questlog.txt)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment] 2021-01-11 13:40
The log you send appears to not show any AVPro Video logging at all.  Are you sure your app is not crashing in another area?  There looks to be plenty of memory issues (out of memory, failed allocations, etc)

**Comment by RenderHeadsSte** [comment] 2021-01-26 19:38
What bitrate is the video you are playing back @RuudvanReenen ?

**Comment by RenderHeadsSte** [comment] 2021-02-03 11:00
We will be closing this issue soon due to lack of response

**Comment by RuudvanReenen** [comment] 2021-02-03 11:12
Sorry for the late reply. The bitrate is approximately 130Mbps, to test if this is the issue I'll see if 50Mbps plays well.

I hope I can add a new log file this week. The video (and the memory use of it) is definitely the cause of the crashing, with lower resolution 360 videos the app keeps running fine.

**Comment by RenderHeadsSte** [comment] 2021-02-03 11:41
Roger that,

As I said earlier, in version 2 of AVPro Video we utilise an ExoPlayer feature that lets the player favour lower ram usage over buffering ahead duration.

I know from another issue reported (and testing here) that 100MBit near 8k videos playback on a Quest 2 just fine in version 2.  You could test your use-case out using the trial version maybe...if having very high bitrates is super important to your project, at least then you have an option to get things working as you require.

**Comment by RenderHeadsSte** [comment] 2021-02-03 11:43
If you want to send over one of your 130MBit videos to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) then I will happily test it in AVPro Video version 2 on a Quest 2.

**Comment by RuudvanReenen** [comment] 2021-02-03 15:46
Thanks for looking into it, I've sent a link via email

**Comment by RenderHeadsSte** [comment] 2021-02-08 18:08
We have not received anything from you @RuudvanReenen.  Can you confirm you have sent it to the correct address?  You might need to use something like WeTransfer to send the video.

**Comment by RuudvanReenen** [comment] 2021-02-08 18:14
I've emailed to unitysupport@renderheads.com on Wednesday around 13:00 CET, with a link to the files on Google Drive. Ended up in spam folder?

**Comment by RenderHeadsSte** [comment] 2021-02-08 18:20
There is no spam folder in our support ticket system.  I have just checked everywhere it could be and have nothing for 3rd Feb.  Could you send it through again?

**Comment by RuudvanReenen** [comment] 2021-02-08 18:32
Ok, sent again, also from another account

**Comment by RenderHeadsSte** [comment] 2021-02-08 18:55
Received. Thanks

**Comment by RenderHeadsSte** [comment] 2021-02-08 19:52
I can confirm that both videos playback perfectly fine on Quest 2 using AVPro Video v2.

**Comment by RenderHeadsSte** [comment] 2021-02-09 11:58
There is no back-port possible to v1.x for the 'favour lower ram usage over buffering ahead duration' feature of v2.  I am closing this issue now as three is a fix offered in v2 and we cannot offer one in v1.x.

**Closed by RenderHeadsSte** 2021-02-09 11:58 UTC
Labels: Android, Version 1.x, wontfix
