### ISSUE TITLE
I made a prefab and placed a UI video inside it. Every time I regenerate the prefab, does frequent generation and destruction of the prefab cause memory leaks

### ISSUE THREAD

**Issue by qinlinger1** [RenderHeads/UnityPlugin-AVProVideo#1621] opened 2023-08-21 12:43 UTC
**Describe the issue**
I made a prefab and placed a UI video inside it. Every time I regenerate the prefab, does frequent generation and destruction of the prefab cause memory leaks？  The program crashed in about four hours

[AVProVideo] Error: Decode failed.  Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: unity2022.3.3
 - AVPro Video version (Initialising AVPro Video v2.8.0 (native plugin v2.8.0f1-ultra) on NVIDIA GeForce GT1030  Direct3D 12.0 [level 11.1] (MT True) on WindowsEditor): 
 - Operating system version: 
 - windows10
 - Device model: 
 - Video specs (1920 1080 60fps): 

**Screenshots**
![5196c2b251c5600ae9b709045e46df8](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/64240865/e965ea04-d109-4dca-b432-8d12465ae57a)

have a good day

**Comment by Chris-RH** [comment] 2023-08-22 07:07
1. Can you update to the latest version of AVPro Video please
2. It looks like you have a lot going on in your project. Can you reproduce this using a new project and just AVPro Video?

**Comment by qinlinger1** [comment] 2023-08-22 07:26
Initialising AVPro Video v2.8.0 (native plugin v2.8.0f1-ultra) on NVIDIA GeForce RTX 3050/Direct3D 11.0 [level 11.1] (MT True) 
It's already very new

**Comment by Chris-RH** [comment] 2023-09-04 08:39
any more info? 
Can you reproduce this using a new project and just AVPro Video and send it to unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2023-09-08 08:45
closing due to lack of reply

**Closed by Chris-RH** 2023-09-08 08:45 UTC
Labels: Windows
