### ISSUE TITLE
About Custom HTTP Headers for Basic Authentication

### ISSUE THREAD

**Issue by berise-hayashi** [RenderHeads/UnityPlugin-AVProVideo#1565] opened 2023-06-20 13:41 UTC
I would like to play a video file in a directory with Basic Authentication set up.

https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html

Referring to the above page
I have configured the authentication information with Base64 encoding from within the script to CustomHTTPHeaders.

On Android devices, playback was successful, but on UnityEditor, Windows, and iOS, an error message was displayed and playback was not possible.

When the exact same video file was placed in a directory on the same server where basic authentication was not set, the video played without issue in all environments.

Is this a known issue?

Translated with www.DeepL.com/Translator (free version)

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.8.0-ultra

**Comment by berise-hayashi** [comment] 2023-06-20 15:58
Thanks for the reply.

Since the current URL cannot be shared, we will prepare a server with a similar environment and send you the URL.

Please allow us a little time for this.

**Comment by berise-hayashi** [comment] 2023-06-20 16:50
I have just sent you the URL and authentication information for the test environment in an email with the same title as this issue.

Thank you for your cooperation.

**Comment by Chris-RH** [comment] 2023-06-21 09:27
On Windows custom HTTP headers are only supported on the WinRT API, and are only supported for adaptive media (HLS and DASH).

**Comment by berise-hayashi** [comment] 2023-06-22 04:16
Thank you very much.
I will try it!

**Comment by berise-hayashi** [comment] 2023-06-22 08:56
We tested it using the method you taught us.

Windows displayed the authentication dialog and did not automatically enter the authentication information.

On Android, an error occurred and the video did not play.
The following is the error message.

>[AVProVideo] Error: Loading failed. File not found, codec not supported, 
>video resolution too high or insufficient system resources.
>RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
>RenderHeads.Media.AVProVideo.MediaPlayer:Update()

Do you have any additional information?

**Comment by Chris-RH** [comment] 2023-06-27 09:22
@berise-hayashi 
Just trying to recap.

1. Android worked to start with, yes? So if you don't change anything then it should still work?
2. iOS now works with the changes, yes?
3. Windows is the one we are currently having an issue with.  It is at least playing now, but it should be doing so without having to re-enter credentials.

**Comment by RichRH** [comment] 2024-03-14 12:10
FYI.. the above is now fixed under Windows but it required implementing a new WinRT HTTP async request handler which we deemed an enhancement as opposed to a fix. To that end it will be available as part of the imminent version 3.0 release.

Cheers,

**Comment by Chris-RH** [comment] 2024-03-25 12:22
This should be fixed in AVPro Video version 3.0.0.  The trial version is available [here ](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases)for testing.  Please let us know if the issue is not fixed in this version.

**Closed** 2024-04-02 10:50 UTC
Labels: enhancement 🚀, Windows, pinned
