### ISSUE TITLE
Rewind and Play when video is paused on end frame is rewinding but not playing

### ISSUE THREAD

**Issue by matt-aitken** [RenderHeads/UnityPlugin-AVProVideo#24] opened 2019-02-19 18:00 UTC
**Describe the bug**
The video is paused on the final frame and I want a button that rewinds to the start and automatically starts playing. If the video is already playing (i.e. in the middle) then this works fine but if it is at the end (i.e. paused on the final frame) the video rewinds to the beginning but doesn't play.

I've tried using:
`MediaPlayer.Rewind();
MediaPlayer.Play();`

Then I thought it was probably because seeking wasn't finished before calling Play(), so I tried calling Rewind() and then waiting for seeking to finish then calling Play() but it still doesn't reliably play. Even using the MediaPlayer Event for seeking finished then calling Play() doesn't seem to work 100% of the time.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.5f1 in the Editor and built to iPhone it's behaving the same.
 - AVPro Video version: 1.9.8
 - Operating system version: Mac Mojave (multiple versions)
 - Device model: Mac Editor and iOS 12 builds
 - Video specs (resolution, frame-rate, codec, file size): mp4 24fps h264 on files even as small as 2MB

To Reproduce**
1. Play a video with looping turned off
2. When it reaches the end (is paused on final frame) try and rewind to the start and play

**Comment by MorrisRH** [comment] 2019-02-20 10:46
Hello!
I'm unable to reproduce this.
Rewind followed by Play is working fine on both macOS and iOS. In fact the Rewind is unnecessary, just calling Play after a video has finished will play from the start.
Are you able to provide any more information?

**Comment by petermauger** [comment] 2019-04-07 23:47
Hey, I ran into this a very similar problem, except I was trying to rewind and then pause. You need to call Rewind() ONLY when the button is pressed. Then you need to monitor events and when the finished seeking event fires, THEN you call whatever you want to happen next. Fairly sure that, while it's in seeking mode, it ignores some of the other calls until seeking is finished.

**Comment by MorrisRH** [comment] 2019-07-09 16:19
Closing this issue as we've not heard anything back from you for quite some time.
Feel free to re-open it if you think the problem still exists.

**Closed by MorrisRH** 2019-07-09 16:19 UTC
Labels: bug, iOS, macOS, need more info
