### ISSUE TITLE
[iOS] How to build Unity Flutter project

### ISSUE THREAD

**Issue by kunka7** [RenderHeads/UnityPlugin-AVProVideo#1659] opened 2023-10-10 01:19 UTC
**Describe the issue**
im using this (https://pub.dev/packages/flutter_unity_widget) flugin in my unity project
im exporting my project with ios version
and i  try build this xcode project but it failed
how handle this?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.19f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core

**To Reproduce**
1. install (https://pub.dev/packages/flutter_unity_widget) and avpro in unity project
2. Export ios through flutter flugin https://raw.githubusercontent.com/juicycleff/flutter-unity-view-widget/master/files/Unity_Build_Options.png
3. exported ios xcode proejct have problem

**Logs**

> dyld[2049]: Library not loaded: @rpath/AVProVideo.framework/AVProVideo
> 
>   Referenced from: <420A1410-F231-3DEE-B15B-31DCB835C706> /private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/UnityFramework.framework/UnityFramework
> 
>   Reason: tried: '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/UnityFramework.framework/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/private/var/containers/Bundle/Application/3CF18742-00DF-4ACE-8F08-716A0BB41993/Runner.app/Frameworks/AVProVideo.framework/AVProVideo' (no such file), '/System/Library/Frameworks/AVProVideo.framework/AVProVideo' (no such file, not in dyld cache)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2023-10-10 09:14
Hi @kunka7 
Make sure that you have followed all of these instructions: https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html#troubleshooting

**Comment by MorrisRH** [comment] 2023-10-10 16:50
Duplicate of #1395

**Comment by kunka7** [comment] 2023-10-11 01:23
> Duplicate of #1395

hello @MorrisRH thank you for answer
i was follow that case but problem not solved
this is my project

![MicrosoftTeams-image (1)](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/9a901d27-251b-4b84-99e2-e9ff17ec4909)
![MicrosoftTeams-image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/c4e146a9-3bcb-4ab2-9bbf-0142e1d61cf1)
![MicrosoftTeams-image (2)](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/13de6195-36c8-4c3c-877b-ba84bde32181)

what did i miss?

**Comment by MorrisRH** [comment] 2023-10-11 18:15
I've no experience with flutter but if this is like anything else where Unity is being used as a library then you should:
- Set `AVProVideo.framework` to `Do Not Embed` in the Unity-iPhone target
- Add `AVProVideo.framework` to the Runner target and set it to `Embed & Sign`

**Comment by kunka7** [comment] 2023-10-12 07:42
> I've no experience with flutter but if this is like anything else where Unity is being used as a library then you should:
> 
> * Set `AVProVideo.framework` to `Do Not Embed` in the Unity-iPhone target
> * Add `AVProVideo.framework` to the Runner target and set it to `Embed & Sign`

every try i made failed, i think its about package dependencies problem, i will try make this plugin to custom pakcage in packages folder

**Comment by kunka7** [comment] 2023-10-12 08:33
> > I've no experience with flutter but if this is like anything else where Unity is being used as a library then you should:
> > 
> > * Set `AVProVideo.framework` to `Do Not Embed` in the Unity-iPhone target
> > * Add `AVProVideo.framework` to the Runner target and set it to `Embed & Sign`
> 
> every try i made failed, i guess its about package dependencies problem, i will try make this plugin to custom package in packages folder

oh it was not, i really dont know how to fix it, it's always be like this ![MicrosoftTeams-image (2)](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/13de6195-36c8-4c3c-877b-ba84bde32181)

**Comment by MorrisRH** [comment] 2023-10-12 21:51
Hey @kunka7 
I have this working using the following steps with a fresh flutter and unity project.

With the runner project and target selected, click on the + under `Frameworks, Libraries and Embedded Content` in the General pane.
<img width="1156" alt="Screenshot 2023-10-12 at 14 39 52" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/3063ce13-a3a9-4fb9-9021-03e49a08ce73">

Click on the `Add Other` dropdown and select `Add Files...`

<img width="1044" alt="Screenshot 2023-10-12 at 14 40 28" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/8c65cf4d-dcec-4003-9f2b-d3e39f76a88d">

Select `AVProVideo.framework` from `UnityLibrary/Frameworks/AVProVideo/Runtime/Plugins/iOS`
<img width="1156" alt="Screenshot 2023-10-12 at 14 41 04" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/a4a18877-5e95-4d27-86e0-c30580a5469b">

Make sure `AVProVideo.framework` is set to `Embed & Sign`
<img width="1156" alt="Screenshot 2023-10-12 at 14 41 11" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/dc28a0fc-83e6-4b3c-a632-62a501603365">

Now build and run your project.

**Comment by kunka7** [comment] 2023-10-13 01:20
> Hey @kunka7 I have this working using the following steps with a fresh flutter and unity project.
> 
> With the runner project and target selected, click on the + under `Frameworks, Libraries and Embedded Content` in the General pane. <img alt="Screenshot 2023-10-12 at 14 39 52" width="1156" src="https://user-images.githubusercontent.com/46530460/274739772-3063ce13-a3a9-4fb9-9021-03e49a08ce73.png">
> 
> Click on the `Add Other` dropdown and select `Add Files...`
> 
> <img alt="Screenshot 2023-10-12 at 14 40 28" width="1044" src="https://user-images.githubusercontent.com/46530460/274740076-8c65cf4d-dcec-4003-9f2b-d3e39f76a88d.png">
> Select `AVProVideo.framework` from `UnityLibrary/Frameworks/AVProVideo/Runtime/Plugins/iOS` <img alt="Screenshot 2023-10-12 at 14 41 04" width="1156" src="https://user-images.githubusercontent.com/46530460/274740283-a4a18877-5e95-4d27-86e0-c30580a5469b.png">
> 
> Make sure `AVProVideo.framework` is set to `Embed & Sign` <img alt="Screenshot 2023-10-12 at 14 41 11" width="1156" src="https://user-images.githubusercontent.com/46530460/274740469-dc28a0fc-83e6-4b3c-a632-62a501603365.png">
> 
> Now build and run your project.

Great! build is success but there is another issue
when call the unity sendmessge the program is stopped
and make this errorlog

> [libil2cpp] ERROR: Could not open /var/containers/Bundle/Application/3700C15D-1EE0-4B50-82A0-2D7C4624B55D/Runner.app/Frameworks/UnityFramework.framework/Data/Managed/Metadata/global-metadata.dat
> 
>    IL2CPP initialization failed
> 
> 2023-10-13 09:57:21.720734+0900 Runner[1727:478534] [client] No error handler for XPC error: Connection invalid
> 
> 2023-10-13 09:57:21.721501+0900 Runner[1727:478541] [VERBOSE-3:thread_local.cc(32)] Check failed: false. pthread_setspecific failed (22): Invalid argument

fortunately i can find solution from here
https://github.com/wowmaking/react-native-unity/issues/20
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/bb843621-5522-4c5a-96d3-4b732f28a710)
setting like this problem is sovled

thanks a lot @MorrisRH

**Closed** 2023-10-13 07:11 UTC
Labels: duplicate, won't fix, iOS
