### ISSUE TITLE
Looping + End of Video event not firing with MediaFoundation playback path

### ISSUE THREAD

**Issue by mikerz** [RenderHeads/UnityPlugin-AVProVideo#799] opened 2021-05-24 18:13 UTC
**Describe the issue**
When playing back a video using the MediaFoundation playback path, no event is fired upon video completion, nor does looping occur if the MediaPlayer component is set to looping playback. This does not happen if using DirectShow playback path (WinRT not tested/used in our products)

**Your Setup (please complete the following information):**
 - Unity version: 2019.4
 - AVPro Video version: 2.1.2
 - Operating system version: Windows 10 
 - Device model:  PC
 - Video specs (resolution, frame-rate, codec, file size):  4k x 4k, 60 fps, h265 / h264

**To Reproduce**
1. Open Demo_MediaPlayer scene
2. Remove the AudioOutput component from MediaPlayer (It works in the demo scene if this component remains)
3. Play -- video won't loop and will instead hang in a seeming buffering state at the end

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment] 2021-05-25 05:24
This was reproduced and the issue is that without the AudioOutput component, no audio was being consumed, so when the video ended it was waiting for the audio to be drained from the buffer.  

We've fixed this issue now by adding some detection for cases where the audio is not drained, in which case it will just flush the buffer and continue.

The fix will be released in 2.1.4 hopefully later this week or early next week

**Comment by kahnivore** [comment] 2021-06-22 14:59
Noting that the fix was released in 2.1.4

**Closed by kahnivore** 2021-06-22 14:59 UTC
Labels: Bug 🐛, Fixed, Version 2.x, Windows
