### ISSUE TITLE
AVPro 2.1.5 crashes on macOS when starting videos repeatedly

### ISSUE THREAD

**Issue by Marcurion** [RenderHeads/UnityPlugin-AVProVideo#853] opened 2021-07-07 12:54 UTC
Hi,

we encountered an issue with the new version:

On MacBooks with the new M1 processor, we found that repeated video starts lead to an app crash. Unity version was a recent 2020.3 LTS.
The faster the video is restarted, the faster the app will crash (0.3 seconds will crash almost immediately or after about 3 restarts). Longer intervals will delay the problem and allow for more restarts but not fix it.

We prepared an example project which you can use to reproduce the issue. You need to add AVPro Version 2.1.5.
https://share.str8labs.net/f.php?h=1CRCCwC5

Another possible issue but not confirmed yet, on M1, the screen safer might crash an app too when the video is playing.

We already checked that the RAM limit of the device is not hit.
Occurs on Mono and IL2CPP scripting backends.
We could not reproduce the issue with iOS (also ARM).

Kind regards

**Comment by MorrisRH** [comment] 2021-07-08 10:52
Thanks for the sample scene. I've been able to reproduce this on both Intel and ARM macs so it's not specific to Apple Silicon.  At 0.3 seconds I didn't see any crashing at all, but at 0.1s it's pretty much instant.

**Comment by Marcurion** [comment] 2021-09-23 07:26
Hi,

I want to suggest reprioritizing this issue.

We found that this affects iOS platforms too and that when using the player in a production environment, the issue is way more severe. Looking at the devices where this issue is most relevant, this seems to be memory-related.
Below you find a link to a unity project with a proxy environment we set up to speed up the process since the environments we usually use are under NDA. You need to add AVPro Ultra version 2.2.0 to the project before building.
https://share.str8labs.net/f.php?h=1pnDVwLN

Alternatively, you find a precompiled .ipa here, which you can install using the OTA method of your choice:
https://share.str8labs.net/f.php?h=3YRMmLqE

So what we could reproduce with this project:
iOS devices with 2 GB of physical memory regularly crash after 1-20 video restarts, even in an 3 seconds interval.

Devices where we could observe this include:

- iPad Air 2
- iPad Pro 9.7"
- iPad (2018)

iOS devices with more memory e.g. iPhoneX are more tolerable but not immune to this issue and require significantly more restarts or shorter intervals to crash.

**Comment by MorrisRH** [comment] 2021-09-24 10:54
@Marcurion the issue you're seeing on iOS is quite separate to the crash caused by starting videos repeatedly.

From your demo project I can see that your scene is already using a lot of memory (1.2Gb on my iPad Pro) before the video player starts so I would suggest that getting this down should be your first port of call.

To reduce the amount of memory the media player is using you can try setting the texture mode in the iOS platform specific settings to YCbCr. This was the default for version 1.x but for 2.x we were able to get the overheads of producing BGRA textures down quite considerable so it's not as big a saving as before.

You can also try setting the Audio Mode to System Direct (if it isn't already) as this will prevent the need to allocate audio buffers.

**Comment by Marcurion** [comment] 2021-10-12 12:20
@MorrisRH thanks for your suggestion we tried implementing the steps, but saw no improvement with the issue.

Well of course we would prefer reducing the overall RAM usage of our app and the proxy environment does not represent the level of optimization our apps have but rather simulates the memory consumption after optimization. This has to do with the amount of content and graphical fidelity we need to provide.

- So turning your question around how much memory should we reserve for repeated video playback? And does it depend lineary on the video file size?

- Also we could run v1 with no issues in the same project.

- And then even if we ignore the growing memory demand, the example shows that iOS as a platform is affected by the original repeated start issue too. This can be seen by crashes on an iPhoneX which has 1GB more RAM available.

**Comment by MorrisRH** [comment] 2021-11-12 09:51
A fix will be in the next release (version 2.2.4).

**Closed by MorrisRH** 2021-11-12 09:51 UTC
Labels: Bug 🐛, iOS, macOS, Fixed, Version 2.x

**Comment by AndrewRH** [comment] 2021-11-18 12:40
@Marcurion AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,
