### ISSUE TITLE
Complete Editor freeze when starting Streaming

### ISSUE THREAD

**Issue by AntoineFougea** [RenderHeads/UnityPlugin-AVProVideo#144] opened 2019-08-09 15:31 UTC
**Describe the bug**
Unity completely freezes, only when using HTTP/HTTPS URL to an online resource.
With an exciting error: Receiving unhandled NULL exception

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.11f1
 - AVPro Video version: 1.9.18t (scripts v1.10.0)
 - Operating system version: macOS Mojave 10.14.6 Beta (18G71a)
 - Device model: iMac (Retina 5K, 27-inch, 2017)
 - Video specs (resolution, frame-rate, codec, file size): 720p H264 11MB

**To Reproduce**
1. Add a Media Player component to a GameObject.
2. Switch to Absolute Path Or URL and enter an HTTP URL to an online mp4. 
3. Force Quit Unity.

**Logs**
Because Unity crashes, there's no console message. However, the last Editor.logs file are:

    [AVProVideo] Opening https://<my_url_was_here>.mp4 (offset 0) with API 
    UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object, Object)
    UnityEngine.Debug:Log(Object, Object)
    RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at Assets/AVProVideo/Scripts/Internal/Interfaces.cs:609)
    RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:893)
    RenderHeads.Media.AVProVideo.MediaPlayer:Start() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:520)
 
    (Filename: Assets/AVProVideo/Scripts/Internal/Interfaces.cs Line: 609)

    Receiving unhandled NULL exception

**Comment by AndrewRH** [comment] 2019-08-09 16:21
Thanks for reporting this.  I notice you're running a beta version of macOS.  Have you been able to replicate this on another system?

**Comment by MorrisRH** [comment] 2019-08-27 11:17
I'm unable to reproduce this here with macOS 10.14.6 and Unity 2019.1.11f1.

Are you able to provide the URL you were using? If you need to keep it private, please send it to 
unitysupport@renderheads.com

**Comment by AndrewRH** [comment] 2019-09-10 11:36
Were you able to send more information?

We will close this thread soon due to inactivity.  Thanks,

**Comment by AndrewRH** [comment] 2019-09-19 11:25
Closing thread due to lack of information

**Closed by AndrewRH** 2019-09-19 11:25 UTC
Labels: bug, macOS, need more info
