### ISSUE TITLE
Using ASIO plugin causing videos to not play

### ISSUE THREAD

**Issue by Sbrenman** [RenderHeads/UnityPlugin-AVProVideo#622] opened 2021-02-10 03:10 UTC
**Describe the bug**

Video playback will sometimes seemingly stop working for most videos on a per-machine basis. Seems to be especially bad with H265 codec, though all videos will play in the Windows Media Player outside of Unity. HEVC extension is installed. We believe this issue is hardware related, not software related, as it only happens on certain machines. My machine has started to have this issue - even when I run an older build in which I had no playback issues at the time, I will still see these errors now.  We need guidance for finding the cause of these bugs.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.16f1
 - AVPro Video version: Version   1.11.6   /   2.0.0   beta   5  
 Released: Oct 16th 2020  
 
 - Operating system version: Windows 10 Enterprise version 2004
 - Device model: Dell precision 5820 Tower X-Series, 
 - Processor: Intel(T) Core(TM) i9-10900X CPU @ 3.70GHz 3.70, GPU NVIDIA Quadro RTX 5000
 - Video specs  (resolution, frame-rate, codec, file size): These are the specs for one example video that doesn't run and causes the error logs pasted below. However there are several more videos with the same issue that may have some differing specs.
 2880 x 2880 (resolution), 60 fps, HEVC 

**To Reproduce**
1. Implement AVPro Content provider
2. Attempt to play video
3. 

**Logs**
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1104)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:545)

Got a error playing back:LoadFailed
UnityEngine.Debug:LogError(Object)
SimVis.ContentPlaybackSystem.MediaInfo.AVProVideoContentProvider:ReceivePlayerEvent(MediaPlayer, EventType, ErrorCode) (at Packages/SimVisCoreCode/Runtime/ContentPlaybackSystem/AVProVideoContentProvider.cs:316)
UnityEngine.Events.UnityEvent`3:Invoke(MediaPlayer, EventType, ErrorCode)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1119)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:545)

**Screenshots**
<img width="1226" alt="Capture" src="https://user-images.githubusercontent.com/67117675/107459086-67892280-6b23-11eb-87ba-dae0ac243711.PNG">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Sbrenman** [comment] 2021-02-10 15:54
UPDATE: We tested the [AVPro Trial Version 2.0.6](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) in a new Unity project (v 2019.4.16f1). Here are the results of trying to play the sample videos:

Working:
RenderHeads-1080p30-H264.mp4
Cones-2D-1080p60-H264.mp4
BigBuckBunny-360p30-H264.mp4

Error:
Cones-360Mono-4K60-HEVC.mp4
Cones-360Stereo-2K30-HEVC.mp4
Cones-Transparent-4K60-HEVC.mp4

The error message is the same as the one described in this ticket:
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1164)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:599)

I also tried videos from our content library. All the videos with HEVC codec that do not play in our project, also had an import error upon dragging them into the project. Here is an image of that import error:
<img width="1470" alt="importerrors" src="https://user-images.githubusercontent.com/67117675/107534876-3eea4280-6b8e-11eb-90c3-a6b87413212e.PNG">

The 2 videos in my content library that do play (AVC) did not have the import error when I dragged them into the project.

**Comment by AndrewRH** [comment] 2021-02-10 15:58
Thanks for extra info.   Could please send a screenshot showing the HEVC codec version installed on your system?

You can find this if you go to "Apps & Features" in Windows and type HEVC into the search box:
![image](https://user-images.githubusercontent.com/5418126/107535325-8ab1e180-6bb8-11eb-81bc-082f58947fba.png)

then if you click on it and go to "Advanced Options" it will take you to a screen showing all the information in the Window:
![image](https://user-images.githubusercontent.com/5418126/107535562-c056ca80-6bb8-11eb-8da4-bf7cca538718.png)

Thanks,

**Comment by Sbrenman** [comment] 2021-02-10 16:04
Hi Andrew,

I have 2 results that come up for HEVC - here are the images:

[cid:46b415d8-00a0-481a-b571-b6cc43403fe9]

[cid:ae01cbd4-c501-41c2-bbf1-981de73d31d1]

[cid:85a2c712-2f48-4b9d-8366-d3fbfc13adc6]

Thank you,
Sasha



Sasha Brenman
Software Engineer, Simulation & Visualization

MSG Ventures
11 W 33rd Street|24th Floor
New York, NY 10120

[cid:d37c33ab-b1a5-46e6-8151-14e09346436e]
________________________________

**Comment by RenderHeadsSte** [comment] 2021-02-10 16:23
Very interesting that you have two. HEVC extensions installed.

Would it be possible to see if that is the case on all the PCs that you are seeing this issue on?  Also, how many are on the PCs where you do not see the problem...

**Comment by Sbrenman** [comment] 2021-02-10 16:26
Adding the team for visibility.

Sasha Brenman
Software Engineer, Simulation & Visualization

MSG Ventures
11 W 33rd Street|24th Floor
New York, NY 10120

[cid:9926ad7d-1686-48db-a9ac-739c53143f37]
________________________________

**Comment by MichaelRankin-MSG** [comment] 2021-02-10 16:37
I only have HEVC Video Extensions installed at the moment.  I had HEVC Video Extensions from Device Manager also installed at one point, but removed it when I was trying to debug the issue.

For the earlier bug report re: which videos worked with the unitypackage, I had the same results.

**Comment by AndrewRH** [comment] 2021-02-11 15:14
Hi @MichaelRankin-MSG @Sbrenman 

We've installed newer Windows and versions of these extensions and we're just not able to reproduce the issue you're reporting.  The HEVC videos continue to play back fine without issue.   I have a few questions and suggestions which may move us forward:

1) Could you try upgrading the HEVC extension(s) to the latest version?  I see you're on 1.03324x and the latest version is 1.0.40203. (it might be a good idea to reboot too after this)
2) Could you try upgrading your GPU drivers?
3) If it's still not working, could you try switching the Video API to WinRT (in Platform Specific > Windows section of the MediaPlayer component) and see if that works?

That's all I can think of for now.

Thanks,

**Comment by Sbrenman** [comment] 2021-02-12 18:31
Hi @AndrewRH, Thanks for these suggestions. 

Unfortunately, I was not able to update my HEVC extension as I did not see any updates available for it. Not sure how to go about getting 1.0.40203. 
My GPU drivers are also up to date. 
I did try the third suggestion, but it didn't make any difference and I still got the same error messages upon selecting videos for playback. 

I also tried using mftrace as I understand the output file could be helpful. However, I continually got this same error while attempting to run mftrace "Failed with hr=0x80070032 (ERROR_NOT_SUPPORTED)". I tried running the trace on the Unity Editor, as well as a Debug Build of the app and still got this error.  Have you been able to run mftrace on a Unity editor or build? 

Thank you.

**Comment by AndrewRH** [comment] 2021-02-12 18:55
Hi @Sbrenman 

Yes mftrace is a good idea.  I have it running here with Unity so it should be possible to use:
![image](https://user-images.githubusercontent.com/5418126/107809712-6d6d4680-6d63-11eb-83d5-2cc6318c1a78.png)

I copied these files out of the Windows SDK folder, then run Unity with the video project, and then through an administrator command-line I run "mftrace -a Unity.exe -o mf.txt"

It works for me and I don't get the error you had, so hopefully you're able to get it to work.  It should give us some good insight into why it's failing to play the videos.

**Comment by Sbrenman** [comment] 2021-02-13 02:24
Thanks Andrew - I copied over mftrace.exe and mfdetours.dll to my build folder so I can run the command without having to type in all the paths. Same issue though - here's the verbose version of the error:

<img width="733" alt="mftrace error" src="https://user-images.githubusercontent.com/67117675/107839269-b54a9880-6d78-11eb-9fd4-09d8380c7800.PNG">


Could this be part of the underlying problem?

**Comment by Sbrenman** [comment] 2021-02-13 02:28
For clarity - also ran this on the unity editor with the same message

**Comment by AndrewRH** [comment] 2021-02-13 13:44
Thanks for this - I think you may be running the 32-bit version of mftrace, and then the application's you're trying to trace are 64-bit.   I tried this and got the same error messages that you had. 

I've attached the 64-bit version of mftrace here for you to try:
[mftrace.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5975761/mftrace.zip)

Thanks,

**Comment by Sbrenman** [comment] 2021-02-13 17:20
Thanks! That did the trick. 

Here are my output logs. I ran mftrace on a build of our project as well as on the unity editor running the project. I just clicked on several videos that failed to play and then stopped the application. 


[mftraceOutputUnityEditor.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5976140/mftraceOutputUnityEditor.txt)
[mftraceOutput_UnityBuild.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5976141/mftraceOutput_UnityBuild.txt)

**Comment by AndrewRH** [comment] 2021-02-16 17:00
Thanks for these logs, i'm busy going through them now.   I am reading this correctly that even the H264 videos didn't play, such as BigBuckBunny-360p30-H264.mp4?

Thanks,

**Comment by Sbrenman** [comment] 2021-02-16 19:25
Yes- even some of the H264 videos didn't play. 

Also, just letting you know I'm temporarily working from another location and won't be back on this machine that is having playback issues for a couple of weeks. We could still try out potential solutions on Mike Rankin's machine in the meantime, as he has experienced similar issues as I have.

Thanks

**Comment by AndrewRH** [comment] 2021-02-17 13:45
Thanks - that's strange...

I think we may have to get remote access to work out what's going on.

Please also check via the registry editor whether there is anything listed here:
Computer\HKEY_CLASSES_ROOT\MediaFoundation\MediaSources\DoNotUse

![image](https://user-images.githubusercontent.com/5418126/108212895-57c29d00-7126-11eb-9d06-65f1c7f931dc.png)

Let's discuss remote acccess via email.

Thanks,

**Comment by AndrewRH** [comment] 2021-02-17 13:52
If you could also email us a dxdiag report (by running dxdiag and saving the info to .txt file) from the affected machine that would be very helpful.

Thanks,

**Comment by AndrewRH** [comment] 2021-02-17 16:49
This may be another clue.  From your log it seems like it's having some trouble setting up the audio renderer:
![image](https://user-images.githubusercontent.com/5418126/108237550-ee4f8800-713f-11eb-9325-0a98d8c6c493.png)

I wonder if your machines have some other audio devices/software connected that may be conflicting?

I wonder what happens if you try to play a video that doesn't contain audio..

Thanks,

**Comment by MichaelRankin-MSG** [comment] 2021-02-17 19:19
Hello Andrew!  To add a couple more data points:
When I play most videos, I get this error:
`
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1104)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Packages/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:545)
`

The video having audio doesn't seem to make a difference.  Video without audio throws the error, and in the past, video with audio has played correctly (though at the moment I don't have an example of that.  Which videos do and don't work seems to change occasionally).  All the videos I've used to test with work fine through Windows Media Player.

I tested today after unplugging any device that could be considered an audio device (external speakers, headset, Oculus Quest), and it didn't change anything re: which videos did or didn't throw the error.

**Comment by AndrewRH** [comment] 2021-03-01 15:37
Okay we have resolved this remotely and found that it was caused by an ASIO plugin locking access to the Realtek driver, so Media Foundation couldn't access it and just errored while loading the video.

I will close this issue now.

Thanks,

**Closed by AndrewRH** 2021-03-01 15:37 UTC
Labels: Version 1.x, Version 2.x, Windows
