### ISSUE TITLE
AVProMedia Player Compatibility with MIUI Platform

### ISSUE THREAD

**Issue by LibGame** [RenderHeads/UnityPlugin-AVProVideo#1941] opened 2024-07-10 10:13 UTC
Hello,

I have a question regarding the compatibility of AVProMedia Player with the MIUI platform. Does AVProMedia Player support this platform, and are videos played without any issues on MIUI devices?

Thank you in advance for your response!

**Comment by Chris-RH** [comment] 2024-07-10 10:23
I believe this is the OS that Xiaomi devices run on?  As far as I'm aware, AVPro does run on such devices.  I would suggest that you try our free, fully featured, [watermarked trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases).

**Comment by LibGame** [comment] 2024-07-10 11:11
I am using AVPro Media Player on a Samsung device, and the video displays correctly. However, on a Xiaomi Redmi Note 9, the video does not display and only shows a black screen. I am using the Exo Player Video API.

**Comment by Chris-RH** [comment] 2024-07-10 13:13
Please can you fill in a full issue form.

**Comment by MorrisRH** [comment] 2024-07-10 15:48
We regularly test on Xiaomi devices and have seen no compatibility issues with MIUI.
The issue is likely specific to the device you're testing on and the video you're trying to play.
Please provide as much information as possible so that we can help you further.

**Comment by Chris-RH** [comment] 2024-07-15 08:43
Please can you fill in a full issue form

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2024-07-22 08:41
Closing due to lack of reply

**Closed by Chris-RH** 2024-07-22 08:41 UTC
Labels: Android, need more info 🤷
