### ISSUE TITLE
How to dynamically switch the adaptive resolution in HLS?

### ISSUE THREAD

**Issue by Andjiang707** [RenderHeads/UnityPlugin-AVProVideo#1247] opened 2022-08-04 09:56 UTC
Problem description:

Hello, 
I need to use avpro to play HLS with adaptive resolution, 
and also need to dynamically switch between different resolutions,
but I can't achieve this function at present.

Device (which devices are you having the issue with - model, OS version number):

 Android Quest2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

HLS Multibitrate, 270p up to 1080p，MP4

System Information:

AVPro Video: v2.5.7 (plugin v2.5.7f1-ultra)
Target Platform: Standalone
Unity: v2020.3.14f1 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.19044) 64bit - ChineseTraditional
CPU: AMD Ryzen 9 3900XT 12-Core Processor  - 24 threads - 65464KB
GPU: NVIDIA GeForce RTX 2080 SUPER - NVIDIA - Direct3D 11.0 [level 11.1] - 8010KB - 16384

**Comment by Chris-RH** [comment] 2022-08-04 10:19
Could you try changing your manifest so that it has each stream on its own as well as the adaptive one?

**Comment by MorrisRH** [comment] 2022-08-05 14:45
Duplicate of #1214

**Closed** 2022-08-10 14:47 UTC
Labels: duplicate, Android

**Comment by Andjiang707** [comment] 2022-08-16 05:11
We did change the manifest to have its own adaptation stream, which is visible on PotPlayer.

![image](https://user-images.githubusercontent.com/29428186/184801433-63345912-9c76-4b5d-b1d8-000edfcb73ef.png)

In avpro1.0 version I can use AndroidMediaPlayer's GetVideoTracksInfo() to get the correct VideoTracks and switch, but I can't reproduce this function in avpro2.0, please help me

**Comment by Andjiang707** [comment] 2022-08-16 08:28
In the log of avpro1.11.1 version,
Can correctly grab to VideoTracks: 5
But I am currently using the same source in 2.0 and can't get it,
Always VideoTracks: 1

![image](https://user-images.githubusercontent.com/29428186/184833353-4fcaa7ca-ebf0-4a2f-9f77-72d2799f179f.png)

**Comment by Chris-RH** [comment] 2022-08-16 12:34
Anything much more than what has been suggested will be implemented as a future enhancement

**Comment by Andjiang707** [comment] 2022-08-17 09:58
> 任何超出建議的內容都將作為未來的增強功能實施

Is there a video for testing multitracks that I can test

**Comment by Andjiang707** [comment] 2022-08-17 10:01
> > 任何超出建議的內容都將作為未來的增強功能實施
> 
> Is there a hls video for testing multitracks that I can test
