### ISSUE TITLE
AvPro not workin in ios 16.0

### ISSUE THREAD

**Issue by SubitPara** [RenderHeads/UnityPlugin-AVProVideo#1473] opened 2023-03-03 08:24 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Sound is playing but video is not playing in ios 16.0**
I am using unity version 2021.3.2 f1 and I am using Av pro for video playing. I am facing a problem while playing the video in IOS version 16.0. In this version sound of video is playing but video is not playing,.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.2 f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  trial version of Av pro
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**

https://user-images.githubusercontent.com/126850920/222669319-6d80e09b-307e-475f-969c-159c98fe6b2f.mp4

If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us

**Comment by MorrisRH** [comment] 2023-03-03 09:09
Possibly a duplicate of issue #1397

**Comment by Chris-RH** [comment] 2023-03-06 12:08
Did that help?

**Comment by SubitPara** [comment] 2023-03-07 03:31
I am looking into it.

**Closed** 2023-03-13 09:58 UTC
Labels: iOS
