### ISSUE TITLE
iOS Audio choppy sample rate

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [RenderHeads/UnityPlugin-AVProVideo#1043] opened 2021-12-13 14:49 UTC
**Describe the issue**
When a video is loaded (audio encoded in 48000Hz), the audio is choppy (with the Audio Mode: Unity).

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.20f1
 - AVPro Video version iOS 2.3.0-core
 - Operating system version: iOS
 - Device model: iphones
 - Video specs: (see attached)
       1280x720
       frame-rate: 25
       video codec: H264 - MPEG-4 AVC (avc1)
       audio codec: MPEG AAC Audio (mp4a)
       audio channels: 3F2R/LFE
       Sample rate: 48000Hz
       Bps: 32

**To Reproduce**
1. Create an Empty GameObject
2. Add a "Media Player"
3. Change the iOS "Audio Mode" to "Unity"
4. Add a "Apply To Material"
5. Add a "Audio Source"
6. Add a "Audio Output"

**Logs**
iOS logs:
```2021-12-13 11:58:49.905933+0100 SampleAVProVideo[4860:1606262] [Player] asset duration is  29.57 seconds
2021-12-13 11:58:49.905979+0100 SampleAVProVideo[4860:1606262] [Player] creating 3 player items
2021-12-13 11:58:49.907772+0100 SampleAVProVideo[4860:1606262] [Player] asset has metadata
2021-12-13 11:58:49.908493+0100 SampleAVProVideo[4860:1606262] [Player] asset is compatible with AirPlay
2021-12-13 11:58:49.908642+0100 SampleAVProVideo[4860:1606262] [Player] asset has 1 audio tracks
2021-12-13 11:58:49.908674+0100 SampleAVProVideo[4860:1606262] [Player] preparing audio capture...
2021-12-13 11:58:49.908779+0100 SampleAVProVideo[4860:1606262] [Player]   max channel count is 6
2021-12-13 11:58:49.908793+0100 SampleAVProVideo[4860:1606262] [Player]   capture buffer capacity is 432000
2021-12-13 11:58:49.909903+0100 SampleAVProVideo[4860:1606262] [Player]   done
2021-12-13 11:58:49.931857+0100 SampleAVProVideo[4860:1606262] [Player] player status is ready to play
2021-12-13 11:58:49.958969+0100 SampleAVProVideo[4860:1606468] [AudioCapture] audio requires resampling from 48000Hz to 24000Hz, audio output may stutter
2021-12-13 11:58:49.972576+0100 SampleAVProVideo[4860:1606262] [Player] player item status is ready to play
```

**Videos**
https://user-images.githubusercontent.com/63807677/145833446-59df683f-2f48-4a80-8472-dc88b677d5b3.mp4

**Comment by EricBeetsOfficial-Opuscope** [comment] 2021-12-14 14:49
🆙

**Comment by MorrisRH** [comment] 2021-12-15 13:27
The problem is the iPhone's audio output is stereo which is leading to some confusion inside the audio grabber as it's asking for 6 channels worth and only getting 2, hence sounding strangely garbled.

I'm looking for a solution but there are two work-arounds available to you:
1. Switch to using System Direct audio output mode,
2. Re-encode the video with a stereo audio track.

**Comment by EricBeetsOfficial-Opuscope** [comment] 2021-12-15 13:58
Hi !

Unfortunately, I cannot use the System Direct audio output mode (I want to record the videos audio and the microphone ..using AVPro Capture), and I am forced to use uploaded videos without modifying them..

**Comment by MorrisRH** [comment] 2022-01-05 17:04
A fix for this will be in the next release.

**Closed by MorrisRH** 2022-01-05 17:04 UTC
Labels: Bug 🐛, iOS, Fixed

**Comment by Days99** [comment] 2023-11-07 17:12
Hi Im still getting this warning, and im in the same situation as the previous example.
I don't notice the audio being choppy but it still gives me the warning, should I be concerned?

**Comment by MorrisRH** [comment] 2023-11-13 09:45
Hey @Days99,
The warning is due to the audio in your video having a different sample rate to Unity so we have to resample it before passing it through to Unity's audio system. On iOS the default sample rate is set to 24000 which is quite low for modern hardware so I would recommend upping It to 48000 and if you can, encode your video's audio at 48000 as well - that way we will not need to resample it.
