### ISSUE TITLE
Quest 3 - H264 video goes completely black after being paused for 5 seconds - hardware/OS issue

### ISSUE THREAD

**Issue by ForemanDev** [RenderHeads/UnityPlugin-AVProVideo#1660] opened 2023-10-11 17:38 UTC
**Describe the issue**
When using the standard AVPro VR sphere (Sphere-ApplyToMesh) and pausing the video, the video sphere suddenly turns black after about 5 seconds of being paused. Expected behavior is for the video to remain on the "freeze frame" when paused. This issue does NOT occur on the Quest 2. It only occurs on the Quest 3. I used Android Logcat to view logs while the app was running and found something that might be suspect (image attached) although I am not sure what to make of it. When the video is un-paused, the black screen goes away and it resumes playing the video without issue. There are no audio/video stutters on the Quest 3 - playback appears to be smooth besides the video turning black after being paused for 5 seconds.

We use a mechanic where the video is paused to allow the user to answer an in-VR survey question. We need the video to hold on the freeze frame when paused, but now it turns black after 5 seconds, leaving the user in darkness. Our team would greatly appreciate a fix (or even a short-term "hacky" workaround recommendation) because this issue disrupts the experience for our users.

I am happy to show the issue directly to a member of the AVPro team if necessary, via a Quest App Lab alpha channel build for the Meta Quest 3.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.48f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.4
 - Operating system version: Version: 57.0.0.279.669.521490460 | Runtime Version: 57.0.0.279.669.521489676 | OS Version: SQ3A.220605.009.A1
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size):
        - 7680x3840, 29.97 fps, H264 MPEG-4 AVC, 954 MB, 6:38 duration
        - 5760x2880, 29.97 fps, H264 MPEG-4 AVC, 2.63 GB, 4:12 duration
        - See attached images for further video information (via VLC).

**To Reproduce**
1. Create a new Unity project (v2020.3.48f1) and set up AVPro using the sphere mesh.
2. Set up the video player with a 7680x3840 resolution video (the issue also happened with a 5760x2880 video)
3. Create functionality to pause the video, maybe a minute and a half into it.
4. Create an Android Quest build.
5. Load onto a Meta Quest 3 - observe that the video sphere turns black after being paused for about 5 seconds.
7. Load onto a Meta Quest 2 - observe that the video sphere does NOT turn black after being paused.
8. Use Android Logcat (there is a Unity plugin for this) to observe error log messages related to AVPro during playback/pause.

**Logs**
Attached.

**Screenshots**
Attached.

**Videos**
Happy to provide privately. Happy to provide an app build privately also.

![Video_01_Info_8k](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/49407845/8883f4da-a787-43e7-b5b9-7125c1a09d5f)
![Video_02_Info_6k](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/49407845/1125c073-fbab-4b80-8885-c30b6c76c152)
![Android Logcat AVPro Error](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/49407845/397a7b6a-bae2-4447-ac23-213979bbf195)

**Comment by ForemanDesigns** [comment] 2023-10-11 21:10
To add to the above, I also just had an occurrence where the video did not resume playing when it was un-paused. The events leading up to this are as follows:

1. The video was played from the beginning.
2. The video was paused about 65 seconds in.
3. After waiting about 5 seconds, the video was played again at about the exact moment when the black screen kicked in.
4. The video remained forever stuck on the black screen rather than successfully playing again.

**Comment by Chris-RH** [comment] 2023-10-12 08:55
Hi, 

We don't have a Quest 3 to test with as they are very new.

1. Can you reproduce this just using a fresh project and the AVPro demo scenes?
2. Are you playing local or streamed media? Is it reproducible with both?
3. Have you tried different media? Lower resolutions? Different video codecs?
4. Have you tried without audio?
5. Could you provide a full logcat from before you pause the media?

**Comment by ForemanDesigns** [comment] 2023-10-13 21:25
Hi @Chris-RH, I have done some more testing and have narrowed it down to the **H.264 codec**. The H.265 codec appears to have no issue. Furthermore, this appears to be a hardware/OS-level issue specifically with the Quest 3. I have attempted to post about it on the Meta Quest Community Forums, but it keeps getting marked as spam (maybe because of the long length of my post). I wish that Meta had an official bug reporting system. 

Anyways, I will copy what I attempted to post on the Meta Community Forums so that the information is visible here (see below) and I am going to see if I can send it to Meta Quest Support via DM instead of a forum post.

Because this appears to be instability with the Meta Quest 3, please do what you please as far as this issue report is concerned, but please remain aware that this problem may affect the Meta Quest 3 users of any AVPro-powered Unity app until Meta fixes things.

====== Message for Meta Community Forums ======

Hello! Our team has been developing a 360 video-based app for Quest (using Unity game engine). After getting Quest 3 headsets, we've discovered evidence that video playback is unstable on the Quest 3, when we had no issues on the Quest 2 with the same APK build.

Specifically, the H.264 codec is not stable on the Quest 3 and we are having issues with the video either turning black when paused (via AVPro Exoplayer Unity plugin), or not being able to resume playing after being paused (via the built-in Unity video player or Meta Quest TV app). The H.265 codec appears to work just fine, however we aren't always able to use this format and we want H.264 to work. The issues for H.264 are present both in our Unity app and also in the Meta Quest TV app, indicating this is a hardware/OS-level issue with the decoder for H.264 video only on Quest 3, and not on Quest 2. I have been able to prove this via Android Logcat error messages I have captured while playing video (see below).

Below are my observations when testing video playback on the Meta Quest TV app, Unity via AVPro, and Unity via the built-in Unity video player. The below is consistent when using either 8k (7680x3840) or 5.7k (5760x2880) 2D (equirectangular) 360 video at 29.97 fps. [@MetaQuestSupport](https://communityforums.atmeta.com/t5/user/viewprofilepage/user-id/16864) or [@Ryanality](https://communityforums.atmeta.com/t5/user/viewprofilepage/user-id/1372579) could you please pass this important information along to the appropriate engineering teams?

Meta Quest TV
- Quest 3:
     - H.264 - After pausing video, waiting at least 5 seconds, then selecting the play button again, the video freezes on the paused frame and does not resume playing. Audio does play, but the video remains frozen.
     - H.265 - No issues.
- Quest 2:
     - H.264 - No issues.
     - H.265 - No issues.

Unity - AVPro Plugin (Exoplayer)
- Quest 3:
     - H.264 - After pausing video, the video turns completely black after about 5 seconds. Expected behavior is of course to hold the paused frame, but the video blacks out after 5 seconds. When playing the video again, the black screen does go away and the video carries on playing.
     - H.265 - No issues.
- Quest 2:
     - H.264 - No issues.
     - H.265 - No issues.

Unity - Unity's Built-In Video Player
- Quest 3:
     - H.264 - After pausing the video, waiting at least 5 seconds, then selecting the play button again, the video shows the next couple of frames for a split second and then freezes completely. Audio also does not resume playing.
     - H.265 - No issues.
- Quest 2:
     - H.264 - No issues.
     - H.265 - No issues.

As you can see above, the issues are isolated to H.264 codec video playback on the Quest 3. Below are the "suspect" Android Logcat messages that I captured:

Android Logcat messages (Quest 3, H.264 video playback):

Meta Quest TV:
[VideoDirectDecoder] unexpected video info code: -10000
[NdkMediaCodec] sf error code: -38
[VideoSession] 1697223336118080000 - state check failed: playing --> ready
[CCodecBufferChannel] [c2.android.aac.decoder#221] MediaCodec discarded an unknown buffer

Unity - AVPro Plugin (Exoplayer):
[MediaCodecVideoRenderer] Video codec error
[MediaCodecVideoRenderer] android.media.MediaCodec$CodecException: Error 0x80000000
[MediaCodecUtil] Unknown AVC level: 60
[ExoPlayerImplInternal] Playback error
[ExoPlayerImplInternal] xom.google.android.explr2avp.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D403C, -1, null, [7680, 3840, 29.970032, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
[ExoPlayerImpInternal] Caused by: com.google.android.exoplr2avp.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
[ExoPlayerImpInternal] Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
[MediaCodec] mapFormat: no mediaType information
[Codec2Client] query -- param skipped: index = 1107298332
[CCodecConfig] query failed after returning 19 values (BAD_INDEX)
[MediaCodec] flushMediametrics
[AVProVideo] Changing video size 5760x2880 to 0x0
[CCodecBufferChannel] MediaCodec discarded an unknown buffer
[System.out] AVProVideo error MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D403C, -1, null, [5760, 2880, 29.970032, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
[MediaMetricsManagerService] failed to get player_metrics_app_blocklist from DeviceConfig

Unity - Unity's Built-In Video Player
[CCodec] [c2.qti.avc.decoder] previous call to queue exceeded timeout
[MediaCodec] Codec reported error 0x80000000, actionCode 0, while in state 6/started
[MediaCodec] flushMediaMetrics
[QC2Comp] [avcD_24] Stats: Pending(10) i/p-done(6) Works: Q: 175/Done 166|Work-Rate: Q(0.0/s Avg=17.4/s) Done(0.000/s Avg=16.485/s)| Stream: 29.97fps 17.3Mbps
[mediametrics::Item] selfrecord: failed to record: {codec, (12-31 18:00:00.000), (, -1, -1), (android.media.mediacodec.codec=c2.qti.avc.decoder, android.media.mediacodec.encoder=0, android.media.mediacodec.errcode=-2147483648, android.media.mediacodec.errstate=STARTED, android.media.mediacodec.height=3840, android.media.mediacodec.latency.avg=683468, android.media.mediacodec.latency.max=779014, android.media.mediacodec.latency.min=231505, android.media.mediacodec.latency.n=44, android.media.mediacodec.latency.unknown=108, android.media.mediacodec.level=131072, android.media.mediacodec.lifetimeMs=10055, android.media.mediacodec.log-session-id=, android.media.mediacodec.low-latency.first-frame=-1, android.media.mediacodec.low-latency.off=0, android.media.mediacodec.low-latency.on=0, android.media.mediacodec.mime=video/avc, android.media.mediacodec.mode=video, android.media.mediacodec.profile=2, android.media.mediacodec.rotation-degrees=0, android.media.mediacodec.width=7680)}
[SurfaceUtils] disconnecting from surface 0xb4000073e9b73010, reason disconnectFromSurface
[QC2Comp] Mem-usage: [In-1D: 4 bufs 50.625 MB] [1D-29: 16 bufs 0.250 MB] [2D-30: 16 bufs 677.812 MB] | Total: 728.688 MB
[QC2Comp] [avcD_24][RUNNING] comp.release() is called without comp.stop()
[CCodecBufferChannel] [c2.qti.avc.decoder#208] MediaCodec discarded an unknown buffer
[BufferQueueProducer] [SurfaceTexture-183-6851-0](id:1ac300000002,api:0,p:-1,c:6851) cancelBuffer: BufferQueue has no connected producer
[NdkMediaCodec] sf error code: -38
[Unity] AndroidVideoMedia::Flush CodecFlush error: -10000

**Comment by Chris-RH** [comment] 2023-10-15 11:53
Have you tested flat videos (ie not equirectangular) and also lower res videos?

**Comment by ForemanDesigns** [comment] 2023-10-16 20:53
Hey @Chris-RH! I haven't tested any flat content since our app is only designed for 360, however the behavior is consistent for mono equirectangular 8k (7680x3840) or 5.7k (5760x2880) video. I did test a draft low-resolution (1920x960) video and that did not appear to have any problems. Videos are being played from local storage - we have a system that pre-downloads the videos in their entirety onto the device before playing them.

Our short-term fix is to encode our own videos with H.265 codec. Currently we have control over all of the video content in our own app, so this will work for us as a fix for now. But this could be problematic for other video player apps that allow users to load their own H.264 encoded videos. That being said, Meta's own "Meta Quest TV" app has issues with H.264 video playback when you pause and resume. I posted in the community forums - I hope a Meta engineer sees it.

**Comment by Chris-RH** [comment] 2023-10-17 08:16
Thanks for all of the info.  I'm glad that you have a workaround at least.  
I'm keeping an eye on your thread and Dave's (white pixels) thread on the Meta forum.

**Comment by ForemanDesigns** [comment] 2023-10-17 18:04
You're welcome, and thank you for monitoring it @Chris-RH. I appreciate your help!

Just so that everything is connected, here is a link to the Meta forums post I made for this issue: https://communityforums.atmeta.com/t5/Quest-Development/H-264-Video-is-unstable-on-Quest-3-black-screen-freezing-No/td-p/1092223

**Comment by Chris-RH** [comment] 2023-10-18 08:22
This is an issue that will potentially effect quite a lot of users, so hopefully they will take it seriously.

**Comment by Chris-RH** [comment] 2023-11-02 08:31
Hi @ForemanDev, 
As you've established that this looks to be a hardware issue, I'm going to close it here.  I will keep an eye on your meta thread though.

**Closed by Chris-RH** 2023-11-02 08:31 UTC
Labels: Android
