### ISSUE TITLE
Native Crashes on iOS related to AVPro Video

### ISSUE THREAD

**Issue by PhannGor** [RenderHeads/UnityPlugin-AVProVideo#978] opened 2021-10-20 14:22 UTC
**Describe the issue**

We're noticing some weird native crashes in Unity Dashboard that are related to AVPro Video that we could not explain. Maybe you could help and shed some light here.

**Your Setup:**

 - Unity version: 2019.4.23f1
 - AVPro Video version: 2.2.1
 - Operating system version: iOS 14.6
 - Device model: iPhone10,6 / Apple A11 GPU

**Logs**

```
Native Crash - Unknown Function (/private/var/containers/Bundle/Application/25EDE754-4E1A-49FD-9817-1FC81A7E036B/frever.app/Frameworks/AVProVideo.framework/AVProVideo)
```

Stack Trace: https://pastebin.com/uu6Z5z6j

Log1: https://pastebin.com/BiFnNqqp
Log2: https://pastebin.com/uMYTF0Fi
Log3: https://pastebin.com/Zh6hDWvC

**Comment by aengmo1** [comment] 2021-11-01 10:51
Can just say that I got the crash now on the latest version of Ultra on iOS, so that update didn't help

**Comment by aengmo1** [comment] 2021-11-01 11:16
Here is a log from my device relating to the crash. Hope it helps! 
[frever 2021-11-01, 11-47.crash.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7452629/frever.2021-11-01.11-47.crash.zip)

**Comment by aengmo1** [comment] 2021-11-01 11:23
Here is the HLS manifests from the video too, that was playing when the crash happened. 
[Archive.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7452674/Archive.zip)
.

**Comment by aengmo1** [comment] 2021-11-03 17:56
Hi,

Any updates here? I think one clue might be the looping? I noticed that the crash happened at the end of both the videos.

**Comment by MorrisRH** [comment] 2021-11-03 18:28
> Here is the HLS manifests from the video too, that was playing when the crash happened.
> [Archive.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7452674/Archive.zip)
> .

Afraid I cannot see the crash in there or what caused it.

> Here is the HLS manifests from the video too, that was playing when the crash happened.
> [Archive.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7452674/Archive.zip)
> .

This looks perfectly ordinary to me so no clues there.

Are you able to share some of the media that is causing an issue with us? You don't have to provide access to your servers if that's a problem, just zipping up some of the HLS media would be fine. If so please send them to unitysupport@renderheads.com quoting this issue.

**Comment by aengmo1** [comment] 2021-11-03 22:55
Sent to the email. Hope we find the cause. Thanks!

**Comment by MorrisRH** [comment] 2021-11-04 10:58
Thanks for sending through the media. It's playing back fine for me here so I think we can now rule that out as the potential cause.

I think the issue is tied to the player instance reuse which is where I'm now focusing my efforts. There is definitely an issue when a player is reused very quickly, i.e. less than ~400ms between OpenMedia calls, so if you can prevent that from happening you may be able to work around the issue for now.

**Comment by aengmo1** [comment] 2021-11-04 11:07
Thanks for the update. Let us know if you have found the cause. So you basically suggest that if we include a delay (so it is above +400ms) when a video is looping that can avoid the issue?

**Comment by MorrisRH** [comment] 2021-11-08 11:54
Linking issue #853

**Comment by aengmo1** [comment] 2021-11-08 12:03
Hi, I saw not in the thread for 853 but for #1000 that you are working on a fix for this bug? Is that true?

**Comment by MorrisRH** [comment] 2021-11-08 12:13
Yes, just linking the issues up as I think they're the same. It's not a trivial fix though so is taking some time and the logs you pasted don't quite match what I'd expect to see so it might not solve the issue you're having.

**Comment by MorrisRH** [comment] 2021-11-12 09:50
Not related to issue #853

**Comment by MorrisRH** [comment] 2021-12-02 11:43
Closing this issue as I believe it is now fixed.

**Closed by MorrisRH** 2021-12-02 11:43 UTC
Labels: iOS, need more info 🤷
