### ISSUE TITLE
No finishedPlaying event at sometimes in android or ios #3.0.3

### ISSUE THREAD

**Issue by DreamYao** [RenderHeads/UnityPlugin-AVProVideo#1908] opened 2024-06-20 08:30 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.
not reproduce every time, but the frequency is very high
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11754273/dac922e8-7fb2-4ac3-8ce3-f9e0821e700b

**Your Setup (please complete the following information):**
 - Unity version:  2023.3.21f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.3 core 
 - Operating system version:  all android or ios
 - Device model:  such as iphone11 and android 10
 - Video specs (resolution, frame-rate, codec, file size): attached file

**To Reproduce**
1. just play
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by DreamYao** [comment] 2024-06-20 09:28
here is code:
mediaPlayer.Loop = false;
                mediaPlayer.OpenMedia(new MediaPath("speak_03.mp4", MediaPathType.RelativeToStreamingAssetsFolder), autoPlay: true);
 When the issue is reproduced, the video is playing with loop

**Comment by Chris-RH** [comment] 2024-06-20 09:41
There is no FinishedPlaying event when the video is looped. [See documentation](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/feature-events.html#events-1).

**Comment by DreamYao** [comment] 2024-06-20 10:20
mediaPlayer.Loop = false; 
My mediaPlayer loop is false

**Comment by Chris-RH** [comment] 2024-06-20 10:25
You've just said "When the issue is reproduced, the video is playing with loop", so are you saying that it is set to not loop, but does loop sometimes?

**Comment by DreamYao** [comment] 2024-06-20 10:32
mediaPlayer.Loop = true;
mediaPlayer.OpenMedia("01.mp4", autoPlay: false);
mediaPlayer.Pause();  

// then wait a few minutes 
mediaPlayer.Loop = false;
mediaPlayer.OpenMedia("02.mp4", autoPlay: false);

 02.mp4 play loop

**Comment by MorrisRH** [comment] 2024-06-20 17:17
Android:
- A fix for this issue will make it into the next release (version 3.0.4)

iOS:
- Could not reproduce

**Comment by Chris-RH** [comment] 2024-06-21 13:14
AVPro Video version 3.0.4 has been released.  Please let us know if it has not fixed your issue.

**Closed** 2024-06-27 09:09 UTC
Labels: Android, Fixed
