### ISSUE TITLE
An error occurred while playing the video on the PC virtual machine

### ISSUE THREAD

**Issue by MYR1105d** [RenderHeads/UnityPlugin-AVProVideo#1960] opened 2024-08-06 08:17 UTC
**Describe the issue**
An error occurred while playing the video on the PC virtual machine. The video is loaded locally using the StreamingAsset method.But it runs normally on a standard Android device.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.3.6f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition 3.0.8

**Logs**

```
Exception: AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.DefaultCompany.StudyProject-1/lib/arm/libAVProVideo2Native.so" has unexpected e_machine: 40


java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.DefaultCompany.StudyProject-1/lib/arm/libAVProVideo2Native.so" has unexpected e_machine: 40
java.lang.Runtime.loadLibrary0(Runtime.java:989)
java.lang.System.loadLibrary(System.java:1562)
com.renderheads.AVPro.Video.Manager.<clinit>(SourceFile)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.access$300(Unknown Source)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:154)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.NewObject (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.PlatformMediaPlayer+Native.AVPPluginBootstrap () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.PlatformMediaPlayer..cctor () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'RenderHeads.Media.AVProVideo.PlatformMediaPlayer' threw an exception.
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)

```

**Comment by Chris-RH** [comment] 2024-08-06 09:57
What device are you running it on?
What VM are you using?

**Comment by MYR1105d** [comment] 2024-08-07 02:41
It's the pc Android emulator.

**Comment by Chris-RH** [comment] 2024-08-07 08:22
What hardware are you running?
Which OS version?
Which android emulator software are you running?
What device are you trying to emulate?

**Comment by MYR1105d** [comment] 2024-08-07 09:55
Using Windows 10 system, some Android simulators have some problems, such as: night God simulator, thunder simulator, simulator website: https://www.yeshen.com, https://www.ldmnq.com/?n=401674

**Comment by Chris-RH** [comment] 2024-08-08 08:18
Are you saying that some simulators are working?
Have you tried the simulator in Android Studio?
Is there a reason that you are testing on simulators rather than actual devices?

**Comment by MYR1105d** [comment] 2024-08-08 11:41
Android Studio has not been tried, but tested on the emulator because some players will use the emulator to play.

**Comment by buoutuanzi** [comment] 2024-08-09 01:37
Also found it crash in MUMU simulator https://mumu.163.com/

**Comment by Chris-RH** [comment] 2024-08-09 11:11
The problem is that our asset is designed to be used on physical devices, not emulators.  Android Studio android simulator is ok for doing some testing on, but the end target should be a physical device.  Is there a reason that you are not targeting the platforms that they are using emulators on?

**Comment by buoutuanzi** [comment] 2024-08-12 03:23
> The problem is that our asset is designed to be used on physical devices, not emulators. Android Studio android simulator is ok for doing some testing on, but the end target should be a physical device. Is there a reason that you are not targeting the platforms that they are using emulators on?

Those who are not familiar with PC tend to choose using an emulator to play the mobile version of the game rather than downloading the PC version, so we hope to support emulators.

**Comment by Chris-RH** [comment] 2024-09-02 11:13
1. Can you reproduce this in a new project running only the AVPro Video demo scenes?
2. Have you tried both Vulkan and OpenGLES?
3. Are you building Mono or IL2CPP?
4. Have you tried streaming videos ([test streams here](https://renderheads.com/content/docs/AVProVideo-v3/articles/feature-streaming.html#test-streams))
5. Are you having the issue with all of the emulators you have tried, or just some of them? Which ones work/don't work? Are you getting the same error messages?

**Comment by Ste-RH** [comment] 2024-09-09 10:19
We think this is the same issue as #1994 and hope to have a fix for this in the next release (v3.0.11).

**Comment by MorrisRH** [comment] 2024-09-09 14:19
We've fixed the issue with running using the Google Android emulator which we hope will resolve the issues seen with other emulators, this will make it into the next release (3.0.11).

**Comment by Ste-RH** [comment] 2024-09-12 16:04
@MYR1105d AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.

**Closed** 2024-09-19 08:01 UTC
Labels: Android, Fixed
