### ISSUE TITLE
 monoscopic mode for stereo video.

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1685] opened 2023-11-08 16:08 UTC
I am considering AVpro for my project for Oculus. But I didn't find a way to enable monoscopic mode (disable stereo). This is necessary so that there is no discomfort eyes when I show the UI on top of 180/360 videos. Is there such a possibility?

**Comment by Ste-RH** [comment] 2023-11-08 17:00
Duplicate of #1678

**Closed by Ste-RH** 2023-11-08 17:00 UTC
Labels: question
