### ISSUE TITLE
support Linux platform please!!

### ISSUE THREAD

**Issue by Alinccc** [RenderHeads/UnityPlugin-AVProVideo#1656] opened 2023-09-26 03:54 UTC
Need to play video in linux system showroom computer program, but did not find a compatible tool, please support it!!

**Comment by Chris-RH** [comment] 2023-09-26 06:23
Duplicate of https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1491

Unfortunately, there are currently no plans for Linux support as it is difficult to ensure compatibility across such a wide range of distributions.
We are a small team so we can't easily add support for all platforms. Linux is also a bit of a tricky one because it doesn't have any built-in codec support, so we would have to add support for VLC/FFMPEG or something like that, and hardware decoding can be tricky too I suspect. We just haven't had the resources to investigate this.

Kind regards,
Chris

**Closed by Chris-RH** 2023-09-26 06:23 UTC
Labels: duplicate

**Comment by avicarpio** [comment] 2023-09-27 10:15
I think that if you focus only on Ubuntu distribution, with ffmpeg and NVENC for hardware decoding, it wouldn't be more difficult as it could be on Windows or MacOS. I hope you will be motivated to investigate it soon as you will gain many more users!

**Comment by Chris-RH** [comment] 2023-09-27 13:14
Its highly unlikely to happen I'm afraid.  We are a very small team and simply do not have enough hours in the day to start developing on and supporting yet another platform.
