### ISSUE TITLE
HLS+AES-128 plays audio only with iOS 16

### ISSUE THREAD

**Issue by dwenegar** [RenderHeads/UnityPlugin-AVProVideo#1250] opened 2022-08-08 08:54 UTC
**Describe the issue**

Blank screen when streaming multi-chunk videos on iOS 16 beta.

**Your Setup (please complete the following information):**

 - Unity version: 2020.3.36f1
 - AVPro Video version:
 	- 2.5.7 trial
 - Operating system version: iOS 16.0
 - Device model: iPhone 13 Pro Max (but it happens on any device)
 - Video specs (resolution, frame-rate, codec, file size):
	- frame-rate: 60
	- codec H264 - MPEG-4

Logs look normal but `_state.status.HasUpdatedTexture()` at `AppleMediaPlayer.cs:312`　returns always `false`.

**Comment by Chris-RH** [comment] 2022-08-08 11:35
Hi @dwenegar,

Could you try our Demo_MediaPlayer scene with the video samples we have included?
Are there any other file types that are not playing?
Do you have a device with an earlier version of iOS to test the files on?

**Comment by dwenegar** [comment] 2022-08-08 11:51
Hi @Chris-RH 

> Could you try opening a new project with our Demo_MediaPlayer scene with the video samples we have included?

All the video samples play correctly.

> Are there any other file types that are not playing?

So far only one specific HLS stream.
Additionally, the very same stream not playing correctly with AVPro, plays correctly in Safari and VLC.

> Do you have a device with an earlier version of iOS to test the files on?

Yes: non-beta versions of iOS do not manifest the described problem.

**Comment by Chris-RH** [comment] 2022-08-08 12:04
OK, thank you very much for the information.
Unfortunately we cannot support for beta releases of OSs, as there are likely to be quite a few changes before the final version is released.  
We will be supporting iOS 16 when it comes out officially, so we will look out for this if the problem is still occurring.

**Comment by mateus-capelesso** [comment] 2022-09-16 02:34
Hello @Chris-RH, I think that this issue could be reopened. After the update to iOS 16, that was released on September 12th, all the HLS stream videos are not working. 
All the logs looks normal, just like @dwenegar mentioned.

**Comment by Chris-RH** [comment] 2022-09-16 06:54
Thanks.
It would be great if you could provide a bit more information
Unity version:
AVPro Version:
Device
What files you are having problems with (resolution, type etc )
A full log would be really helpful if you can provide one, please

**Comment by mateus-capelesso** [comment] 2022-09-16 10:47
Sure @Chris-RH 

Unity Version: 2021.3.5f1
Device: iPhone 13 Pro (iOS 16)
HLS encrypted videos are not being rendered, but I can hear them. 
All other type of videos (non HLS encrypted are working fine).
All of our videos are 1080p.

I'm sending two log files. The full one has all the logs from the device. The other one, just the logs from our application.
[avpro-ios16.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9583121/avpro-ios16.log)
[avpro-ios16-full.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9583122/avpro-ios16-full.log)

**Comment by Chris-RH** [comment] 2022-09-16 10:49
Brilliant, thank you so much @mateus-capelesso.
Our iOS dev is away until Tuesday (Its a Bank holiday here in the UK), so he'll look at it then.

**Comment by MorrisRH** [comment] 2022-09-20 08:22
Hey @mateus-capelesso, could you tell me more about how the HLS streams are being encrypted? Are you able to share one of these streams so that we can test it here? Thanks!

**Comment by mateus-capelesso** [comment] 2022-09-20 10:22
Hey @MorrisRH, we are using AES-128 + CloudFront signed cookies.

**Comment by MorrisRH** [comment] 2022-09-20 12:22
I've reproduced the issue here and unfortunately it does seem to be something in the internals of AVFoundation. In essence the low-level player instance does not produce frames when playing an AES-128 encrypted HLS video when running iOS 16.

I've opened an issue with Apple so hopefully they will get back to me with something.

For now I'm afraid that we cannot support HLS+AES-128 on devices running iOS 16.

**Comment by bgalerani94** [comment] 2022-09-28 10:11
Hello,

Is there any update on this? 

I'm having the same problem here and my app has a lot of these ):

Thanks!

**Comment by Chris-RH** [comment] 2022-09-28 10:58
We're still waiting to hear back from Apple.  We'll keep this thread updated when we know anything more :)

**Comment by guerwan** [comment] 2022-09-28 17:25
We are facing the same issue here.
When we try to play the live stream in a native iOS app we don't have the issue though.

**Comment by guerwan** [comment] 2022-09-29 07:58
@MorrisRH you're right we are using AVPlayerViewController.

**Comment by guerwan** [comment] 2022-10-05 10:12
@MorrisRH Apparently the issue has been fixed now in iOS 16.1 beta 4.

**Comment by Chris-RH** [comment] 2022-10-05 10:34
That sounds promising. Hopefully it won't be too long until 16.1 is released into the wild and we shall see :)

**Comment by Rex-121** [comment] 2022-11-01 09:26
already fixed?

**Comment by MorrisRH** [comment] 2022-11-14 12:40
A quick test using the latest AVPro Video (version 2.6.6) and iOS 16.1 shows that this is now fixed.

**Closed by MorrisRH** 2022-11-14 12:40 UTC
Labels: Bug 🐛, iOS, pinned
