### ISSUE TITLE
Android. The playback doesn't pause during the incoming call.

### ISSUE THREAD

**Issue by PopovYuriy** [RenderHeads/UnityPlugin-AVProVideo#1967] opened 2024-08-15 15:31 UTC
**Describe the issue**
The video playback doesn't pause during an incoming call on Android devices, while on an iOS device it works fine.

 - Unity version: 2022.3.40f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.6 Core edition
 - Operating system version: 14
 - Device model: OPPO CPH2591

**To Reproduce**
1. Run the app with the AVPro player.
2. Play a video.
3. Get an incoming call.

**Logs**
Error Unity Exception: No such proxy method: UnityEngine.AndroidJavaProxy.onAudioFocusChange(System.Int32)

**Comment by Chris-RH** [comment] 2024-08-16 12:23
Are you expecting the video be paused for the duration of the call, even if brought back into focus?

1. Are you using Exoplayer or Android mediaplayer?
2. Are you using Vulkan or OpenGLES?
3. Can you reproduce it in a new project running only the mediaplayer demo scene?
4. Is it reproducible on other android devices?
5. Can you provide a full, unfiltered logcat in txt format?

I can't reproduce this in a new project using the mediaplayer demo.  When answering the call and the app is out of focus, the video is paused.  Playback will resume once the call has ended and the app is refocused.  The video will also resume during the call if I bring the app back into focus, but the audio will not play.  This is using Unity 2021.3.29 and AVPro Video version 3.0.8.

**Comment by Chris-RH** [comment] 2024-08-16 12:50
It paused when I answered the phone and the app was backgrounded.  My device doesn't show backgrounded apps when on a call, unless you refocus them on purpose.

**Comment by Chris-RH** [comment] 2024-08-16 13:15
So you wish it to be paused from the moment an incoming call pops up, even if it isn't answered?

**Comment by PopovYuriy** [comment] 2024-08-16 14:00
Right. As I mentioned before, iOS devices have this behavior, it looks like the player cares about it.

**Comment by PopovYuriy** [comment] 2024-08-22 11:07
Hi @Chris-RH
Would you happen to have any updates?

**Comment by Ste-RH** [comment] 2024-08-27 15:00
I think we can accommodate this such that pausing videos rather than just muting them is the default behavior on Android.  This will be included in the next release (v3.0.9).  We are aiming to release it later this week.

**Comment by Ste-RH** [comment] 2024-08-30 14:20
AVPro Video v3.0.9 has just been released.  Do let us know if the issue has been fixed for you.

**Closed** 2024-09-06 09:25 UTC
Labels: Android, Fixed

**Comment by Ste-RH** [comment] 2024-10-10 13:51
NOTE: The fix used to address this issue caused #2026 and so a different fix has been applied for this issue now.
