### ISSUE TITLE
4k video on Quest/Android looks pixelated, is there a way to smooth it using mipmapping?

### ISSUE THREAD

**Issue by LukeFarrer** [RenderHeads/UnityPlugin-AVProVideo#441] opened 2020-08-13 11:33 UTC
Hi there!

I am using the latest version of AVProVideo with Unity 2018.3.6f1 on Windows 10. 
I wish to use it in VR on the Oculus Quest.
I notice the 4k videos (h265 encoding of 4096x4096 textures) look pixelated. This is due I think to too many pixels being rendered in a given space, due to a lack of mipmapping. (You can reproduce this issue very similar for a still texture, just by switching off mipmapping.)
To get around this problem one can render an array of individual mipmapped texture frames. The result looks great but the memory overhead is too great and I really require a video solution.
I notice that AVProVideo for Windows has a Mipmap option. 
Is there a similar feature for Android or is there another way to reduce this pixelation? (I have tried Trilinear and Aniso settings but they don't do that much).

Thanks
Luke Farrer

**Comment by AndrewRH** [comment] 2020-08-26 13:32
Yes we are looking at adding mipmap support in the future.  For Android based mobile VR headsets this might add too much overhead though - so it may be better to use a video  resolution that better matches the headset.  I wouldn't have thought that 4096x4096 would downscale during rendering if you are mapping to a sphere - unless perhaps you're not doing stereo, in which case your vertical resolution may just be too high and that could be causing the aliasing.

**Comment by Chris-RH** [comment] 2023-06-27 12:19
Duplicate of https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/107

**Closed** 2023-06-27 12:20 UTC
Labels: duplicate, enhancement 🚀, Android
