### ISSUE TITLE
Increase Twitch HLS  buffer size

### ISSUE THREAD

**Issue by schemaxxx** [RenderHeads/UnityPlugin-AVProVideo#117] opened 2019-07-10 15:58 UTC
Problem description:

I'm trying to display streams from Twitch via m3u8 URL. This is mostly working perfectly fine.
In rare occasion Streams with a bit worse connection keep stalling however. 
Is it possible to increase buffer size for streaming, or do I have to manage that in a different location?

Device (which devices are you having the issue with - model, OS version number):

Windows

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

One video, 1920x1080, streamed from twitch

System Information:

AVPro Video: plugin v1.9.17 scripts v1.10.0
Target Platform: Standalone
Unity: v2019.1.0f2 WindowsEditor
OS: Desktop - MS-7A68 (MSI) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz - 8 threads - 32722KB
GPU: NVIDIA GeForce RTX 2070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8031KB - 16384

**Comment by ignacio-fsstudio** [comment] 2019-08-13 17:22
Any update on this? I'm encountering that the buffering on my videos stops until the playback catches up to it and then it resumes buffering, which means my playback stops several times per playback.

It would be great if we could have finer control of the buffering process!

**Comment by AndrewRH** [comment] 2019-08-14 19:52
Yeah, it's one of the weak points right now - there is no control over buffering.  This is something we aim to improve in the future, but we don't have anything in the works right now.

**Comment by Carwashh** [comment] 2020-09-04 12:57
We're working on an app where we stream videos from an S3 server, playing 360 videos at 3840x1920 using H.264 and AAC. We get reports from users on both Android and iOS devices of continual stop/starting to buffer as they watch the videos, we do not believe the cause of the problem to be bandwidth related as this issue is happening for users on WiFi with 100MB connections.

Does the video carry on buffering ahead of where the user is currently watching?

I see from this thread, a year ago there was no control over buffering, has this changed at all?

Ideally, what we'd like to be able to do is:
1- See how much of a video is buffered at any given time.
2- Dictate how much of the video should be buffered before playing.

**Comment by AndrewRH** [comment] 2021-12-08 16:25
Closing this old version 1.x issue.   In version 2 we have made many improvements.   If anyone is having issues with version 2 please open a new ticket.

**Closed by AndrewRH** 2021-12-08 16:25 UTC
Labels: enhancement 🚀, Windows, Version 1.x
