### ISSUE TITLE
[Android] Some textures not rendering in android build

### ISSUE THREAD

**Issue by Cobrakinggames** [RenderHeads/UnityPlugin-AVProVideo#2093] opened 2024-12-03 06:37 UTC
### Unity version

2023.2.20

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

3.1.3

### Device hardware

Unity

### Which Android OS version are you using?

8

### Unity Graphics API

OpenGLES 3

### Video API

MediaPlayer

### Texture format

BGRA

### Audio output

Unity

### Any other Media Player component configuration required to reproduce the issue.

No

### Any other component configuration required to reproduce the issue.

No

### The issue

@Ste-RH after i updated this https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/2081#issuecomment-2500966769  i got some weird issues  Like Some Images are automatically change in devices  please see the attached screenshot    please look both the image 1 is editor image and 1 is mobile  ![Media](https://github.com/user-attachments/assets/606b2a5c-dbb5-44e8-bd49-3128b97e7b7c) ![undefined](https://github.com/user-attachments/assets/7bf2eb1e-c515-4e9d-822c-a1c6ea7b6eb3)  ![Capture](https://github.com/user-attachments/assets/86637ed2-299b-44e1-9969-1e3c3c5ec9d7)

**Comment by Chris-RH** [comment] 2024-12-03 11:52
So the only thing that you changed was your gradle, in the way that was prompted by @Ste-RH in the previous thread?

**Comment by Cobrakinggames** [comment] 2024-12-03 12:00
Yes

**Comment by Chris-RH** [comment] 2024-12-03 12:11
Could you send us the project please to unitysupport@renderheads.com
If you cannot send this project, could you make a simple project that reproduces the issue please. 
:)

**Comment by Cobrakinggames** [comment] 2024-12-03 12:19
IS that Ok if I share Apk To You  Because it's only happened in mobile not in editor

**Comment by Chris-RH** [comment] 2024-12-03 12:29
no, we need to look at the project

**Comment by Cobrakinggames** [comment] 2024-12-03 12:45
For confidentiality, we cannot share the project as it contains numerous secret keys.
 is there any other solutions can we connect on teams or some where else

**Comment by Chris-RH** [comment] 2024-12-03 12:50
That's fine.  You can just make a new project with AVPro Video and as little changes in it that will reproduce the issue when we build it for android.

**Comment by Cobrakinggames** [comment] 2024-12-03 13:02
https://we.tl/t-yJM07B1Ebn

here is the apk For testing

**Comment by Ste-RH** [comment] 2024-12-03 13:04
As stated, please DO NOT post APKs (or project files).  Email them over.

**Comment by Chris-RH** [comment] 2024-12-04 09:13
Hi, 

We can't really do anything until we have a simple project that reproduces the issue.  Please send a project to unitysupport@renderheads.com

**Comment by PradeepSymb** [comment] 2024-12-06 05:56
@Chris-RH 
We have sent the project to unitysupport@renderheads.com. Kindly help us identify this issue at the earliest, as we are currently blocked due to AVPro.

**Comment by Ste-RH** [comment] 2024-12-10 11:37
This issue only affected OpenGLES (specifically when not using OES mode).  It is quite fringe and only seen on older devices where projects are using a lot of texture based UI.

There will be a fix for this included in the next release.

**Comment by Ste-RH** [comment] 2024-12-10 12:24
@Cobrakinggames We would recommend that, yes.  As I stated in my email to you, OES mode has many benefits over BGRA.  We would recommend it by default if there is no reason for your project not to use it.

**Comment by 1a1aca** [comment] 2024-12-14 03:34
> @Cobrakinggames We would recommend that, yes. As I stated in my email to you, OES mode has many benefits over BGRA. We would recommend it by default if there is no reason for your project not to use it.

How to change to OES mode? When will the new version be released?

**Comment by Chris-RH** [comment] 2024-12-14 08:43
Info on [OES rendering](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/platform-android.html#oes-playback-path).

We are working to get the next version out ASAP.

**Comment by 1a1aca** [comment] 2024-12-15 03:00
> 我们建议，是的。正如我在给您的电子邮件中所说，OES 模式比 BGRA 有很多好处。如果您的项目没有理由不使用它，我们会默认推荐它。

I tried it, but it doesn't display properly on Apply To Mesh and Apply To Material. Everything is fine in 2.9.x. Why did you make such a change? In addition, this version will crash directly when opening some 8K videos.

**Comment by 1a1aca** [comment] 2024-12-15 03:04
> > 我们建议，是的。正如我在给您的电子邮件中所说，OES 模式比 BGRA 有很多好处。如果您的项目没有理由不使用它，我们会默认推荐它。
> 
> 如何更改为 OES 模式？新版本何时发布？

The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low.

**Comment by Ste-RH** [comment] 2024-12-16 09:33
If by your question you are asking why we made a big change between v2.x
and v3.x, it is because we wanted to add Vulkan rendering support and this
meant we needed to change the entire rendering pipeline on Android.  The
change also allowed us to add a good number of other features to the plugin
that were impossible to do in v2.x.

There is no reason OES should not work with the fully licensed version of
AVPro Video. It will *not* work with the trial version.

For ApplyToMesh/Material you will need to change the shader you are using
to the OES version. You will not get video frames rendering if you do not.

We are aiming to release the update to v3.x this week.

Best,
Ste

**Comment by Ste-RH** [comment] 2024-12-16 09:34
We have never seen this, or had it reported to us before.  Can you send a
screen shot of the message please?

Best,
Ste

**Comment by 1a1aca** [comment] 2024-12-16 09:57
It may be that some new phones are still using old hardware. For example, when I tested it with an OPPO phone, the problem I described occurred. I now know about the OES shader, but the crash problem still exists. For example, when I opened the 8K MKV format and WEBM format on the OPPO phone, the video would be inverted when opening the screen recording video. The current version.
![Screenshot_2024-12-16-17-51-10-09](https://github.com/user-attachments/assets/b7a52479-82d9-4079-ac07-6985d44778b5)
![Screenshot_2024-12-16-17-51-19-90](https://github.com/user-attachments/assets/ec7452e7-5c24-45ba-83eb-12502c209ea8)

**Comment by 1a1aca** [comment] 2024-12-16 09:59
It may be that some new phones are still using old hardware. For example, when I tested it with an OPPO phone, the problem I described occurred. I now know about the OES shader, but the crash problem still exists. For example, when I opened the 8K MKV format and WEBM format on the OPPO phone, the video would be inverted when opening the screen recording video. The current version.
![Screenshot_2024-12-16-17-51-10-09](https://github.com/user-attachments/assets/a4b76fa4-d1d6-4adf-9bb6-bb75b7e479fa)
![Screenshot_2024-12-16-17-51-19-90](https://github.com/user-attachments/assets/d6259832-f338-4691-968f-3ef5a60bba37)

**Comment by 1a1aca** [comment] 2024-12-16 10:00
> We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?

It may be that some new phones are still using old hardware. For example, when I tested it with an OPPO phone, the problem I described occurred. I now know about the OES shader, but the crash problem still exists. For example, when I opened the 8K MKV format and WEBM format on the OPPO phone, the video would be inverted when opening the screen recording video. The current version.
![Screenshot_2024-12-16-17-51-10-09](https://github.com/user-attachments/assets/8feb370b-29e5-411d-bece-3c22fcf5d230)
![Screenshot_2024-12-16-17-51-19-90](https://github.com/user-attachments/assets/e32ba8dd-3d34-413e-b8ed-d2ff3593921b)

**Comment by Ste-RH** [comment] 2024-12-16 10:06
8k is a lot for anything but the most modern hardware to play.  Are you sure these devices can actually play 8k?

What is the framerate, bitrate of these 8k videos?

**Comment by 1a1aca** [comment] 2024-12-16 10:09
> "The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low." We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?

So, I can only make these two modes switch automatically, but, how can I change the CurrentMediaPlayer when using the ApplyToMaterial component?
![2024-12-16 180415](https://github.com/user-attachments/assets/9fb8a25b-2047-4563-9fa0-67f67467e3e1)

**Comment by 1a1aca** [comment] 2024-12-16 10:09
> "The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low." We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?

So, I can only make these two modes switch automatically, but, how can I change the CurrentMediaPlayer when using the ApplyToMaterial component?
![2024-12-16 180415](https://github.com/user-attachments/assets/ff1e7846-c5d6-442c-85c9-d9813d8e1aae)

**Comment by Ste-RH** [comment] 2024-12-16 10:10
We are a bit lost now.  What is the actual problem here?  Because we thought we had solved the original issue (you can, before the next release, use OES...and we have fixed the issue in none OES mode for the next release).

If your problem is playing back a specific asset in OES mode, then please send along that video so we can take a look.

**Comment by Ste-RH** [comment] 2024-12-16 10:11
> > "The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low." We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?
> 
> So, I can only make these two modes switch automatically, but, how can I change the CurrentMediaPlayer when using the ApplyToMaterial component? ![2024-12-16 180415](https://private-user-images.githubusercontent.com/154946683/396051957-ff1e7846-c5d6-442c-85c9-d9813d8e1aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDQxMDMsIm5iZiI6MTczNDM0MzgwMywicGF0aCI6Ii8xNTQ5NDY2ODMvMzk2MDUxOTU3LWZmMWU3ODQ2LWM1ZDYtNDQyYy04NWM5LWQ5ODEzZDhlMWFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMDEwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODc0ODM4NGFhYmZmYmU0MTdmMGUxMzRlYzMyZWE1YzBkNWZiZTVhZGYwZGRlNDc4ZTJmN2VhYzBkMTJiODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BChoOuGZ9L7nAQnN4FnX-dzlWusrFzReR65SOGNvg4I)

Why just not use displayUGUI all the time?  What is the reason to switch to ApplyToMaterial?

**Comment by 1a1aca** [comment] 2024-12-16 10:21
I sent you two videos before, don't know how that feedback disappeared.
Old hardware phones cannot play 4K and above videos when using Exo Player mode, so the current version can only switch between two modes. I don't want to give up supporting old hardware phones.

**Comment by 1a1aca** [comment] 2024-12-16 10:22
> We are a bit lost now. What is the actual problem here? Because we thought we had solved the original issue (you can, before the next release, use OES...and we have fixed the issue in none OES mode for the next release).
> 
> If your problem is playing back a specific asset in OES mode, then please send along that video so we can take a look.

I sent you two videos before, don't know how that feedback disappeared.
Old hardware phones cannot play 4K and above videos when using Exo Player mode, so the current version can only switch between two modes. I don't want to give up supporting old hardware phones.

**Comment by 1a1aca** [comment] 2024-12-16 10:22
> > > "The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low." We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?
> > 
> > 
> > So, I can only make these two modes switch automatically, but, how can I change the CurrentMediaPlayer when using the ApplyToMaterial component? ![2024-12-16 180415](https://private-user-images.githubusercontent.com/154946683/396051957-ff1e7846-c5d6-442c-85c9-d9813d8e1aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDQxMDMsIm5iZiI6MTczNDM0MzgwMywicGF0aCI6Ii8xNTQ5NDY2ODMvMzk2MDUxOTU3LWZmMWU3ODQ2LWM1ZDYtNDQyYy04NWM5LWQ5ODEzZDhlMWFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMDEwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODc0ODM4NGFhYmZmYmU0MTdmMGUxMzRlYzMyZWE1YzBkNWZiZTVhZGYwZGRlNDc4ZTJmN2VhYzBkMTJiODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BChoOuGZ9L7nAQnN4FnX-dzlWusrFzReR65SOGNvg4I)
> 
> Why just not use displayUGUI all the time? What is the reason to switch to ApplyToMaterial?

For example, my custom 3D curved screen.

**Comment by 1a1aca** [comment] 2024-12-16 10:25
> > > "The reason why I can't use version 2.9.x is because it is incompatible with the Unity XR plug-in, and it prompts that the plug-in version is too low." We have never seen this, or had it reported to us before. Can you send a screen shot of the message please?
> > 
> > 
> > So, I can only make these two modes switch automatically, but, how can I change the CurrentMediaPlayer when using the ApplyToMaterial component? ![2024-12-16 180415](https://private-user-images.githubusercontent.com/154946683/396051957-ff1e7846-c5d6-442c-85c9-d9813d8e1aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDQxMDMsIm5iZiI6MTczNDM0MzgwMywicGF0aCI6Ii8xNTQ5NDY2ODMvMzk2MDUxOTU3LWZmMWU3ODQ2LWM1ZDYtNDQyYy04NWM5LWQ5ODEzZDhlMWFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMDEwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODc0ODM4NGFhYmZmYmU0MTdmMGUxMzRlYzMyZWE1YzBkNWZiZTVhZGYwZGRlNDc4ZTJmN2VhYzBkMTJiODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BChoOuGZ9L7nAQnN4FnX-dzlWusrFzReR65SOGNvg4I)
> 
> Why just not use displayUGUI all the time? What is the reason to switch to ApplyToMaterial?

And my custom VR spherical screen.

**Comment by Ste-RH** [comment] 2024-12-16 10:27
So you are not linked to the original team who reported this issue?  Because we saw no VR in the project we were sent.  It was a completely flat 2D project.

**Comment by 1a1aca** [comment] 2024-12-16 10:27
> 除了最现代的硬件之外，8K 对于任何东西来说都很多。您确定这些设备真的可以播放 8k 吗？
> 
> 这些 8k 视频的帧率、比特率是多少？



> 8k is a lot for anything but the most modern hardware to play. Are you sure these devices can actually play 8k?
> 
> What is the framerate, bitrate of these 8k videos?

Yes, I'm sure it can be played, and the 2.9.x version can also play it.

**Comment by Chris-RH** [comment] 2024-12-16 10:34
Hi @1a1aca,

Please can you open a new issue for this, as its not related to the original issue.

**Comment by Ste-RH** [comment] 2024-12-17 18:03
NOTE: Deleted a bunch of posts as they were not related to this issue.

**Closed** 2024-12-17 18:03 UTC
Labels: Android, Fixed, Version 3.x

**Comment by Chris-RH** [comment] 2024-12-20 11:18
AVPro Video version 3.2.0 has been released.  Please let us know if it has not fixed your issue.
