### ISSUE TITLE
SeekFast calls occasionally cause player to start seeking and never finish

### ISSUE THREAD

**Issue by robbbbbb** [RenderHeads/UnityPlugin-AVProVideo#1136] opened 2022-03-24 18:48 UTC
**Describe the issue**
We are trying to use SeekFast to skip a player in a Windows 10 (HoloLens) build to a given time in an m3u8 stream using the WinRT Video API. 

Much of the time this call to SeekFast will put the mediaPlayer in to IsSeeking() == true for an extremely long time. Sometimes this is 1-2 seconds, sometimes it can be 20-30 seconds, occasionally it just goes in to that state forever and never comes out again.

If we just load the video and call mediaPlayer.Play(), playback begins immediately and behaves fine 100% of the time.

- Is seeking with adaptive stream sources not supported/expected to be problematic in some way?
- Is there a more appropriate Seek method you suspect would work better with adaptive streams like the one linked below?
- Is there an appropriate way to _interrupt_ a Seek if we decide it's gone on too long?
- Should we be doing something else before SeekFast-ing? Like Pausing, or waiting for some event other than just 'ReadyToPlay'?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19f1
 - AVPro Video version: 2.4.1 core
 - Operating system version: HoloLens Win 10 (multiple versions, but exhibits on 20348.1440 and later)
 - Device model: HoloLens 2
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 25fps, avc1 over m3u8, file size...I guess irrelevant here, but this repros with both tiny 5 second clips and long 20 minute ones

**To Reproduce**
1. Open an m3u8 stream with the media player on UWP x64 on Win 10 using the WinRT Video API
2. Wait for the MediaPlayerEvent.EventType.ReadyToPlay event
3. Call mediaPlayer.Control.SeekFast(x) where 0 < x < duration

**Videos**
If applicable, add a copy of your video or the URL

Issue repros with this stream https://joinmediadev-euwe.streaming.media.azure.net/d902e6d0-9991-41f4-99ea-e0a75ad9cddc/6296c91f-0fdc-42c8-b7ee-458b4188.ism/manifest(format=m3u8-aapl)

**Comment by robbbbbb** [comment] 2022-03-24 18:50
Perhaps worth mentioning this is also reproducible in x64 Windows 10 native builds (also using the WinRT Video API), so it's not just UWP and not just HoloLens.

**Comment by robbbbbb** [comment] 2022-03-25 13:35
Slightly more info on this issue: I can repro a very long SeekFast with [this video](http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)) which you've provided as a suggested test stream here https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html

By watching the changing values of:
- IsSeeking()
- IsBuffering()
- GetBufferedTimes()

A couple of things seem to be the case:
- When SeekFast-ing, the media player will try to buffer in all segments for the target time + 3 seconds, perhaps this is dependent on the keyframes or the codec, but not in my experiments. Seems to just be one strategy.
- The _first_ time you call SeekFast() on an open video the seek completes very quickly (e.g. the next frame, or one after), although calling Play() at this point will still not actually begin playback until the appropriate segment has buffered (e.g. the above stream seems to have keyframes at 10s intervals, so if you SeekFast to '10' then the buffers fill relatively quickly, if you seek fast to 19.9 it takes much longer). Regardless, after SeekFast()ing, and then calling Play(), the return values of IsSeeking(), IsBuffering() and IsPlaying() are all false.
- If you immediately issue a _second_ call to SeekFast() to a different time, you get a slightly different result. This time the video player does much the same thing (buffers in the segments for the corresponding target time + 3s) but this time IsSeeking() is true, while IsBuffering() and IsPlaying() are still false. It also seems to take _significantly_ longer to complete this second SeekFast operation, regardless of whether the target time is early in a segment, or late.

I've also found that the problem is made significantly worse if _two_ media players are doing similar sequences of operations with two different streams in the app at the same time. 

Do you have advice as to whether multiple media players opening + buffering m3u8 streams concurrently is expected to work ok or should be discouraged (particularly on mobile platforms)?

**Comment by robbbbbb** [comment] 2022-03-31 15:17
@MorrisRH any feedback on this would be appreciated. I can provide a repro project if helpful.

**Comment by Chris-RH** [comment] 2022-04-12 10:51
Hi, as mentioned in the email, we are looking into this. Its possibly not related to our code, but we might be able to find a work around.  Thank you for your patience.

**Comment by robbbbbb** [comment] 2022-04-14 16:03
Another quick update on this, in case it's useful: I'm experimenting switching us over from the WinRT video API to the Media Foundation one (mainly because we see occasional **massive** stalls when calling OpenMedia() with WinRT both on Windows x64 and on UWP, but not with Media Foundation). I can report that exactly the same behaviour with a perfectly reasonble SeekFast() call shortly after the video succesfully opens consistently leads to a hugely long period of the video going in to IsSeeking state, which can last 5-10 seconds. 

So: WinRT api and Media Foundation api both seem to behave pretty much the same for multiple different video streams. I feel like this perhaps makes it more likely that the issue is somewhere inside AVPro Video itself, and not in the Windows SDKs (unless those two SDKs share some common bit of network buffering code or something).

**Comment by Chris-RH** [comment] 2022-04-14 17:38
Thank you, that will be very useful in helping us to pinpoint the problem.

**Comment by AndrewRH** [comment] 2022-04-19 16:41
Hi, 
I've been trying to reproduce this issue bug so far I've been unsucessful.

Here is the script I'm using:
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RenderHeads.Media.AVProVideo;

public class TestSeekingFast : MonoBehaviour 
{
	private MediaPlayer _mp;
	
	void Start () 
	{
		_mp = GetComponent<MediaPlayer>();
		_mp.Events.AddListener(HandleEvent);
	}

	void HandleEvent(MediaPlayer mp, MediaPlayerEvent.EventType eventType, ErrorCode code)
	{
		Debug.Log(eventType.ToString());
		if (eventType == MediaPlayerEvent.EventType.ReadyToPlay)
		{
			RandomSeek();
		}
	}

	void RandomSeek()
	{
		double time = (double)UnityEngine.Random.Range(0.0f, (float)_mp.Info.GetDuration());
		_mp.Control.SeekFast(time);
		_mp.Play();
	}
	
	// Update is called once per frame
	void Update () {
		if (Input.anyKeyDown)
		{
			RandomSeek();
		}
	}
}
`

The first seek happens automatically, and then the second seek happens when I press a key.  I don't get any long buffering.  Perhaps you could show me the code you're using?

Thanks,

**Comment by Chris-RH** [comment] 2022-05-05 14:15
Hi @robbbbbb,
If you are still having a problem with this, would you be able to show us what code you are using please?

**Comment by Chris-RH** [comment] 2022-05-19 08:29
I'm closing this due to no further response from OP and we could not replicate the problem.  If this is still a problem, please reopen.

**Closed by Chris-RH** 2022-05-19 08:29 UTC
Labels: Windows, Triage
