### ISSUE TITLE
Add FishEye Layout Mapping Support

### ISSUE THREAD

**Issue by busyxiang** [RenderHeads/UnityPlugin-AVProVideo#83] opened 2019-06-15 16:11 UTC
I am developing an application for Oculus GO and using 360Sphere to play my videos. But, I noticed that the current plugin does not support **FishEye** format and my videos require **FishEye** format. So I would like to have **FishEye** format to be considered as one of the new features since not all 360/180 videos are EquiRectangular format. And at the same time, when using **FishEye** format the user should also be able to **control** the **angle** ( or dome angle, not sure what is the actual naming for it ) to control the amount of angle to display the video.

**Comment by Applet-LLC** [comment] 2019-06-16 02:33
I'm developing and I'm not perfect yet, but there is a code for Shader that works once.
https://appletllc.wordpress.com/2019/06/04/fisheye180-side-by-side%E5%AF%BE%E5%BF%9C/

**Comment by busyxiang** [comment] 2019-06-16 07:21
@Applet-LLC Awesome and thank you for sharing your shader! I would also like to know is it possible to control the angle of the FishEye format instead of a fixed 180 degree.

**Comment by Applet-LLC** [comment] 2019-06-16 09:14
@busyxiang Thank you for your comment. As for the angle, it is unclear whether the intended original is the same, but the variable Fov (0 to 360) is currently set to 180 by default, but changing this corresponds to different angles.  As we did not encounter content other than 180 degrees, we could not confirm whether it was correct. Then there are limitations as it is not perfect. It does not correspond to HIGH_QUALITY and scaleOffset. Also, the format is only Side by Side, not Top and Bottom.

**Comment by parmaia** [comment] 2019-11-28 09:37
I also want to support this enhancement, because we stream live 180 videos, both stereoscopic and monoscopic, and we are lacking a robust solution to that.

**Comment by AndrewRH** [comment] 2020-11-13 02:05
@Applet-LLC yes thanks again, we're still considering how to add this to the next version as a new feature.

**Comment by Applet-LLC** [comment] 2021-08-17 09:53
I tried to make it compatible with HIGH_QUALITY. 
However, since the correspondence of Angle: FOV was skipped, the operation is unconfirmed except for VR180.
https://appletllc.wordpress.com/2021/08/17/fisheye180-shader-high_quality%e5%af%be%e5%bf%9c/

**Comment by Applet-LLC** [comment] 2021-08-24 16:51
PS. My trial FishEye180 Shader files for AVProVideo 2.1.8, Interfaces.cs, VideoRender.cs.
https://appletllc.com/files/Shader.zip

**Comment by AndrewRH** [comment] 2021-12-08 16:12
[Shader.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7677368/Shader.zip)

Here is a copy of the above archive.

I'm closing this issue now as we don't intend to embed this feature and @Applet-LLC  has kindly shared their implementation

**Closed by AndrewRH** 2021-12-08 16:12 UTC
Labels: enhancement 🚀

**Comment by gekkehenkie11** [comment] 2025-12-18 17:36
There's still no official fisheye support? I tried the above shader but couldnt get it running in 'high quality' mode... In the normal quality mode things looked a bit off ...

**Comment by gekkehenkie11** [comment] 2025-12-18 18:08
Too bad, been working on the trial version but without fisheye support I won't be buying.

**Comment by gekkehenkie11** [comment] 2025-12-18 20:40
@Applet-LLC The zip file version doesnt work correctly with highquality indeed. On your website there's an updated version but it calls 'GetStereoScaleOffset2' but I dont see the implementation?

**Comment by gekkehenkie11** [comment] 2025-12-18 22:09
Ok managed to fix it up. The missing function is quite obvious, it's just a modified verison of the original to fix the stereo mode. Big props to @Applet-LLC.  Also the FoV rendering works fine btw
