### ISSUE TITLE
RE: !!Camera GUID

### ISSUE THREAD

**Issue by lookreelDev** [RenderHeads/UnityPlugin-AVProVideo#1093] opened 2022-02-08 05:33 UTC
Hi guys,

This is not an error but a feature, and I am in dire straits for I have a very heavy deadline coming up.

So far your product has been absolutely very strong in it's capabilities for what we needed it for.

We are creating a Unity application that requires camera and sensor readings. And we have achieved that already with using only 1 camera(it's great)

How to explain this?

We have a client that is requesting 4 camera systems with pressure sensor readings.

I do know we can run multiple cameras and they run well. However I am trying to marry the cam device with the sensor device utilising the same hub.

So I found that I can use the GUID of the device, which I can log or register as a file json and connect that with the ID of the Sensor(port)

However I have noticed that the GUID does't stick to a device camera. When I change it to another camera to see if I can get a different GUID, it assigns the previous GUID to the current camera I changed to.

The only way I can get a different GUID is when I have multiple cameras, but at that moment I don't know which GUID is assigned to any of the different cameras. Which makes it hard to check it against the log.

The issue would be that the sensor that works with the camera plugged into a hub could be any camera assigned with the sensor reader. Thus would give us wrong results as recording.

I hope I have explained this well. It has been an absolute pain. The unfortunate part is our deadline for our client's needs for an important job.

What can I do?
Where can I find in your API something that can give me a more fixed serial that is specific to the camera and it doesn't change permanently?
Please Help!!

Unity version: 2020.3.26f1
AVPro Video version (2.9.1 (Current) Purchased):
Operating system version: Windows
Device model: 4k Camera
Video specs (resolution, frame-rate, codec, file size):
To Reproduce

1.Plug in current camera Check GUID
2.Unplug current Camera
3.Plug in new camera Check GUID
4.Will assign the same GUID on second camera from first
5.Unless you have two cameras plugged in. Then will assign separate
6.GUID changes on different cameras. Nothing fixed

**Comment by kahnivore** [comment] 2022-02-09 11:45
Closing this as it is a duplicate of previous issue.

**Closed by kahnivore** 2022-02-09 11:45 UTC
