### ISSUE TITLE
Not able to play encrypted HLS video in Android

### ISSUE THREAD

**Issue by DeepKrr** [RenderHeads/UnityPlugin-AVProVideo#1510] opened 2023-04-11 06:42 UTC
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I am using AvPro-Ultra Edition (purchased) version.
We have to use this to play HLS videos on Window, Android & IOS.
Its working working fine for windows platform but in Android its not working properly.
I am using the exoplayer and the steps suggested on this link: [https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html#hls-aes-128-encrypted-playback.](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html#hls-aes-128-encrypted-playback)
Getting the error--> Error loading failed, codec not supported...
I am testing on mobile device: OPPO Reno8 5G.

NOTE: we have not to keep the encrypted key in parallel of videos/segments

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.24
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra Edition - Version 2.7.3
 - Operating system version: Android
 - Device model: Oppo Reno8 5G
 - Video specs (resolution, frame-rate, codec, file size): 
resolution - 360p
frame rate - 30fps
codec - avc1.64001f,mp4a.40.2
file size - 1-2 mb per TS segment

**To Reproduce**
1. Kept segmented videos on local server and keeping encrypted key inside the code base.
2. used Exoplayer and passed the encrypted key
3. Video not played and get codec error.

**Logs**
If applicable, add error logs to help explain your problem.
[AvProVideo Error]: Loading failed. File not found, codec not supported and video not played.
[AVProVideo] Error: #347 

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com
![Screenshot_PlayerError](https://user-images.githubusercontent.com/40888438/231077397-2f157f85-8bdd-4a64-8f21-c168eca9bb73.jpg)

**Comment by Chris-RH** [comment] 2023-04-11 13:11
I believe Android does not support overrideDecryptionKey.

Have you also made sure to double check that the device can play the video unencrypted, so that you know that isn't the issue?

**Comment by DeepKrr** [comment] 2023-04-12 11:17
Yes, I have checked able to play the unencrypted video.

**Comment by DeepKrr** [comment] 2023-04-13 05:24
We have tried using keyServerToken  also, but didn't work. Please suggest, is there anything else we can try;
Or give some code snippet that we can try to play encrypted video, it will be helpful.

_MediaPlayer.PlatformOptionsAndroid.keyAuth.keyServerToken = "my key";

One more thing, in documentation there is not anywhere described that its not supported in android.

**Comment by Chris-RH** [comment] 2023-04-13 08:27
Did you try entering it in using the mediaplayer component?

**Comment by DeepKrr** [comment] 2023-04-13 10:49
Yes, we tried with mediaplayer component.
In editor mode if we try with component it picks Windows as platform and not works. 
While, if we use key override (overrideDecryptionKey) it works in editor mode as well as for windows platform but not for Android.

**Comment by Chris-RH** [comment] 2023-04-13 13:14
OK, what do you get in the logcat when you try to play the file?

**Comment by DeepKrr** [comment] 2023-04-14 07:52
Hi, I have already attached the screenshot.
Sharing the logcat also..
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11230304/log.txt)

**Comment by Chris-RH** [comment] 2023-04-14 08:50
I noticed that the URL in the log was HTTP.  Could you try an HTTPS url instead?

**Comment by DeepKrr** [comment] 2023-04-14 11:25
ok, i will try and update here

**Comment by DeepKrr** [comment] 2023-04-14 11:35
Hi, i tried with https also but no success.
Attached the logcat also for your reference.
[com.DefaultCompany.AV_Pro_Player-logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11232301/com.DefaultCompany.AV_Pro_Player-logcat.txt)

**Comment by Chris-RH** [comment] 2023-04-14 12:48
Out of interest, is the URL or videos related to Youtube in any way?

**Comment by Chris-RH** [comment] 2023-04-14 14:19
Are you able to provide URL and token? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by DeepKrr** [comment] 2023-04-15 08:08
Hi, we are not using any youtube url.

I am redefining my problem statement,
I have to play the HLS videos using overrideDecryptionKey
Its working working fine for windows platform but in Android its not working.

So, my concern is that; if overrideDecryptionKey method is provided for window to play the HLS videos then why not for android.
Is there some code, i can go through to play the videos in android.

Also, in future is there any plan to release patch with the solution for android.

**Comment by DeepKrr** [comment] 2023-04-20 05:36
Hi, please tell is there any plan in future to release update/patch with the solution for android or give some solution.

If not, refund some of the amount ($200) as its not working for android platform.
And its not mentioned in your documentation, that it will not work for android.

**Comment by DeepKrr** [comment] 2023-04-24 12:32
ok, Please suggest some timeline by when I will get the information.
As, I have some project deliveries which are pending because of this.

Also, let me know regarding some discount/refund policy, if no solution provided.

**Comment by Chris-RH** [comment] 2023-04-26 10:49
Hi, 
The dev team is overseas on a build at the moment.  The team will be back middle of next week.
Decryption using an auth token should work though, its strange that its not working for you.
Are you able to send URL/token for us to investigate with?  unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2023-04-28 11:00
Can you try this stream please:
https://amssamples.streaming.mediaservices.windows.net/830584f8-f0c8-4e41-968b-6538b9380aa5/TearsOfSteelTeaser.ism/manifest(format=m3u8-aapl)

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5ZGRhMGJjYy01NmZiLTQxNDMtOWQzMi0zYWI5Y2M2ZWE4MGIiLCJpc3MiOiJodHRwOi8vdGVzdGFjcy5jb20vIiwiYXVkIjoidXJuOnRlc3QiLCJleHAiOjE3MTA4MDczODl9.lJXm5hmkp5ArRIAHqVJGefW2bcTzd91iZphoKDwa6w8

**Comment by DeepKrr** [comment] 2023-05-01 04:50
Hi Chris, we will try the stream and update.

Regarding URL/token, I will share the data.. But one thing here, we have to use overrideDecryptionKey method to play HLS videos.

**Comment by DeepKrr** [comment] 2023-05-10 06:55
Hi Chris,
Any update?

**Comment by DeepKrr** [comment] 2023-05-17 06:16
Hi Chris,
Any success/update, have your team tried with sample videos zip shared?
If not, suggest what is next step.

**Comment by Chris-RH** [comment] 2023-05-17 09:02
Nothing at the moment.  Did you manage to get the AES encryption working on android without overrideDecryptionKey?

**Comment by DeepKrr** [comment] 2023-06-07 04:29
Hi, our requirement is to play the video using overrideDecryptionKey.
I have already mentioned above many times.
So, please look into this direction and update when it will be fixed.

I have already shared the attachment above, please try with that file and key.

**Comment by DeepKrr** [comment] 2023-06-07 09:07
Hi Chris, if your dev team is not looking into this direction ..
We want some percentage of amount to be be refunded.

**Comment by Chris-RH** [comment] 2023-06-07 10:09
Hi @DeepKrr,
It is being looked into :)

**Comment by DeepKrr** [comment] 2023-06-07 10:57
ok, but it has been so long.. Can you give some timeline or estimation by when it will be resolved.

**Comment by Ste-RH** [comment] 2023-06-07 11:52
@DeepKrr We have a fix for this now that will go into the next build.  If you require a fix sooner than this then there are two options:

1) The issue is linked to using TS segments.  If you change your videos to use fragmented MP4 then you will not see the problem

2) Email over your Unity PDF invoice and we will issue a new set of plugin files for Android for you.  You will need to update to AVPro Video 2.8.0 before you can use the Android plugin files we provide.

Do let us know how you would like to proceed.

**Comment by DeepKrr** [comment] 2023-06-08 04:36
@Ste-RH Hi,
We would like to go with the second option i.e. to update to AVPro Video 2.8.0 and use a new set of plugin files for Android.

But, before that would like to know that using these plugins files will I be able to to play the video using overrideDecryptionKey.

**Comment by Ste-RH** [comment] 2023-06-08 10:30
As per above, we believe we have fixed the issue on Android.  I would recommend setting up a test project with 2.8.0 with the updated plugin file(s).  Email us at unitysupport@renderheads.com and I will get it over to you asap

**Comment by DeepKrr** [comment] 2023-06-09 04:37
Hi @Ste-RH,
I have sent the mail yesterday. Please provide the updated plugin file(s).

**Comment by DeepKrr** [comment] 2023-06-09 07:11
@Ste-RH By when, plugin files will be shared.
Please update, its urgent.

**Comment by DeepKrr** [comment] 2023-06-09 10:40
Hi, any update..

**Comment by Chris-RH** [comment] 2023-06-09 11:11
Hi @DeepKrr, 

The file has been sent to your email :)

**Comment by DeepKrr** [comment] 2023-06-09 11:56
@Chris-RH 
File well received, thanks..

**Comment by Chris-RH** [comment] 2023-06-30 12:45
The latest version has been released.  Please let us know if your issue has not been fixed.

**Closed** 2023-07-05 08:41 UTC
Labels: Android, Fixed
