### ISSUE TITLE
No video on iPhone 11 pro max

### ISSUE THREAD

**Issue by shiryshev** [RenderHeads/UnityPlugin-AVProVideo#1273] opened 2022-08-29 07:38 UTC
**Describe the issue**
User of our app report problem with player on iPhone 11 pro max device:
— hear sound, no video (only black or white screen) 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.4 Ultra
 - Operating system version: iOS 15.6.1
 - Device model: iPhone 11 Pro Max
 - Video specs (resolution, [frame-rate,] codec, file size): 1920х1080, 25 fps, h.264, 

**To Reproduce**
1. Download https://apps.apple.com/ru/app/id1592290296 
2. Skip paywall, go to home screen
3. Play any free video

**Logs**
No logs

**Screenshots**
![11pro-15 6 1-Paul-novideo](https://user-images.githubusercontent.com/726717/187148880-7fdea001-f599-429d-b533-5ae63f2779ea.jpg)

**Videos**

https://user-images.githubusercontent.com/726717/187148663-396b8712-7145-4c76-897b-7271dc4389e9.mov

Attached

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment] 2022-08-30 09:48
Hi @shiryshev,
Have you tried a new project with just our demo media player?
Have you tried it on other devices?
Do you have any error logs? 
We need to know if the following events are working: ReadyToPlay, MetaDataReady, FirstFrameReady

**Comment by shiryshev** [comment] 2022-08-30 10:33
Have you tried a new project with just our demo media player?
No. It is 2.5.4 Ultra

Have you tried it on other devices?
Yes, iphone 6,7,8,10,11,13,se, ipad 4 gen - no problem

Do you have any error logs?
No. This is user's device

We need to know if the following events are working: ReadyToPlay, MetaDataReady, FirstFrameReady
They are working

**Comment by Chris-RH** [comment] 2022-08-30 12:07
Ah, so you don't have access to the device?

Can they test it with an apk just playing our demo media player? 
https://www.renderheads.com/content/docs/AVProVideo/articles/usage-demos.html

**Comment by MorrisRH** [comment] 2022-08-31 09:36
Hey @shiryshev, a few more questions:
1. Are the movies HLS or mp4?
2. Would it be possible to get a link to one of the videos so we can test playback here? (you can send it to unitysupport@renderheads.com with 'GitHub Issue #1273' as the subject if you want to keep it private).
3. What are the settings on the media player component?

**Comment by shiryshev** [comment] 2022-08-31 10:15
Hi!

> Can they test it with an apk just playing our demo media player?

Nope. This is iPhone :)

> 1. Are the movies HLS or mp4?

mp4

> 2\. Would it be possible to get a link to one of the videos so we can test playback here? (you can send it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) with 'GitHub Issue [No video on iPhone 11 pro max #1273](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1273)' as the subject if you want to keep it private).

Ok

> 3\. What are the settings on the media player component?

See attach
![2022-08-31 13 12 03](https://user-images.githubusercontent.com/726717/187655844-6e17fa6e-3df3-4716-9487-6634b6500c42.jpg)
![2022-08-31 13 12 13](https://user-images.githubusercontent.com/726717/187655859-ff889fbb-3a3f-4e34-a069-f66a219d5dd3.jpg)
![2022-08-31 13 12 44](https://user-images.githubusercontent.com/726717/187655863-147d8bc0-4073-4705-8296-2dde886c07b7.jpg)
![2022-08-31 13 13 15](https://user-images.githubusercontent.com/726717/187655865-9a5d10cb-5f69-46dc-966c-9110bb9433e4.jpg)

Thanks!

**Comment by MorrisRH** [comment] 2022-08-31 13:35
Thanks for sending on the video, everything looks fine there. Unfortunately I cannot reproduce this. I am wondering if it's the same issue as #1266.

**Comment by shiryshev** [comment] 2022-08-31 14:22
You test on an iPhone 11 pro max and everything is ok?

**Comment by MorrisRH** [comment] 2022-08-31 14:42
I don't have access to an iPhone 11 Pro Max, I have checked on an iPhone 13 Pro, iPhone X and an iPad Pro (10.5"). I've never had an issue specific to a model of iPhone before though so I'm unconvinced that it is specific to an iPhone 11 Pro Max.

It will be worth asking your user if they've been using AirPlay before using your app just to rule that out as a possible cause of the issue.

**Comment by shiryshev** [comment] 2022-08-31 15:49
We tested on all these devices, but we can't find an iphone 11 pro max
(only 11) to reproduce the issue.
And our user tested on the wife's  iphone 13 pro — everything works.

I try to ask about AirPlay. What kind of problem may be with it?

**Comment by MorrisRH** [comment] 2022-09-01 08:52
If AirPlay has been enabled in another app (Apple's TV app for example) then when a video is played in your app it will automatically be cast to the TV. When this happens no video is rendered inside the app so you see a blank image where the video would be which matches what you are describing.
We've made this behaviour opt-in in AVPro Video so it shouldn't happen by default, but if "Enable External Playback" is checked in the media player properties then it will happen.

**Comment by MorrisRH** [comment] 2022-09-05 06:53
Closing as duplicate of #1266

**Closed by MorrisRH** 2022-09-05 06:53 UTC
Labels: iOS, need more info 🤷, Could not reproduce 🤷
