### ISSUE TITLE
getting crash in IOS 10.3.3

### ISSUE THREAD

**Issue by jesspanda** [RenderHeads/UnityPlugin-AVProVideo#371] opened 2020-05-28 06:51 UTC
**Describe the bug**
Crash in IOS 10.3.3

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.12f1
 - AVPro Video version: 1.11.1
 - Operating system version: IOS 10.3.3
 - Device model: IPAD4  MD513CH/A
 - Video specs (resolution, frame-rate, codec, file size): 

**Logs**
If applicable, add error logs to help explain your problem.
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/48973744/83108599-9f198100-a0f2-11ea-9b6d-6ee63c4fa590.png">

**Comment by MorrisRH** [comment] 2020-05-28 09:16
I've been able to reproduce this. It's due to using multithreaded rendering with the opengles renderer. I recommend you disable multithreaded rendering for now whilst we look for a solution.

**Comment by jesspanda** [comment] 2020-05-28 09:34
Ok, thanks a lot

On May 28, 2020, at 5:16 PM, Morris Butler <notifications@github.com<mailto:notifications@github.com>> wrote:



I've been able to reproduce this. It's due to using multithreaded rendering with the opengles renderer. I recommend you disable multithreaded rendering for now whilst we look for a solution.

**Comment by MorrisRH** [comment] 2020-05-28 16:14
This issue should be fixed in the next release.

**Comment by AndrewRH** [comment] 2020-05-29 13:04
Hi @jesspanda 

The new version is out (1.11.2), could you confirm whether that solves your issue?

Thanks,

**Comment by jesspanda** [comment] 2020-06-01 03:38
hi  @Andrew

    This issue has been solved in version(1.11.2). Thank you for your support.

Thanks,

On May 29, 2020, at 9:04 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @jesspanda<https://github.com/jesspanda>

The new version is out (1.11.2), could you confirm whether that solves your issue?

Thanks,

**Comment by jesspanda** [comment] 2020-06-01 03:41
hi  @AndrewRH 

    This issue has been solved in version(1.11.2). Thank you for your support.

Thanks,

**Closed** 2020-06-01 06:01 UTC
Labels: Bug, Fixed, iOS
