### ISSUE TITLE
Trying to control media player from code

### ISSUE THREAD

**Issue by nirniron** [RenderHeads/UnityPlugin-AVProVideo#803] opened 2021-05-26 14:23 UTC
hello
I'm trying to perform 2 actions on media player via code but cannot find how.
I'm useing AVPro 1.11.7 (Latest AVP1)

1. I'm using the function MediaPlayer.OpenVideoFromFile(relativeTo, url, false); but I cannot find the option to AutoOpen but not Autoplay. I'm instantiating a MediaPlayer and I want to define it by code as OpenVideoFromFile only have a variable for AutoOpen.

2. I want to subscribe to a MediaPlayer event via code. for instance "On Buffering Complete"

**Comment by kahnivore** [comment] 2021-05-26 14:56
HI 

1. To set the AutoOpen flag you could use:

`mediaPlayer.m_AutoOpen = true;`

2. You could do something like this:

//Add the event listener (can also do this via the editor GUI)
MediaPlayer mediaPlayer;
mediaPlayer.Events.AddListener(OnVideoEvent);

//Callback funtion to handle events
private void OnVideoEvent(MediaPlayer mediaPlayer, MediaPlayerEvent.EventType et, ErrorCode errorCode)
{
	switch (et)
	{
		case MediaPlayerEvent.EventType.FinishedBuffering:
			//Do Something
			break;
	}
           
        Debug.Log("Event: " + et.ToString());
}

**Comment by kahnivore** [comment] 2021-06-01 12:14
Hey @nirniron, does this answer your question?

**Comment by nirniron** [comment] 2021-06-01 13:09
> Hey @nirniron, does this answer your question?

yes, thank you
1 last thing I was encountered in the meanwhile is:
How can I enable/disable platform Specific, assign it to WebGL and change the external library via code? is it possible?

I want to create a handler that can receive multiple types of paths and will then configure the appropriate player according to the suffix.

**Comment by kahnivore** [comment] 2021-06-02 15:43
Not sure what you mean by enable/disable platform specific? You need to target a specific platform per build.

**Comment by nirniron** [comment] 2021-06-06 11:15
hi
waht I mean is:
if I want to enable/disable the use of hls library in webGL platform
specific, but I want to change the setting via code (so I can create a
manager/handler that defines the settings according to the format I want to
use automatically) how can I do that?

**Comment by nirniron** [comment] 2021-06-06 11:16
Also, kay.

1. thank you for all your assistance so far

2. I've noticed here
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/35
that there may be an option to control the default streaming quality via
AVPro2. has it already been implemented?

**Comment by kahnivore** [comment] 2021-06-09 15:51
To set the webGL library via code you could use, for example: 

mediaPlayer.PlatformOptionsWebGL.externalLibrary = WebGL.ExternalLibrary.HlsJs;

Re the default streaming quality - there are various options for each platform. But an example of this is:

mediaPlayer.PlatformOptionsAndroid.startWithHighestBitrate = true; 

Or: 

public Resolution preferredMaximumResolution = Resolution.NoPreference;
#if UNITY_2017_2_OR_NEWER
            public Vector2Int customPreferredMaximumResolution = Vector2Int.zero;
#endif
            public float preferredPeakBitRate = 0.0f;
            public BitRateUnits preferredPeakBitRateUnits = BitRateUnits.Kbps;

Does this help?

**Comment by nirniron** [comment] 2021-06-10 13:40
Yes, it does.
where can I find the documentation for this?
so I can for example switch platforms and know which functions are only
platform specific?

for instance

mediaPlayer.PlatformOptionsAndroid.startWithHighestBitrate = true;
is great, to mimic it to webgl do i only need to do

mediaPlayer. PlatformOptionsWebGL  .startWithHighestBitrate = true; ?

**Comment by nirniron** [comment] 2021-06-10 13:43
also
if i set

mediaPlayer.PlatformOptionsWebGL.externalLibrary =
WebGL.ExternalLibrary.HlsJs;
 and the hls setting are included in the index.html and template folder,
can i still play with no issues any mp4 or similar? or did i just force
avpro to use the lib and the setting hls must be disabled in order to play
mp4?

**Comment by AndrewRH** [comment] 2021-06-11 04:05
there is no option in WebGL to start with the highest bitrate.   You would need to modify the jslib file to add that option to hls.js

See here:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl

            var config = {
                lowLatencyMode: true,
            };
            hls = new Hls(config);

See the HLS.JS options here:
https://github.com/video-dev/hls.js/blob/master/docs/API.md


If you are loading MP4 files, then you would need to set the ExternalLibrary to None

**Comment by nirniron** [comment] 2021-06-13 08:40
Thanks, I'll check it out.

that was my question sir :)
"If you are loading MP4 files, then you would need to set the
ExternalLibrary to None"
Do I HAVE TO? is it possible to play the mp4 if the external lib is not
none? I'm checking with you to verify the steps I need to take.

**Comment by kahnivore** [comment] 2021-06-30 12:58
Hi @nirniron 

Yes, you do have to set the external library to 'none' in order to play an MP4 file. In AVPro Video 1.x the only way to do this is to create a separate media player - as the external library gets set when the media player is created and cannot be changed. In 2.x we have added code for this to be possible to be changed via code.

**Comment by nirniron** [comment] 2021-07-04 16:19
Hi Kay
how are you

I've checked the format supporting of AVPro, but since you aren't
officially supporting webGL I'm not 100% sure which of the formats are
expected to be supported.
will MKV, MOV, AVI and WEBM play without any need for external lib?

MP4 ✓ ✓ ✓ ✓
MOV ✓ . ✓ ✓
MKV ✓ 1
<https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html#f1>
✓ . .
WebM ✓ 2
<https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html#f2>
✓ . .
AVI ✓ . . .
MP3 ✓ ✓ ✓ ✓
AAC ✓ ✓ ✓ ✓
WAV ✓ . . .
CAF

**Comment by AndrewRH** [comment] 2021-07-05 15:17
Support for media depends on the browser - you should check the browser docs:

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

I haven't checked on each browser, but I would guess that .webm would play in most, but the others (avi/mov/mkv) will not..

**Comment by AndrewRH** [comment] 2021-07-05 15:18
I'm closing this thread because the issue is no longer related to the topic.  Please open a new issue if you have any more questions or problems.

Thanks,

**Closed by AndrewRH** 2021-07-05 15:18 UTC
Labels: Version 1.x, WebGL, question
