### ISSUE TITLE
Video Playback Issues in AVPro 2.9.3 on Android Devices (Resolved in v3)

### ISSUE THREAD

**Issue by AmalBabuM** [RenderHeads/UnityPlugin-AVProVideo#2005] opened 2024-09-17 05:43 UTC
**Describe the issue**
We’ve been experiencing issues with the current version (Core Edition 2.9.3), including black screens, crashes, and audio playing without video in some of the devices.
To confirm that these were AVPro-related, we tested the latest trial version of AV Pro (v3 - Core Edition), and found that the issues were resolved in their recent updates

**Your Setup (please complete the following information):**
 - Unity version: 2023.2.3 f1
 - AVPro Video version (AVPro Video - Core Edition 2.9.3): 
 - Operating system version: Android
 - Device model: Samsung S21 FE
 - Video specs (4k, 25fps, H24, 100 MB):

**Comment by Chris-RH** [comment] 2024-09-17 09:18
Hi Amal, 

As per our email conversation, AVPro Video version 2 was depreciated 6 months ago and can no longer receive any updates.  There were no mentions of your issues prior to depreciation.  As you have seen, the issue appears to be resolved in the current version of AVPro Video version 3.0.11.  There is a [discounted upgrade path](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#upgrade-pricing) between AVPro Video version 2 and AVPro Video version 3.  We do clearly state in our documentation that [each major version lasts at least 2 years](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#future-updates).

Kind regards, 
Chris

**Comment by Ste-RH** [comment] 2024-09-17 11:04
Closing due to being a duplicate of support email #b7io88nhab

Please stick to one method of contacting support unless we ask you to do otherwise.

**Closed by Ste-RH** 2024-09-17 11:04 UTC
Labels: question, Version 2.x
