### ISSUE TITLE
Failed to create texture because of invalid parameters

### ISSUE THREAD

**Issue by 1987skywalker** [RenderHeads/UnityPlugin-AVProVideo#295] opened 2020-03-19 10:47 UTC
**Describe the bug**
I have a old game on appstore and want to play a video when the app starts.  I add FullscreenVideo.prefab to the scene and set source path. It's OK in editor and android. But it can not play on ios. The log is below. Why call RenderHeads.Media.AVProVideo.Demos.SampleApp_Multiple while there is only DisplayIMGUI component? Help me,please!

**Your Setup (please complete the following information):**
 - Unity version: 4.7.2f1
 - AVPro Video version: 1.10.1
 - Operating system version: iOS 11.2.6
 - Device model: iPhone6 Plus
 - Video specs (resolution, frame-rate, codec, file size): 1280*720,30fps,H264,10.6M

**To Reproduce**
1. Add FullscreenVideo.prefab to the scene and set source path
2. export to xcode project
3. run

**Logs**
Initialising for graphics device type Metal
2020-03-19 18:06:19.367209+0800 dungeonstriker[4395:2123706] [Common]
_BSMachError: port a90b; (os/kern) invalid capability (0x14) "Unable to insert
COPY_SEND"
2020-03-19 18:06:19.371259+0800 dungeonstriker[4395:2123706] [Common]
_BSMachError: port a90b; (os/kern) invalid capability (0x14) "Unable to insert
COPY_SEND"
-> applicationDidBecomeActive()
OnApplicaitionPause false
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
sdGlobalDatabase:OnApplicationPause(Boolean)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-
il2cppGenerated/UnityEngineDebug.cpp Line: 56)
PauseFalse
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
CheckLagObj:OnApplicationPause(Boolean)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-
il2cppGenerated/UnityEngineDebug.cpp Line: 56)
TextureFormat is invalid!
UnityEngine.Texture2D:Internal_Create(Texture2D, Int32, Int32, TextureFormat,
Boolean, Boolean, IntPtr)
UnityEngine.Texture2D:.ctor(Int32, Int32, TextureFormat, Boolean, Boolean,
IntPtr)
UnityEngine.Texture2D:CreateExternalTexture(Int32, Int32, TextureFormat,
Boolean, Boolean, IntPtr)
RenderHeads.Media.AVProVideo.OSXMediaPlayer:UpdateTextures()
RenderHeads.Media.AVProVideo.OSXMediaPlayer:Update()
RenderHeads.Media.AVProVideo.Demos.SampleApp_Multiple:Update()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
[ line 467]
(Filename: Line: 467)
UnityException: Failed to create texture because of invalid parameters.
at UnityEngine.Texture2D.Internal_Create (UnityEngine.Texture2D mono,
Int32 width, Int32 height, TextureFormat format, Boolean mipmap, Boolean
linear, IntPtr nativeTex) [0x00000] in <filename unknown>:0
at UnityEngine.Texture2D..ctor (Int32 width, Int32 height, TextureFormat
format, Boolean mipmap, Boolean linear, IntPtr nativeTex) [0x00000] in
<filename unknown>:0
at UnityEngine.Texture2D.CreateExternalTexture (Int32 width, Int32 height,
TextureFormat format, Boolean mipmap, Boolean linear, IntPtr nativeTex)
[0x00000] in <filename unknown>:0
at RenderHeads.Media.AVProVideo.OSXMediaPlayer.UpdateTextures ()
[0x00000] in <filename unknown>:0
at RenderHeads.Media.AVProVideo.OSXMediaPlayer.Update () [0x00000] in
<filename unknown>:0
at RenderHeads.Media.AVProVideo.Demos.SampleApp_Multiple.Update ()
[0x00000] in <filename unknown>:0
at RenderHeads.Media.AVProVideo.MediaPlayer.Update () [0x00000] in
<filename unknown>:0
at System.Linq.SortContext`1[TElement].Compare (Int32 first_index, Int32
second_index) [0x00000] in <filename unknown>:0
at System.Linq.SortContext`1[TElement].Compare (Int32 first_index, Int32
second_index) [0x00000] in <filename unknown>:0
at System.Linq.SortContext`1[TElement].Compare (Int32 first_index, Int32
second_index) [0x00000] in <filename unknown>:0
at System.Linq.SortContext`1[TElement].Compare (Int32 first_index, Int32
second_index) [0x00000] in <filename unknown>:0
at System.Linq.SortContext`1[TElement].Compare (Int32 first_index, Int32
second_index) [0x00000] in <filename unknown>:0
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)
System.Linq.SortContext`1:Compare(Int32, Int32)

**Comment by MorrisRH** [comment] 2020-03-19 14:44
Is "Use YpCbCr420" in the iOS Platform Specific section of the Media Player settings checked?
If so, can you uncheck it?

**Comment by 1987skywalker** [comment] 2020-03-20 03:07
It's OK after I uncheck it. Is this a bug? Can you fix it? So I can use YpCbCr420 in iOS to improve performance.

**Comment by MorrisRH** [comment] 2020-03-20 11:50
The problem is that the older Unity's don't support the texture formats we're using internally. However we think we have a workaround which will be in the next release (1.10.2, hopefully being released later today).

It will be very handy if you can confirm that it works.

**Comment by 1987skywalker** [comment] 2020-03-23 03:15
Does it have better performance compare to unity's Handheld.PlayFullScreenMovie? I just use it to play fullscreenVideo.

**Comment by AndrewRH** [comment] 2020-03-23 13:06
Yes it should have better performance compared to Handheld.PlayFullScreenMovie.  If you upgrade to the latest version (1.10.2) you should be able to enable YCbCr option again.  Do let us know if this works for you and then we can close this ticket.  I hope this answers your question.  Thanks,

**Comment by AndrewRH** [comment] 2020-03-25 13:38
I believe this issue is now resolved (in the latest plugin version), so we will be closing this issue soon unless we hear otherwise.  Thanks,

**Closed** 2020-03-30 11:57 UTC
Labels: Fixed, iOS
