### ISSUE TITLE
Not rendering hls video in iOS 16.0.3

### ISSUE THREAD

**Issue by ofreyre** [RenderHeads/UnityPlugin-AVProVideo#1330] opened 2022-10-13 22:45 UTC
**Describe the issue**
HLS video is not rendering in iOS 16.0.3. The video is rendering in the Unity Editor and in Android.

 - Unity version: 2020.3.35f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v2.6.4 - 30 September 2022, Trial
 - Operating system version: iOS 16.0.3
 - Device model: iPhone SE 2020, iPhone 12.
 - Video specs (resolution, frame-rate, codec, file size):
   https://content.uplynk.com/6ec78e9a9922482f90964dc09f631c1f.m3u8

**To Reproduce**
1. Open Trial Demo project in Unity
2. Open the Demo_MediaPlayer scene
3. Select the MediaPlayer gameObject from scene hierarchy
4. In the Media Playe component inspector change Source/Settings/Media Source to Path.
5. In the Media Playe component inspector change Source/Settings/Absolute Path or URL paste the video url.
6. Add the Demo_MediaPlayer scene to Build setings.
7. Build XCode Project.
8. Build and run from XCode 14.0.1. (Monterrey 12.5.1)

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
https://content.uplynk.com/6ec78e9a9922482f90964dc09f631c1f.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com
![AVPro](https://user-images.githubusercontent.com/11655901/195724019-9dbfe494-a396-4f7d-bfcd-a5157616a88a.jpg)

**Comment by Chris-RH** [comment] 2022-10-14 09:39
Hi @ofreyre
Thank you for report.  
Have you tested this with other streams, such as these test streams: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams
Would you be able to provide a full log of the crash please?

**Comment by MorrisRH** [comment] 2022-10-14 10:27
Closing as duplicate of #1250

**Closed by MorrisRH** 2022-10-14 10:27 UTC
Labels: duplicate, iOS
