### ISSUE TITLE
Windows 7 systems with only IE8 instead of IE11 fail to load AVPro Video DLLs

### ISSUE THREAD

**Issue by long597957111** [RenderHeads/UnityPlugin-AVProVideo#855] opened 2021-07-08 09:46 UTC
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.3
 - AVPro Video version: 2.1.3
 - Operating system version: windows7 ultimate
 - Device model: 

**To Reproduce**
1. Some windows7 system gives raise to application crash or unity editor crash
2. I installed the pure version of win7 without installing anything extra.
**Logs**
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found
' (Address: 00140188)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed
' (Address: 00140188)
0x00140188 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found
' (Address: 111C5A20)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed
' (Address: 111C5A20)
0x111C5A20 ((<unknown>)) (function-name not available)

**Comment by AndrewRH** [comment] 2021-07-10 12:32
is this in the editor or a standalone build?
if it's a build - do you know if it's 32-bit or 64-bit, or whether this makes a difference?

Thanks,

**Comment by long597957111** [comment] 2021-07-12 01:38
1. Whether "biuld" or "editor" all gives raise to crash , i have tried to use 32-bit and 64-bit all unworkable
2. Win10 run very good, but Win7 cause a crash
3. Can you give us an idea?

**Comment by AndrewRH** [comment] 2021-07-12 06:50
please could you find out the exact windows 7 version number that it's not working on?

perhaps it's related to a specific version or SP1?

if you open our MediaPlayer demo scene, and set the Video API to "directshow" then does it work?

**Comment by long597957111** [comment] 2021-07-12 07:18
Version is Windows7 Ultimate X64 Service Pack1 (6.1,  version 7601). 
When I entered the Demo, it crashed before running "Unity3D". The dialog box shows that "UnityEditor" has stopped working.
According to the crash log, can you judge whether our computer is missing something?
Error log shows "Unable to find specified module and DLL initialization routine failed".

**Comment by AndrewRH** [comment] 2021-07-14 12:27
Thanks, it sounds like a dependency issue.  Please could you download and run [Dependency Walker](https://www.dependencywalker.com/) and drag in the AVProVideo.DLL and then the Audio360.DLL files (from the /Plugins/x86_64 folder) and then it will take a few minutes to scan dependencies... Then collapse all of the items in the expanded tree and you should see which DLLs it has a problem loading/finding.  You could send the screenshot here.

Thanks,

**Comment by long597957111** [comment] 2021-07-15 06:25
1.The first one is AVProVideo.DLL and second one is Audio360.DLL display result.
2.The Chinese red words means "System can't find specified file".
3.Do you know what document is missing?
![微信图片_20210715141225](https://user-images.githubusercontent.com/87122350/125738383-1233879a-f628-4475-b4da-3a38837a0ef9.png)
![audio360](https://user-images.githubusercontent.com/87122350/125738416-e31ae638-0c4f-4543-9ea2-556eb55d0edb.png)

**Comment by long597957111** [comment] 2021-07-15 08:49
Thank you very much!
Based on the tools(Dependency Walker) you provide,that problem is over.Before is IE8,upgraded to IE11 is ok.

**Comment by AndrewRH** [comment] 2021-07-15 11:23
Oh that's very strange!  I'm glad it is solved for you.  
We will have a look to see whether we can solve this for IE8

Thanks,

**Comment by long597957111** [comment] 2021-07-27 08:37
Hello AndrewRH,

I see this problem "Windows 7 Crash when using GPU without D3D11.1 support or without KB2670838 installed".
I tested it again,discover,the problems encountered were also caused by this patch.
Because,IE8 upgraded to IE11,patch KB2670838 must be installed.

Uninstall patch KB2670838.
Video API set to Media Foundation + Disable Hardware Decoding,this test doesn't work either.

**Comment by AndrewRH** [comment] 2021-07-27 12:57
Thank you, yes it looks like that is the cause.

We have fix coming in version 2.1.8 (releasing today).  Please could you test it and let us know if it solves your problem.

Thanks,

**Comment by long597957111** [comment] 2021-07-28 02:29
Thank you very much,that problem is over.

**Comment by AndrewRH** [comment] 2021-07-28 09:03
I'm glad to hear it's fixed.  I will close this issue now.

Thanks,

**Closed by AndrewRH** 2021-07-28 09:03 UTC
Labels: Bug 🐛, Fixed, Version 2.x, Windows
