### ISSUE TITLE
6950XT + SteamVR = Crash

### ISSUE THREAD

**Issue by rygo6** [RenderHeads/UnityPlugin-AVProVideo#1290] opened 2022-09-12 18:05 UTC
The 6000 series Radeon cards are currently crashing with the 22.8.2 driver when loading a video in a Unity VR application running through SteamVR. Specifically, this is happening in VRChat, so whatever version of Unity and and AVPro they are using. There have been multiple people with this issue: https://www.reddit.com/r/VRchat/comments/wxprxm/vrchat_avpro_crashing_with_6950xt/

The error AVPro gives is "[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources." 

The issue does not exist at all with the 22.5.1 AMD driver.

Please close this and punt entirely to the AMD drivers or VRC but figured I would open a ticket in case you had no knowledge of it and have better means to point out to AMD what they broke in their new driver. This probably affects other Unity titles too.

**Comment by Chris-RH** [comment] 2022-09-13 06:53
Hi @rygo6,
Thank you for your message.  I don't think that we have any of those cards to test with.  Could you provide a bit more information please.

1. Unity version:
2. AVPro Video version (number and edition (trial/core/ultra/enterprise)):
3. Operating system version:
4. Device model:
5. Using the demo media player scene, have you tried Media Foundation, DirectShow and WinRT APIs? 
6. What different sort of video files have you tried? (resolution, frame-rate, codec, file size etc?)

**Comment by FenrirVR** [comment] 2022-09-19 09:18
Can confirm the behaviour on an AMD 6800 XT as well with the Radeon Pro Driver 22Q2 leading to Unity crashing, as well triggering the bug report tool for the AMD drivers. The affected game would be ChilloutVR, they use AVPro for Youtube, Twitch and similar streaming inside their platform. A note here older versions of AVPro dont have this problem with newer AMD drivers, hope one of the CVR devs can give insight which versions exactly. 

Unity Version is: 2019.4.28f1
AVPro Version: Latest version 
Operating System: Windows 10 Pro  21H2
AMD Radeon 6800XT
Tested media was Youtube and Twitch streaming both leading to a Unity crash

**Comment by Chris-RH** [comment] 2022-09-20 08:09
Thank you.  Does it provide any sort of bug report for the user as well?

**Comment by FenrirVR** [comment] 2022-09-20 10:30
I think the devs of ChilloutVR also only run nvidia GPUs if im not mistaken, but maybe they can give some extra insight, meanwhile i can provide a logfiles and crash dumps with from the game, hope that helps. If thats not enough maybe i can grab the demo version of AVPro and see if it crashes inside Unity it self.

[Crash Dumps and Logs.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9606596/Crash.Dumps.and.Logs.zip)

**Comment by Chris-RH** [comment] 2022-09-20 10:45
"If thats not enough maybe i can grab the demo version of AVPro and see if it crashes inside Unity it self."
Please, that would be really helpful, its available here, thank you: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases

**Comment by FenrirVR** [comment] 2022-09-21 00:42
Ok some more tests just using AVPro inside Unity is fine no crashes at all testing the sample scenes as well trying a few random setups. Also i set up a basic SteamVR scene which sadly also refused to crash. So its a very specific build setting or setup inside the game that both ChilloutVR and VRChat use that triggers the crash on newer AMD drivers.

**Comment by FenrirVR** [comment] 2022-09-21 10:56
Ok little extra info which hopefully helps pinning this one down, the crash clearly only appears with using SteamVR, using the applications in desktop mode wont trigger it. Also both ChilloutVR and VRChat use a render texture to display the video inside maps/worlds.

**Comment by ronoverdrive** [comment] 2022-09-28 03:54
One thing to note is VRChat is using v2.5.6 Ultra. I don't know what version ChilloutVR is using, but I'm assuming v2.6.1 as a strong possibility as they mentioned in their release notes they updated to the latest literally a few days before the release of v2.6.2.

**Comment by Chris-RH** [comment] 2022-09-28 08:04
Thank you for the info.  We are in touch with the team from VRChat, and are trying to work out what is causing the problem.  For now I would suggest just going back to the previous driver version.

**Comment by FenrirVR** [comment] 2022-09-28 18:45
ChilloutVR uses version 2.6.0 cant say exactly say which was the version they used before the update but it should be something around 2.1.5 maybe a tad older but i doubt newer, this version was not effected and worked fine on Radeon Pro 22Q2 and other newer releases of the regular versions.

**Comment by ronoverdrive** [comment] 2022-09-29 01:48
Also I should probably point out this doesn't happen in Desktop Mode in VRChat only in VR Mode.

**Comment by JeremyDF93** [comment] 2022-10-10 04:50
I have this issue as well.

**Comment by Chris-RH** [comment] 2022-10-10 09:49
Thank you for the info. We are in touch with the team from VRChat, and are trying to work out what is causing the problem. For now I would suggest just going back to the previous driver version.

**Comment by soursecorst** [comment] 2022-11-10 21:11
Issue seems to be fixed on latest VRC update, atleast for me
VRChat ver. 2022.4.1p2
Radeon 6700 XT, driver ver. 22.10.3

**Comment by Chris-RH** [comment] 2022-11-11 09:29
@rygo6 and @ronoverdrive - have these issues been fixed for you with the latest VRChat update?

**Comment by JeremyDF93** [comment] 2022-11-11 11:16
Still crashing in VR.
VRChat 2022.4.1p2 
RX 6900 XT with software version 22.10.3

**Comment by Chris-RH** [comment] 2022-11-11 12:14
ok, thanks for the feedback :)

**Comment by ronoverdrive** [comment] 2022-11-11 23:58
> @rygo6 and @ronoverdrive - have these issues been fixed for you with the latest VRChat update?

Looks like it working for me. I tried a known movie world with a video I know caused it to crash previously and for me it seems to be working.

Windows 10
SteamVR + Index HMD
6800XT, driver 22.10.3

**Comment by QuantumFur** [comment] 2022-11-12 21:59
> @rygo6 and @ronoverdrive - have these issues been fixed for you with the latest VRChat update?
Still getting crashes on 22.10.3 and below until 22.5.1

Windows 10 22H2
SteamVR + Vive Pro Eye
6950XT

ronoverdrive do you happen to have anything tweaked with your stuff? Did you use DDU or upgrade drivers directly?

**Comment by ronoverdrive** [comment] 2022-11-13 02:52
Well spoke too soon. Was watching a video with friends and half way through the video it crashed then every time I came back to the world it crashed again. Checked the log from the first crash and nothing was there indicating an error. Then after that the "[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources." re-appeared in each log it crashed after that.

**Comment by Chris-RH** [comment] 2022-11-14 09:19
OK, thanks for letting us know

**Comment by ronoverdrive** [comment] 2022-11-16 02:13
> OK, thanks for letting us know

NP, honestly it does not look like VRChat has touched their version of AVPRo, looks like they're still using 2.5.6 that they've been using since July.

**Comment by ronoverdrive** [comment] 2022-11-16 05:05
> Word on the VR street is its fixed in the driver slated to release with 7000 series launch.

Honestly a few of us thought the same would happen with 22.10.2 with all the video relation fixes. Hopefully we get a fix soon, I have barely stepped into VRChat because of this. Basically I am forced to choose between riding on 22.5.1 and dealing with driver bugs in other games, riding on the latest so the majority of my games run well and avoid VRChat chill worlds when I can, or downgrade to 22.5.1 every time I want to have an extended stay in VRChat.

**Comment by Chris-RH** [comment] 2022-11-16 10:00
As mentioned, we have been in contact with VRChat and they are working on it. 
Hopefully this will get fixed in the next update.

**Comment by ronoverdrive** [comment] 2022-11-17 00:12
> You can delete the two AVProVideo dll's from `VRChat_Data\Plugins\x86_64` and the game will still launch and run fine on current drivers. This usually results in fallback to the Unity Video Player and allows most SD/YouTube videos to play.

Thanks for the tip, if only we didn't have to deal with EAC we'd probably be able to swap DLL files.

**Comment by pandages** [comment] 2022-11-21 19:03
> As mentioned, we have been in contact with VRChat and they are working on it. Hopefully this will get fixed in the next update.

is there anything I can do to help? Because I can say I've been dealing with this issue for coming on 6 months now and it's driving me crazy.  I'm ready for it to be resolved.  So any assistance I can provide, I'll do so happily.

**Comment by sylveon** [comment] 2022-12-01 17:47
This has been fixed in 22.11.2, which released just today.

**Comment by Alex-Garay** [comment] 2022-12-01 23:45
> This has been fixed in 22.11.2, which released just today.

I will update to 22.11.2 and do some testing. I will report back with my findings.

**Comment by JeremyDF93** [comment] 2022-12-02 00:18
Updated to `22.11.2` and tested a few worlds that specifically use AVProVideo and I can confirm that it is fixed in this release.

**Comment by rygo6** [comment] 2022-12-02 07:33
Jeez took them like 7 months. I really hope AMD is trying to prioritize their gaming driver teams and put more resource to it.

**Comment by Chris-RH** [comment] 2022-12-02 09:19
@ronoverdrive @pandages @FenrirVR @QuantumFur can you confirm that the 22.11.2 update has fixed it for you please? :)

**Comment by pandages** [comment] 2022-12-02 13:40
> @ronoverdrive @pandages @FenrirVR @QuantumFur can you confirm that the 22.11.2 update has fixed it for you please? :)

performed an upgrade installation from 22.5.1 yesterday upon hearing of 22.11.2, and then did a 2 hour long test in VRchat (which uses in the impacted version of AVProVideo).  No issues during that initial test.  So far, so good!

**Comment by rygo6** [comment] 2022-12-03 20:47
So 22.11.2 did fix the AVPro crashing bug...

...but now you can get some weird crash due to some combination of shaders and mirrors :( Okay think it's time to get a 4090. AMD is not suitable for VRC.

**Comment by sylveon** [comment] 2022-12-03 21:28
@rygo6 do you know which shader causes this? Or have a public avatar that can repro this, at least? I can take a look this Monday.

**Comment by rygo6** [comment] 2022-12-03 22:05
Well, that's the complication of VRChat. It is user generated content. There are thousands of shaders. Unfortunately, the exact combination I never figured out because whoever had the shader on their avatar that caused the issue left before I could. Even more unfortunate it wasn't just one shader, but specifically some shader through a mirror. It's a combination of shaders made by different people.

The only thing I can think of to deal with this is coming up with some way to fuzz shaders. 

Really this might be quite a pernicious issue for AMD. I presume AMD has thought more along the lines that developers will test on AMD and then fix things for AMD. But in a user generated content paradigm that's just not going to happen. People will just make things and primarily test on only nvidia because that is what most have, then you end up with a minefield of crashes for AMD users that wander through the same virtual spaces. I know from a business and corporate perspective how hard that will be to communicate the significance of, saying you need to invent some new way of automated shader testing to get rid of a tiny percentage of random crashes in one VR game. But VRC is the killer VR app for PC and it is dictating what people buy for VR. Even just one random crash a week is enough of an annoyance that it will continue to make everyone steer clear of AMD for VR, and VR is a small market segment, but its growing and if that reputation is getting solidified now, could take years to undo.

Really, if I worked at AMD I would try to convince them to put together a team solely to develop some new system of automated shader tests. If AMD is hiring, you could maybe convince me to do this :) it does sound like it'd be fun.

**Comment by Chris-RH** [comment] 2022-12-09 11:16
OK, I think I'm going to close this now as it seems like AMD have fixed it.

**Closed by Chris-RH** 2022-12-09 11:16 UTC
Labels: need more info 🤷, pinned

**Comment by tgrafk12** [comment] 2022-12-16 00:03
AMD has not fixed this issue, as I'm still receiving issues on multiple VRChat worlds. 

The desktop version works fine, its only in steam VR,
tested in SteamVR  v1.24.6, with driver version 22.11.2 and SteamVR v1.23.7 22.11.2, both versions result in laggy choppy frames, playback issues, and preloaded frames of up to 2-5 and looping, flashing green playback upon loading, multiple pc crashes with no bluescreens, just a complete power down and boot back to windows.

the only driver that works with flawless playback and no issues at all running even the SteamVR beta 1.25.1 on AMD driver version 22.9.2 
*and i went thru tons of past drivers, from 22.11.1-22.10.3-22.9.1.-22.4.1-etc.
all drives EXCEPT 22.9.2 work perfectly, after VRC did an update to Groups, it started to malfunction, which was about the same time that the standard updated. 
Anyways, not sure if this helps, but I'm starting to get tired of video playback not working
I have a FE 6900xt with stock clocks and OC profiles ready, if you need me to run tests, please hit me up on Discord
Index HMD
FadedQuill7#8725

**Comment by sylveon** [comment] 2022-12-16 00:07
We're aware of the stutter/looping playback issues and are investigating.

**Comment by tgrafk12** [comment] 2022-12-16 00:08
> 

awesome! if you need testing, I'm totally down to help test!

**Comment by tgrafk12** [comment] 2022-12-20 13:54
been a few days, is there anything i can do to speed up this process? or help in someway?

**Comment by Chris-RH** [comment] 2022-12-21 11:09
VRChat are working on this internally, so there is nothing that you can do at this end I'm afraid, but thank you for offering.

**Comment by tgrafk12** [comment] 2023-01-14 02:57
Has this issue been resolved yet? so I can update to the latest drivers?

**Comment by pandages** [comment] 2023-01-17 16:20
Stuttering Issue still persists, and has occasionally caused me to crash (driver timeout) when several instances of video playback are within the same world.

**Comment by tgrafk12** [comment] 2023-01-23 09:20
Leave it to VRC devs to update their game... 
In all honesty, I'm pretty sure they don't even know it's an issue, they have "better ideas" to work on instead, like groups and banning cheaters instead.
sadly, I'm pretty sure they marked this as *fixed* and they won't update their side to fix this in the future, so. 
and it doesn't even seem to appear on their bug list either. so there's not really much hope for it being fixed. 
if I know VRChat devs, if they think it's *Fixed*, they think it's fixed, just like putting in EAC to prevent mods from being loaded but we all know that we can still bypass it. so.

Looks like I'm stuck on 22.4.1 for now until there's more I can find out on. Ill Post here again _if_ they finally fix it:<

**Comment by tgrafk12** [comment] 2023-01-31 06:14
yep! i was right!
Dosent look like they have plans to update it, how fucking right i was
so im going to have a vrchat dev tell me its a driver issue, and not even LOOK into the report i made, i dident even tell them what DRIVER version i used, so thats already a lie!
How dumb do they look on their part, cause if they read my report, they would have LOOKED here! BUT THEY DIDENT!
UNREAL!

![imagee](https://user-images.githubusercontent.com/36301692/215680743-dabe68b0-c04a-489e-8c1d-cb278a420692.png)

**Comment by pandages** [comment] 2023-01-31 20:54
So let's send in some more support requests to the VRchat devs.  I'd be happy to file one myself, I'm having the issue, and it remains unresolved.

What do you suggest, @tgrafk12 ?

**Comment by tgrafk12** [comment] 2023-01-31 21:24
honestly, i would yeah, im upset with them, cause clearly, they dont give a shit

**Comment by QuantumFur** [comment] 2023-01-31 21:32
Have to stick on 22.5.1 here until it gets any better. It's the first driver for the 6950XT and I wouldn't want to run into trouble for going lower on unofficial support.

Missing out on better encoding features and OpenGL performance so far.

Who is to blame anyway? Probably AMD but I'd wish that we're sure VRC devs are not sitting still on it. That they are actually pointing at it for AMD.

**Comment by tgrafk12** [comment] 2023-02-01 16:27
@QuantumFur 
it is the vrc's devs.
they are lazy and just dont want to update a game. again, read up here https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1290#issuecomment-1409826264
sadly, they just, dont give a shit about our community anymore, and its really upsetting to see it. maybe they will update it, who knows. 
your best bet is to open a ticket and complain that the latest drivers wont work for AVPro and any media played just dosent work

**Comment by pandages** [comment] 2023-02-01 17:17
I filed a support ticket with VRchat.  I referenced this thread.  I am hoping that if they get a number of reports they will look into it.

WHY Do developers not QA on AMD hardware? I Don't understand that choice.  I get that they should absolutely have Nvidia hardware for QA, but it shouldn't be entirely Nvidia hardware.

**Comment by tgrafk12** [comment] 2023-02-01 17:29
no, its not QA, its just the devs.
see, their process of fixing things is, if its "fixed" we never need to go back and fix it again
The problem is, vrchat updated with a fix to the game that actually fixed the issue, THEN, about 2 or so days after, AVPro updated their codec, rendering the vrchat update practically useless. 
it is now up to vrchat, and their lazy asses, to UPDATE the dll for the game. 
im not so sure why this is an issue for them, but they already placed a gold star on their paper and started patting themselves on the back too early.

**Comment by tgrafk12** [comment] 2023-02-03 00:35
LOL
They just pushed an update and said nothing about updating the AVPro encoder, thats WACK AS FUCK. 
guys, i think we should just give up. ether that, or we need to go straight to the top and say something, cause clearly they just, DO NOT care.

**Comment by tgrafk12** [comment] 2023-02-03 03:43
finally ranted about it in the discord, apparently, Tupper was in there, and actually gave me an answer instead of the support team just telling me to update my drivers. 
Apparently, they're waiting on AMD to push a new driver update, they tried updating the AVPro encoder and they did. so now we wait for AMD. what a waste of time.

**Comment by Chris-RH** [comment] 2023-02-03 10:10
The problem with working with a large company like AMD is that it can take a while for the gears to turn, because they'll probably need to do a lot of testing before each new driver is released.  Their bug list will be huge and it will take a long time to get through everything.  What is a smaller issue to them will be likely pushed to the side unfortunately.

**Comment by sylveon** [comment] 2023-02-03 10:27
In my experience during my internship there, if the issue is simple to reproduce and not hard to fix, it usually gets fixed fairly fast internally once reported. However (and this is what gives the feel of fixes being slow moving) it can take a while for said fix to surface to a public driver.

**Comment by QuantumFur** [comment] 2023-02-24 03:15
This is surely just an AVpro related issue though. Because other players don't have any issues.

**Comment by urgerestraint** [comment] 2023-03-09 12:03
Can confirm the stuttering is still occurring on AMD Software: Adrenalin Edition 23.3.1 Driver Version 22.40.37.01 for Windows® 10 and Windows® 11 (Windows Driver Store Version 31.0.14037.1007).

Again this only affects AVPro, standard Unity Video Player appears unaffected.

**Comment by Chris-RH** [comment] 2023-03-09 12:12
You need to contact SteamVR about this please

**Comment by QuantumFur** [comment] 2023-04-24 10:34
Not long ago there was a new update that introduced "--disable-hw-video-decoding" as a launch setting which fixes the issue at the cost of CPU performance.

The loss is not noticeable from what I have, another alternative solution is to use NimeZ drivers 22.11.2 with 22.5.1 kernel LTS to keep hardware acceleration, this only works with 6000 series however.

**Comment by rygo6** [comment] 2023-04-27 02:49
One thing with AMD, make sure everything is up to date with the latest drivers downloaded from the AMD website, not ASUS/ASROCK/GIGABYTE etc. website as they can often be out of date. Everything. Flash to latest bios. Latest chipset driver. Latest built-in audio driver (or disable bulti-in if you dont use it!) When I had all AMD it wasn't just the graphics driver that caused issues, but every other driver at some point contributed to something funky. Same thing for Windows updates. I actually no longer have much issue with Win11 even.

But really, AMD is probably going to struggle with VRC because its a UGC platform.
