### ISSUE TITLE
Black screen on iOS.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1572] opened 2023-06-26 09:10 UTC
Black screen on iOS.
Continue to call OpenMedia and CloseMedia repeatedly.
At some point, the screen displays a black texture. However, the sound is output.

One strange thing is the data below. Occurred in FirstFrameReady event.
`"length":4355.25,"current":0.000001,"bufferedTimeMin":9.999999974752428e-7,"bufferedTimeMax":17.95126724243164`

My code:
```
eventData.details.length = player.GetVideoLength();
eventData.details.current = player.GetCurrentTime();

Vector2 bufferedTime = player.GetBufferedTime();
eventData.details.bufferedTimeMin = bufferedTime.x;
eventData.details.bufferedTimeMax = bufferedTime.y;
```

`current`, `bufferedTimeMin` is too stragne.
I think the previous data is left.

 - Unity version: Unity 2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core
 - Operating system version: iOS 14.6, 15.1, 16.4.1
 - Device model: iPhone 11, iPhone 12 Mini, iPhone SE3
 - Video specs (resolution, frame-rate, codec, file size): https://mediapoccdn2-standard-ms-ams.azureedge.net/ebd5f61c-732e-4b6c-88ac-2a377a39bce5/92a72576-c80e-4994-bfc2-2dd3778f.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8

**Comment by Chris-RH** [comment] 2023-06-28 09:21
1. Are you able to provide logs from before the crash?
2. How long is it taking to crash?
3. Are you running it from a new project just with AVPRo Video and your code?
4. Are you just doing it using a single video?
5. Have you tried different videos?

**Comment by Chris-RH** [comment] 2023-06-28 12:56
OK, can you provide logs?
How long does it take before black screen?

**Comment by dw8869** [comment] 2023-06-28 13:10
log: [3.0.5(3)_ucf log on_라운지스크린검은화면.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11895030/3.0.5.3._ucf.log.on_.log)

**Comment by MorrisRH** [comment] 2023-06-30 16:47
Possibly linked to #1095

**Comment by dw8869** [comment] 2023-07-03 01:43
@MorrisRH 
I also wrote a comment on #1095 , but is the problem solved?

**Comment by Chris-RH** [comment] 2023-07-04 10:26
If you could provide a small test project that shows the issue then we will investigate further. Please send it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com).

**Comment by MorrisRH** [comment] 2023-07-04 10:27
Hey @dw8869, as I've been unable to reproduce it I cannot say if it's been solved or not. If you're still seeing it with the latest AVPro version then it would be great if you're able to provide a reproducible test case so that we can investigate further (if so please send to unitysupport@renderheads.com)

**Comment by dw8869** [comment] 2023-07-07 05:03
I'll investigate further and let you know.

**Comment by Chris-RH** [comment] 2023-07-14 10:51
Any luck?

**Comment by Chris-RH** [comment] 2023-07-21 10:36
Closing due to lack of reply. please reopen if this is still an issue and email us a reproducible test case :).

**Closed by Chris-RH** 2023-07-21 10:36 UTC
Labels: iOS, Could not reproduce 🤷

**Comment by luankun** [comment] 2024-01-26 06:39
Our project also encountered a black screen issue when playing videos on iOS devices. One consistent observation is that once one video starts playing with a black screen, all other videos also play with a black screen. However, most of the devices can recover from this issue after a restart.
