### ISSUE TITLE
Crash when call SetAudioTrack on iOS

### ISSUE THREAD

**Issue by crazylulu9999** [RenderHeads/UnityPlugin-AVProVideo#120] opened 2019-07-13 18:10 UTC
**Describe the bug**
Crash when call SetAudioTrack on iOS
(Cannot reproduce on Android)

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.4f1
 - AVPro Video version: 1.9.17b
 - Operating system version: iOS 12.3.1
 - Device model: iPad mini 5
 - Video specs (resolution, frame-rate, codec, file size): FHD, 30FPS, H264, AAC, 10sec, 3 audio tracks (no and 2 languages)

**To Reproduce**
1. OpenVideoFromFile(RelativeToStreamingAssetsFolder, path, false)
2. Wait until Control.CanPlay()
3. Control.SetAudioTrack(1 or 2)
4. Control.Play()

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment] 2019-07-16 10:14
Can you provide a copy of the video you are trying to play?

**Comment by crazylulu9999** [comment] 2019-07-19 00:48
Hi, This is the video. (3 audio tracks)
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/120#issuecomment-511756116

 video_cha_231_caroline_login_merged.mp4
<https://drive.google.com/file/d/0BxbCSDOFflxGRlVKUGVpUHBJd0w1VDFCa0hlQ1VweVdJa084/view?usp=drive_web>


2019년 7월 16일 (화) 오후 7:14, Ste Butcher <notifications@github.com>님이 작성:

**Comment by crazylulu9999** [comment] 2019-07-19 00:51
> Can you provide a copy of the video you are trying to play?
I sent but returned. (too big attached file error)
So resend with rink.

**Comment by MorrisRH** [comment] 2019-07-19 10:06
Thanks for the video file. The problem is that all the audio tracks are marked as default so the player only sees 1 audio track and the crash was as a result of trying to switch to another audio track.

MediaPlayer.Info.GetAudioTrackCount() would have returned 1.
MediaPlayer.Control.SetAudioTrack(2) would then cause the crash.

We'll get the crash issue fixed for the next release.

In order to fix your video you need to make sure only one audio track is marked as default. You can use the following ffmpeg command to achieve that:
```
ffmpeg -i in.mp4 -c copy -map 0:0:v:0 -map 0:1:a:1 -map 0:2:a:2 -map 0:3:a:3 -disposition:a:1 0 -disposition:a:2 0 out.mp4
```

**Closed by MorrisRH** 2019-07-19 10:06 UTC
Labels: bug, iOS, need more info
