### ISSUE TITLE
Audio cuts out prematurely when using Unity audio.

### ISSUE THREAD

**Issue by gautam-strivr** [RenderHeads/UnityPlugin-AVProVideo#55] opened 2019-05-17 16:30 UTC
**Describe the bug**
Audio cuts out prematurely when using Unity audio with any video in Windows 10, independent of file size. If there is audio during the last half second or so, it will not be audible.

**Your Setup (please complete the following information):**
 - Unity version: 2018.2.17f1
 - AVPro Video version: 1.19.14 
 - Operating system version: Windows 10 Pro 17763.503
 - Device model: MSI GS65 Stealth
 - Video specs (resolution, frame-rate, codec, file size): 640x360, H.264, 174KB

Reproduction steps and a sample project have been emailed.

**Comment by AndrewRH** [comment] 2019-05-25 16:16
Thanks for this.  We have reproduced the issue.  It is related to using the AudioOutput component.  It's proving to be quite tricky to resolved so far.

**Comment by esDotDev** [comment] 2019-08-10 04:09
Any movement on this? We have discovered similar issues in an installation, and the Client is requesting a fix.

**Comment by takwaiw** [comment] 2019-09-20 01:02
Hi Andrew, 
Our customers are complaining about a batch of video with this problem, and we can't work around it. Can you give us an update on this issue?

**Comment by AndrewRH** [comment] 2019-09-20 11:10
Thanks.  Well one workaround for this would be to to pad the end of your video so it is a little bit longer (the video track only, keep the audio the same length so the fade down works).

**Comment by esDotDev** [comment] 2019-09-20 14:08
Ya, the problem is that we have about 1000 videos from a major league sports client, and they are not too keen on re-cutting all 1000 of them. Also most of the clips have a commentator speaking right up until the end of the video, so it's quite obvious when one of the words gets clipped.

**Comment by AndrewRH** [comment] 2019-09-20 16:00
> Ya, the problem is that we have about 1000 videos from a major league sports client, and they are not too keen on re-cutting all 1000 of them. In our case most of the clips have a commentator speaking right up until the end of the video, so it's quite obvious when one of the words gets clipped.

Understood.  This is an issue we're looking into.

**Comment by AndrewRH** [comment] 2020-08-26 13:05
This has been fixed in AVPro Video 2.0

Thanks,

**Closed by AndrewRH** 2020-08-26 13:05 UTC
Labels: Bug 🐛, Windows
