### ISSUE TITLE
[Android] Last frame of the last viewed video is displayed on the next video

### ISSUE THREAD

**Issue by SlavomirDev** [RenderHeads/UnityPlugin-AVProVideo#1965] opened 2024-08-12 14:06 UTC
Describe the issue
When opening the video, the last frame from the previous viewed video is shown for about 2 Unity frames

Our setup:
 - Unity 2022.3.24f: 
 - AVPro Video version 3.0.8 ultra: 
 - Android: 
 - Any android device and also any Meta Quest:
 - Any:

How to Reproduce
1. Open any video;
2. Close this video on any time
3. Open new video

**Comment by Chris-RH** [comment] 2024-08-16 12:55
Are you opening and closing the video in the same mediaplayer component?
Have you tried using our playlist feature?
Is this playing local videos or streaming?
Is this Exoplayer or Android mediaplayer?
Can you reproduce this in the editor?
Is this reproducible in a new project running the demo scene and as little changes as possible?

**Comment by SlavomirDev** [comment] 2024-08-16 15:24
Hi Chris!
I want to note that I upgraded from version 2.7.3 to 3.0.8 and it worked for me in 2.7.3 version, and in 3 this problem appeared

But now about your questions:
1. Yes. It's the same component;
2. No, i don't need it;
3. Streaming;
4. ExoPlayer;
5. No. This is a bug only on the Android;
6. No, i didn't check on it. And still it only reproduced on Android;
7. Unfortunately not.

**Comment by thesanketkale** [comment] 2024-08-30 12:55
Hi @Chris-RH, I am facing the same issue on Android. Like @SlavomirDev, it used to work back in v2.9.3 but not in 3.0.8. Is there any new API that can clean the DisplayUGUI render image or the media player cache?

Need some fix or a workaround for an app update.

**Comment by MorrisRH** [comment] 2024-09-02 09:50
Using OpenGL ES3 as the renderer, set the media player's texture mode to YCbCr420 OES as this does not require textures to be created internally so when CloseMedia is called no texture will be produced.

We're looking into how we can make this work with the BGRA texture mode and Vulkan renderers but this is not a trivial change.

**Comment by thesanketkale** [comment] 2024-09-02 12:46
> Using OpenGL ES3 as the renderer, set the media player's texture mode to YCbCr420 OES as this does not require textures to be created internally so when CloseMedia is called no texture will be produced.

Hey @MorrisRH, thanks for sharing the workaround. 

I tried changing the texture mode but the issue persists. I think in my case I am not calling CloseMedia on the previous video before switching to the next video. Could that be the cause?

**Comment by Ste-RH** [comment] 2024-09-06 14:21
AVPro Video v3.0.10 has now been released.  Do let us know if this fixes the issue for you.

**Comment by thesanketkale** [comment] 2024-09-07 13:20
I tried the v3.0.10 but the issue persists for me. 

By the way, I have HLS-encoded videos (.m3u8) streaming in the media player. I am switching the URL on the next button click after stopping the previous video and then playing the next video. Do I need to do something different to solve this?

**Comment by MorrisRH** [comment] 2024-09-10 14:23
This has now been fixed and will make it into the next release (version 3.0.11).

**Comment by Ste-RH** [comment] 2024-09-12 16:04
@SlavomirDev @thesanketkale AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.

**Closed** 2024-09-19 08:00 UTC
Labels: Bug 🐛, Android, Fixed

**Comment by SlavomirDev** [comment] 2024-12-11 15:27
Yeah, this fixed. I was testing in 3.1.3 version. Thanks!
