### ISSUE TITLE
Random Crash on iPhone

### ISSUE THREAD

**Issue by tomh520** [RenderHeads/UnityPlugin-AVProVideo#1725] opened 2024-01-05 07:23 UTC
Recently, we have received some crash reports on iPhone. The stack trace is as follows, and due to unknown reasons, we have not been able to successfully resolve the function names. We hope to receive your assistance.

0 AVProVideo 0x104b16a30 0x104ae8000 +191024
1 MediaToolbox 0x18d7c6b8c 0x18d410000 +3894156
2 MediaToolbox 0x18d7c6970 0x18d410000 +3893616
3 CoreMedia 0x18dd2d668 0x18dc37000 +1009256

 - Unity version:  2019.4.13f1
 - AVPro Video version (2.5.7 (Apple 2.5.4)）edition (core): 
 - Operating system version: iOS
 - Device model: iPhone

**Comment by Chris-RH** [comment] 2024-01-05 09:18
Please can you upgrade to the latest version of AVPro Video and then retest. That one is 6 months old and there have been several fixes since then.

We also need more information:

1. What model of device the issue is on
2. What OS version the device is running
3. What are the specs of the video being played
4. What happens in the run up to the crash

**Comment by tomh520** [comment] 2024-01-10 10:31
We have planned to upgrade to the latest version of AVProVideo, but it will take some time before the new version is available.

1. This includes but is not limited to iPhone12 and iPhone13.
2. This includes but is not limited to iOS 16 and iOS 17.
3. The video specifications are streaming, .mp4, 720P, but not for any specific video.
4. There were no specific actions before the crash occurred; it was simply playing a remote video.

**Comment by Chris-RH** [comment] 2024-01-10 11:14
OK, well could you update us and let us know if this is still occurring when you are using the latest version please.

**Comment by tomh520** [comment] 2024-01-12 02:53
get

**Comment by Chris-RH** [comment] 2024-01-15 10:31
I'm going to close this for now, but please reopen it once you update if there is still an issue.

**Closed by Chris-RH** 2024-01-15 10:31 UTC
Labels: iOS, need more info 🤷
