### ISSUE TITLE
When the IOS alarm clock pops up, the video is stuck. Turn off the alarm clock pop-up, or is it stuck

### ISSUE THREAD

**Issue by mengflyQ** [RenderHeads/UnityPlugin-AVProVideo#819] opened 2021-06-16 09:04 UTC
**Describe the issue**
When the IOS alarm clock pops up, the video is stuck. Turn off the alarm clock pop-up, or is it stuck

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.12f
 - AVPro Video version: 1.11.7
 - Operating system version: ios 14.2
 - Device model: iphonex
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. When the video pop-up window is closed, the video can resume playing
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
2569386351@qq.com

**Comment by MorrisRH** [comment] 2021-06-16 09:54
This is standard behaviour on iOS, any external event will cause the video to pause playback. I suggest you add a listener for the paused event and if it triggers unexpectedly either resume playback or offer a resume option to your users.

**Comment by kahnivore** [comment] 2021-06-21 08:27
@mengflyQ I hope these suggestions were helpful. Closing this as it is not a bug.

**Closed by kahnivore** 2021-06-21 08:27 UTC
Labels: Version 1.x, iOS
