### ISSUE TITLE
Random crash on Hololens 2 when using WinRT API

### ISSUE THREAD

**Issue by mhlqk123** [RenderHeads/UnityPlugin-AVProVideo#1124] opened 2022-03-05 06:25 UTC
**Describe the issue**
Obtain MP4 files from the network and save them to the **persistentdatapath**，
then use **MediaPlayer.OpenMedia** to play.
There is no problem on the PC side,
But hololens2 crashes occasionally, it will cause the program to crash and exit directly.

**Your Setup (please complete the following information):**
 - Unity version: **Unity2020.3.30**
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): **AVPro Video - Ultra Edition**
 - Operating system version: WIN10
 - Device model: Hololens2
 - Video specs (resolution, frame-rate, codec, file size):  MP4

**Comment by AndrewRH** [comment] 2022-03-05 13:38
I wonder if it's related to timing....  If you wait a bit after the copy perhaps it works?  It could be a write-caching issue....

**Comment by mhlqk123** [comment] 2022-03-07 01:25
It's my code.

`IEnumerator ShowVideo(string title, string file)
    {
        yield return new WaitForSeconds(1f);
        FT_MediaPlayer.OpenMedia(new MediaReference() {  MediaPath = new MediaPath(file, MediaPathType.AbsolutePathOrURL) }, false);
        yield return new WaitForSeconds(1f);
        FT_MediaPlayer.Play();
        yield return null;
    }`

**Comment by mhlqk123** [comment] 2022-03-07 01:26
It's my code.

`IEnumerator ShowVideo(string title, string file)

{
        yield return new WaitForSeconds(1f);
        FT_MediaPlayer.OpenMedia(new MediaReference() {  MediaPath = new MediaPath(file, MediaPathType.AbsolutePathOrURL) }, false);
        yield return new WaitForSeconds(1f);
        FT_MediaPlayer.Play();
        yield return null;
    }`

**Comment by AndrewRH** [comment] 2022-03-07 13:22
It may be related to the way you're trying to open the media.  

A MediaReference is a ScriptableObject, so it's something that should be created ahead of time in the editor.

If you want to just load a video try this:

FT_MediaPlayer.OpenMedia(new MediaPath(file, MediaPathType.AbsolutePathOrURL), false);

More examples of loading code can be found [here](https://www.renderheads.com/content/docs/AVProVideo/articles/usage-loading-media.html).
    
Does that help?

**Comment by mhlqk123** [comment] 2022-03-08 02:11
Tried it, still doesn't work.

`IEnumerator ShowVideo(string title, string file)
    {
        FT_MediaPlayer.OpenMedia(new MediaPath(file, MediaPathType.AbsolutePathOrURL));
        yield return null;
    }`

**Comment by kahnivore** [comment] 2022-03-08 08:32
By still doesn't work, do you mean it crashes? What about taking your code out of a coroutine to simplify, just to rule out anything going wrong with the code.

**Comment by AndrewRH** [comment] 2022-03-08 08:42
yeah, and is there a crash log?

**Comment by mhlqk123** [comment] 2022-03-08 08:42
Yes, this code will cause the program to crash.
There was no coroutine before,and there were fewer crashes after adding, so add it.
Simply, the path is persistentdatapath, and a MP4 file almost 240KB (No matter how big). The code is this sentence. It will crash here and the probability is quite high.

**Comment by mhlqk123** [comment] 2022-03-08 08:43
Crash without any logs.

**Comment by mhlqk123** [comment] 2022-03-08 08:53
![image](https://user-images.githubusercontent.com/27323657/157201669-1847f916-e880-4a59-a3b9-42bef61f5841.png)

**Comment by mhlqk123** [comment] 2022-03-09 02:19
Because I don't know what information I should provide you.

I've tried **Media Foundation** and it doesn't seem to crash anymore.

Ths.

**Comment by kahnivore** [comment] 2022-03-11 11:23
So the crash is with WinRT only?

**Comment by mhlqk123** [comment] 2022-03-12 02:16
It does seem so at present.

**Comment by kahnivore** [comment] 2022-03-15 15:17
Closing this as there seems to be a workaround and we currently can't reproduce without access to a Hololens 2.

Please feel free to reopen the issue if more support is needed.

**Closed by kahnivore** 2022-03-15 15:17 UTC
Labels: Bug 🐛, Windows
