### ISSUE TITLE
Unity AVPro core edition breaking Unity cloud builds on iOS

### ISSUE THREAD

**Issue by suwas-subvrsive** [RenderHeads/UnityPlugin-AVProVideo#814] opened 2021-06-08 18:12 UTC
Unity AVPro core edition breaking Unity cloud builds on iOS

It seems like as soon as I import AVPro Video - Core Edition plugin unity cloud builds for iOS start failing. I have reported this to the Unity cloud build team as well but figured I should post it here too since it's relevant.

 - Unity version: 2020.3.9f1
 - AVPro Video version: 2.1.3f1 core
 - Operating system version: iOS

**Logs**
fastlane finished with errors
Error packaging up the application
! build of 'ios-dev' failed. ! xcode build failed.

[CloudBuildErrorLog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6618716/CloudBuildErrorLog.txt)

Am I missing anything here?

**Comment by MorrisRH** [comment] 2021-06-09 08:42
From the log file I can see that the archive process succeeded but the export is failing for some reason, unfortunately there is not enough information there to work out what is going on.

The log does mention the following though:
> 📋  For the complete and more detailed error log, check the full log at:
> 📋  /BUILD_PATH/Library/Logs/gym/DigiKeyBoardsGuide2021-Unity-iPhone.log

Are you able to get the full log from the system?

**Comment by SuwasSVR** [comment] 2021-06-09 23:38
Here's the full xcode log

[subvrsive-cloudbuildtest-ios-master-4-CloudBuildTest-Unity-iPhone.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6627428/subvrsive-cloudbuildtest-ios-master-4-CloudBuildTest-Unity-iPhone.log)

**Comment by MorrisRH** [comment] 2021-06-10 10:48
Can't see anything wrong in there.

Has cloud build worked for you previously? If so, which version of AVPro Video and Unity were you using?

**Comment by SuwasSVR** [comment] 2021-06-10 16:43
Cloud builds have always worked for me. AVPro 1.x worked with cloud builds.

**Comment by MorrisRH** [comment] 2021-06-10 16:48
Have you had cloud build working with an earlier version of AVPro Video 2.x or with the trial version? 
I'm trying to work out if this is a new problem with version 2.1.3 or whether it has always existed and whether the problem is specific to the core edition.

**Comment by SuwasSVR** [comment] 2021-06-10 17:01
I haven't tried earlier versino of AVPro Video 2.x. But, I have tried the AVPro Android 2.x version with cloud builds and it works. I haven't tried the  AVPro iOS 2.x version. But with the AVPro core 2.x version which supports all platforms.. cloud builds for android work but iOS cloud builds break. Local iOS builds work. It could a case where it's not able to resolve the platform specific  plugin stuff within the AVPro Video core edition 2.x version.

**Comment by MorrisRH** [comment] 2021-06-11 11:56
I'm wondering if #810 is causing the failure with the cloud build, are you able to try a build with the trial version?

**Comment by SuwasSVR** [comment] 2021-06-15 17:49
I updated AVPro to 2.1.4 which has the fix for #810 but that didn't seem to fix it. 

Here's an interesting data point @MorrisRH : I tried archiving the project using Xcode 12.4 and it fails but with Xcode 12.5 it works. Unity cloud build doesn't support Xcode 12.5 yet. So, I'm assuming that's the reason the cloud builds were failing. For some reason when you try to Build and Run using Xcode 12.4 & 12.5 it works fine. 

Here are the error logs for the failed Xcode 12.4 archiving process:
[IDEDistribution.verbose.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6657639/IDEDistribution.verbose.log)
[IDEDistributionPipeline.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6657640/IDEDistributionPipeline.log)
[IDEDistribution.standard.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6657641/IDEDistribution.standard.log)

**Comment by MorrisRH** [comment] 2021-06-16 09:49
Looking at those logs it does look like issue #810 is the problem. Unfortunately our fix runs too late in the process for the first build, and only applies for all subsequent builds... which I expect is no good for cloud builds.

I'm currently looking for a better solution. We've also opened the issue with Unity so hopefully they might be able to help from their end.

**Comment by MorrisRH** [comment] 2021-06-16 11:41
I've just updated the post-process script (see #810) which I hope will solve your cloud build issues.

**Comment by SuwasSVR** [comment] 2021-06-16 22:06
That didn't fix it.

**Comment by MorrisRH** [comment] 2021-06-18 16:58
I've managed to reproduce the issue locally. Seems the app thinning part of the export process is falling over due to the plugin being compiled with Xcode 12.5 and Unity Cloud builds are still using Xcode 12.4.

We'll get a new plugin released ASAP built with Xcode 12.4.

**Comment by SuwasSVR** [comment] 2021-06-18 18:57
Thank you. That's what I thought was happening. I did mention this a few days ago on this thread: [https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/814#issuecomment-861709058](url)

Looking forward to the new release! Thanks

**Comment by suwas-subvrsive** [comment] 2021-06-21 23:55
Thank you! Cloud builds with AVPro work now!

**Comment by alexander-mahisoft** [comment] 2021-09-16 20:16
Good afternoon! This issue appears to be fixed, nevertheless I'm presenting the same issue described with AVPro 2.2.0, is there someone else with this issue or should I look into any other thing that could be causing this? I migrated from AVPro 1 to 2 and since then I haven't been able to compile with Unity Cloud Build

**Comment by alexander-mahisoft** [comment] 2021-09-16 20:19
The compact log for this is the following, the full log is > 20 MB but if useful I can upload it 
[CompactLog1609.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7180729/CompactLog1609.txt)

**Comment by MorrisRH** [comment] 2021-09-17 08:17
This is usually due to Unity's Cloud build using an older version of Xcode. We're currently using 12.5.1.
If you could let us know what the latest version of Xcode Unity Cloud Build supports is, then we will look into getting the plugin compiled with that version of Xcode.

**Comment by alexander-mahisoft** [comment] 2021-09-17 12:06
Thank you very much for your fast reply. I checked and the last version supported is still 12.4.0 

There are plans to release Unity Cloud Build support for 12.5 by the end of this month (it's something they have mentioned since July, hope it still remains that way). Also not sure if that will include Xcode 12.5.1 or just 12.5.0

![image](https://user-images.githubusercontent.com/84341320/133779954-9ca584b0-2f2a-4b15-b49f-692ddbe696a2.png)

I'll be also happy to upgrade AVPro as soon as a fix is released and try it out to let you know. Thanks again!

**Comment by AndrewRH** [comment] 2021-09-24 16:22
moz should i remove the 2.2.1 milestone?

**Closed** 2021-09-24 16:23 UTC
Labels: iOS, Fixed, Version 2.x

**Comment by alexander-mahisoft** [comment] 2021-09-24 18:34
Thanks! I guess I need to wait for 2.2.1 to be released, add it to my project and test it out. Will do and confirm everything once that's done.
